>A_pis1 NP_001152831.1 ecdysone receptor isoform A [Acyrthosiphon pisum]
M-------------------MDQKCDGG-----------------GGGVAAAAAGIGGGG
VGGLMSY-----NR--------GRGGTEVI---------IKPRSPAVLQVTTGGGYHGLP
TATDAVIVRSPPGGHLPGQQQQQVPPSRNGCSTL--------------------------
-----FSDIAGV-------KRLRPD---DWLAVNSP---PASSPGTSHISYTV-------
------------------------------ISNGGGG-----------------GGGGGG
------GGGGGYNTSPMSTN-----------------SYDPY-SPMSG---KIVKEEL--
SPPNSLSGV---------------------------SSHS-DGLKKKKLNHSPVTGVVNT
AASGPGGGVGGNVLNNRPPEELCLVCGDRSSGYHYNALTCEGCKGFFRRSITKNAVYQCK
YGNNCEIDMYMRRKCQECRLKKCLTVGMRPEC---------------VVPEVQCAVKRKE
-KKAQREKDKPNSTT-------------------------DISPEI--------IKIEPT
EMKI----------------------ECGEPMIMGTPMP----------TV--PYVKPLS
SEQKELIHRLVYFQDQYEAPSEKDMKRL----------TINNQNMDEYDEEKQSDTTYRI
ITEMTILTVQLIVEFAKRLPGFDKLVREDQITLLKACSSEAMMFRVARKYDITTD-----
SIVFANNQPFSA---DSYNKAGLGDAIENQLSFSRFMYNMKVDNAEYALLTAIVIF-SSR
PNLLDGWKVEKIQEIYLESLKAYVDNRDRDTATVR--YARLLSVLTELRTLGNENSELC-
-MTLKLKNRV----VPPF--LAEIWDVMP-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>G_bue1 GBUE004915-PA
------------------------------------------------------------
------------------------------------------------------------
MGEESGRLAAPQ------------------------------------------------
------------------------E---DW------------------------------
---PIAYVSP--------------------------------------------------
--------SNGYSSPTTSAG-----------------SYEPY-SP-NN---KLGREDL--
SPVGSLNGY---------------------------SADSCDGSKKKK------------
---GPQ---------QRQQEELCLVCGDRASGYHYNALTCEGCKGFFRRSITKNAVYQCK
YGNNCEIDMYMRRKCQECRLKKCLSVGMRPEC---------------VVPEYQCAVKRQE
KKKQQKDKDKHVSTT-------------------------NGSPEV--------IKSEPE
Q----------------------------PPGVSSLTLTSWPEEV-KIVNQ--NGVKPVS
PEQEELIHRLVYFQNEYEHPSEEDIRRI----------------NTPTDTE-EADMKFRH
ITEITILTVQLIVEFAKRLPGFDKLQREDQIALLKACSSEVMMLRMARRYDATSD-----
SILFANNQPYTR---DSYRMAGMGEVVEDLLRFCRQMYNMKVDNAEYALLTAIVIF-S--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>G_bue2 GBUE013140-PA
-------------------------------------------------MEAGPVKSWLG
HRRSVTTINIHHQV--------GGGGCSVVVGEKSIVDEDSSAADAEVTNFTNDAVNLRH
KKNDDEIIERPMSWEGELSDSQ--------LATIKPEPNETCI-----------ENSVQI
PHGTNDPSIAHSEDEKHHSVKYALDPVNEKTAESLRSSTLSSQTELPLLVDKLLSNGVYC
RSGPVATASPDSAVYSCYSPGASPVTSRHFLSSSSGIS-SPFTPSLSRNNSDASQYGG--
-SNHSSCYSHSYSSVSVSPT-----------------QFSPTHSPIQG--RHIQRTNF--
-PSPVLSARTS--------SHSEFPNHDEAIIVDDKVSGDPLAHASPA------------
---ISR---------QQLINSPCPICGDKISGFHYGIFSCESCKGFFKRTVQNRKNYVCL
RGSSCPVSIATRKKCPACRFDKCLTMGMKLEA---------------I----------RE
-DRTRGGRSTYQCSYTV-------------------------------------------
-----------------------------PPG--------LAEPKDTTSPH--PNVPTLL
QEIMEVEHLWQYKESEGGVSQQPPIQ-----------------INNSDPSA--------N
LCNIADHRLYKIVKWCKSLPLFKNISIDDQISLLINAWCELLLFSCCYRSMSSPG-----
EIRVSLGKSISL---GEARALGLAPPIERMLNFTDHLRRLRVDNYEYVAMKVILLLTSDT
SELREPEKVRASQEKALQALQHYTLAHYPDIPSK---FGELLLRIPELQRTCQVGKEM--
-LSAKSKEGE----GPSFNLLMELLRGDH-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>G_bue3 GBUE021020-PA
MFL----------------------------RFQ--------------VASAGFIISTFE
QSCTVRFL----------------------------------------------------
------------------------------FLTF--------------------------
--------------CKVGLTRFLID-----------------------------------
---PIAEAVE-----------------FTRLSGGVGKR-QTWEPV---------------
--------GTALRSVRSHTE-----------------EFPGHESD-----SNLKRKYFIS
SESAKVRGVT--------------------------ASSSASSSPTER------------
---ASA----------NSPSQLCAVCGDTAACQHYGVRTCEGCKGFFKRTVQKGSKYVCL
AEKQCPVDKRRRNRCQFCRFQKCLSVGMVKEV---------------V--RTDSL-KGRR
-GRLPSKPKSPQESPPS-------------------------------------------
-----------------------------PPVSLITAL--VRAHVDTS-----PDLSNLD
Y-------------NQFREAAEEEIH-----------------ISESEKTQ--------Q
FYNLLTSSVEVIRHFAEKIPGYAELCPEDRDLLFQSASLELFVLRLAYRTKATDT-----
KLTFCNGVVLSR---GQC-LKSFGDWLLAILDFCQSLHSMDVDISAFACLCALTLV-TER
HGLKEPHKVEQLQMKIIGSLRDHITYNADAQKKSH-YFSRLLGKLPELRSLSVQGLQRI-
-FYLKLEDLVP---APPL--IENMFMASL-------------------------------
------------------------------------------------------------
---------------------------PF-------------------------------
------------------------------------------------------------
-------------------
>G_bue4 GBUE021385-PA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------ER
PSLLEAWKVEKIQEIYLEALKSYVDNRVRPKSPTI--FAKLLSVLTELRTLGNQNSEMC-
-FSLKLKNKN----IPPF--LAEIWDVNT-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>F_exs1 XP_029677557.1 ecdysone receptor isoform X1 [Formica exsecta]
M--------------------DTSGDSSL--------------DTANGTAAASVAASVAA
IASVV-------------------GGT------------------ASLTVKAERPDHLAG
TSTSPAVAAGPIGT----------------GSSL--------------------------
-----FAGIANS------NKTSRPD---DWLATSSP-ESPQSSLQSQHVVYTVSQQQL-S
EQPPVAHSSP-----------------HQQVSN---------------------------
---------NGYASP-MSTG-----------------SYDPY-SP-NG---KIGRDEL--
SQSGSINGYGNNSGGGNCGGGGGGNGNGSG------TSEGCD-AKKRK------------
---GPT---------PRQQEELCLVCGDRASGYHYNALTCEGCKGFFRRSITRNAVYQCK
YGNGCEIDMYMRRKCQECRLKKCLTVGMRPEC---------------VVPEYQCAVKRKE
-KKAQKEKDKPNSTTM------------------------NGSPGSAGIGDQMGVKIEPA
EAE-----------------------SLSVSGSSGILTP--------VSPY--TCVKPIS
PEQEELINRLVSFQCEFEQPSEEDLKRI---------------TNQPLEGEDPSDYSFRH
ITEITILTVQLIVEFSKRLPGFNELLREDQITLLKACSSEVMMLRMARKYDVQTD-----
SIIFANNQPYTR---DSYNVAGMGETIEDLLRFCRQMYAMRVNNAEYALLTAIVIF-SER
PNLLESRKVEKLQEIYLKTLKAYVDNRRRPKSGTI--FAKLLSVLTELRTLGNQNSEMC-
-LNLKFKNKK----LPVF--LAEIWDVMP-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>N_lug1 XP_022195205.1 ecdysone receptor-like [Nilaparvata lugens]
MELKLALYPVHNLPPLPNPLQDLQTKSTLLQRLP-----------STPTLQQNLPTEPTQ
LRNLSPLPNPHQNL--------QRTSTLLQ---------NQPSEPTPLQNLPTKPTQLRN
LSPEPNLLLNPQTQ----------------PTQLQN------------------------
---LSPENILHQ------NLHPQPTLS----------QNPQSESTHATTTMLVKREQL-D
DTTPLRGGSP-----------------RGSPTPQGGLRGSSWPPSPRDMTP---SYGGGG
------TPLNGYPSPTMSSQHS---------------NYDSCLSP-NS---KIGREDL--
SPPSSLNGY----------GGGGGPGGG--------SMDPSELAKKKK------------
---GPV---------PRQQEELCLVCGDRASGYHYNALTCEGCKGFFRRSITKNAVYQCK
YGNNCEIDMYMRRKCXXCRLKKCLSVGMRPEC---------------VVPEYQCAVKRKE
-KRDMKDKTRPNSTT-------------------------SRSPEA--------LKIEPE
SQRMCDFSVELESGNTLGASSNTGGLGAGPPSVGGSLSP--------PLTA--GGVKPVS
SEQEELIHRLVYFQNEFEHPSEEDLKRI---------GCLNLPSQVAQDQQAESDMRFRH
ITEITILTVQLIVEFAKRLPGFDKLLREDQIVLLKACSSEVMMLRTARKYDVNTD-----
SILFANNQPYTR---DSYTLAGMGYDMWDLLQFCRHMYRMKVDNAEYALLTAIVIF-SDR
PSLLEAWKVEKIQEIYLEALKSYVDNRIRPKSSPI--FAKLLSVLTELRTLGNQNSQMC-
-FSLKLKNKK----LPDF--LMEIWDVDM----------EKEKENEKKKAAAENNNSMSS
STS---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>N_lug2 XP_022195205.1 ecdysone receptor-like [Nilaparvata lugens]
MELKLALYPVHNLPPLPNPLQDLQTKSTLLQRLP-----------STPTLQQNLPTEPTQ
LRNLSPLPNPHQNL--------QRTSTLLQ---------NQPSEPTPLQNLPTKPTQLRN
LSPEPNLLLNPQTQ----------------PTQLQN------------------------
---LSPENILHQ------NLHPQPTLS----------QNPQSESTHATTTMLVKREQL-D
DTTPLRGGSP-----------------RGSPTPQGGLRGSSWPPSPRDMTP---SYGGGG
------TPLNGYPSPTMSSQHS---------------NYDSCLSP-NS---KIGREDL--
SPPSSLNGY----------GGGGGPGGG--------SMDPSELAKKKK------------
---GPV---------PRQQEELCLVCGDRASGYHYNALTCEGCKGFFRRSITKNAVYQCK
YGNNCEIDMYMRRKCXXCRLKKCLSVGMRPEC---------------VVPEYQCAVKRKE
-KRDMKDKTRPNSTT-------------------------SRSPEA--------LKIEPE
SQRMCDFSVELESGNTLGASSNTGGLGAGPPSVGGSLSP--------PLTA--GGVKPVS
SEQEELIHRLVYFQNEFEHPSEEDLKRI---------GCLNLPSQVAQDQQAESDMRFRH
ITEITILTVQLIVEFAKRLPGFDKLLREDQIVLLKACSSEVMMLRTARKYDVNTD-----
SILFANNQPYTR---DSYTLAGMGYDMWDLLQFCRHMYRMKVDNAEYALLTAIVIF-SDR
PSLLEAWKVEKIQEIYLEALKSYVDNRIRPKSSPI--FAKLLSVLTELRTLGNQNSQMC-
-FSLKLKNKK----LPDF--LMEIWDVDM----------EKEKENEKKKAAAENNNSMSS
STS---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>C_hook1 maker-scaffold389-size1115929-augustus-gene-10.2-mRNA-1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------G---------------ELRATYR---------CREDL--
SPPNSLNGY---------------------------SLDGSD-AKKKK------------
---GPA---------PRQQEELCLVCGDRASGYHYNALTCEGCKGFFRRSITKNAVYQCK
YGNNCEIDMYMRRKCQECRLKKCLSVGMRPEC---------------VVPEYQCMVKRKE
-KKAQKDKDKPNSTT-------------------------NGSPEM--------VGIKDP
EHK----------------------------QVEPEKLP----------VL--NGVKPVS
PEQEELIHRLVYYQNEYEQPSEDDLKRI---------------TNTPIDGEDQSDVKFRH
ITEITILTVQLIVEFAKRLPGFDKLLREDQIALLKACSSEVMMFRMARRYDVQSD-----
SILFANNQPYTK---DSYSMAGMGETIDDMLRFCRQMYSMKVDNAEYALLTAIVIF-SER
PSLIEAWKVEKIQEIYLEALKAYVDNRRRPKSGAV--FAKLLSVLTELRTLGNQNSEMC-
-FSLKLKNKK----LPPF--LAEIWDVMP-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>C_hook2 maker-scaffold2708-size326647-augustus-gene-1.2-mRNA-1
Q-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------QY---------------------
------------------------------------------AAADSN------------
---SST---------PAKSFVPCKVCGDKASGYHYGVTSCEGCKGFFRRSIQKQIEYRCL
RDGKCLVIRLNRNRCQYCRFKKCLAVGMSRDS---------------V--RYGRVPKRSR
-ERCGEEPGRVSTTEPD-------------------------------------------
-----------------------------QPADPDTKQLAVYDVVLAVSQAFLANCGYTE
ERTRGLMRKPIAQPSCSGAGSPDDPEVA---------------SSTAESLEQQRVWLWQQ
FATHVTPSVQRVVEFAKRVPGFCELSQDDQLILIKVGFFEIWLGHVARL--SNDS-----
SLTFADGTYVTR---QQMDIIYDAEFVSSLFHFVSTFSALALNDTELGLFSAVVLLTADR
PGVTDVKTIEHHQDRLIDALKVQVGRTHASDPQV---LTSLLVKLPELRNLGAKHSAHLD
WFRLNWAKLR----LPPL--FAEIFDIPK----CEEDLQ---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>C_lec1 CLEC002129-PA
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------WVRG-----------------YAMREEGC-D
QVT------------------------------------SSCSPGVDDLEL---WDLGLG
------------PGP-RGIQLS---------------EHRGDIS---------GREDL--
SPPNSLNGY---------------------------SADSCDGSKKKK------------
---GTA---------VRQQEELCLVCGDRASGYHYNALTCEGCKGFFRRSITKNNVYQCK
YGNNCEIDMYMRRKCQECRLKKCLSVGMRPEC---------------VVPEYQCAVKRKE
-KKAQKDKDKPVSTT-------------------------NGSPEA--------IKVEPE
PHRVSYTSSLFQSMIKESQTQ----------STEGELAK---------VAV--NGIKQVS
AEQEELIHRLVYFQNEYEHPSDEDVRRI----------------NTPNDEEEQSDLKFRH
ITQITILTVQLIVEFAKRLPGFDKLLREDQIALLKACSSEVMMLRMARRYDAQSD-----
SILFANNQPYTR---DSYNMAGMGDVVEGLLRFCRQMYNMKVDNAEYALLTAIVIF-SER
PSLTEGWKVEKIQEIYLEALKSYVDNRARPRSPTI--FAKLLSVLTELRTLGNQNSEMC-
-FSLKLQNRK----LPPF--LAEIWDVNP-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>C_lec3 CLEC001111-PA
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-EKHA-------------------------------------------------------
------------------------------------ESSGIMNANSDK------------
---IHS---------LCLGVEICVVCGDRASGRHYGAISCEGCKGFFKRSIRKRLGYQCR
GNQQCEVTKHHRNRCQYCRLQKCLTMGMR-----------------TV--------QHER
-KPISVKKEFPNHSSPFYKSLTQPSNIGQSNYGVYNSLPYNLYSDGY-------IKQESS
NII-----------------------GNYDYSNYDESS--DSDLIESIGPG--QDSKSMI
NSAMEIATKL-GMNGNFGNSDDEEMENLQFDGRLLDDNAFIFQIQSPSPMPAYTDV--HY
IYESASRLLFLSVHWVRNVPAFQILNMDTQVSLIKGCWSELFTLGLSQCAQVLALPTIIL
SIINHLQSSVAQQKISSSKVKAVTEHIFSLQDFVGSMVALNVDDHEYAYLKLIALFSPDN
PSLHIRRQLSELQEKAFQELREQIGDVNSNR------FARLLLRLPPLRALNRHIMEQI-
-FFPGLGDQCDIDNIIPF--ILKMESIDF-----------VNEQNN--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>C_lec4 XP_014241436.1 ecdysone receptor isoform X1 [Cimex lectularius]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------WVRG-----------------YAMREEGC-D
QVT------------------------------------SSCSPGVDDLEL---WDLGLG
------------PGP-RGIQLS---------------EHRGDIS---------GREDL--
SPPNSLNGY---------------------------SADSCDGSKKKK------------
---GTA---------VRQQEELCLVCGDRASGYHYNALTCEGCKGFFRRSITKNNVYQCK
YGNNCEIDMYMRRKCQECRLKKCLSVGMRPEC---------------VVPEYQCAVKRKE
-KKAQKDKDKPVSTT-------------------------NGSPEA--------IKVEPE
PHRVSYTSSLFQSMIKESQTQ----------STEGELAK---------VAV--NGIKQVS
AEQEELIHRLVYFQNEYEHPSDEDVRRI----------------NTPNDEEEQSDLKFRH
ITQITILTVQLIVEFAKRLPGFDKLLREDQIALLKACSSEVMMLRMARRYDAQSD-----
SILFANNQPYTR---DSYNMAGMGDVVEGLLRFCRQMYNMKVDNAEYALLTAIVIF-SER
PSLTEGWKVEKIQEIYLEALKSYVDNRARPRSPTI--FAKLLSVLTELRTLGNQNSEMC-
-FSLKLQNRK----LPPF--LAEIWDVNP-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>M_ext1 Medex_00015863-RA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------MFVS---------GREDL--
SPPNSLNGY---------------------------SLDGSD-AKKKK------------
---GPA---------PRQQEELCLVCGDRASGYHYNALTCEGCKGFFRRSITKNAVYQCK
YGNNCEIDMYMRRKCQECRLKKCLSVGMRPELDVLYNCHISIGCVPGVVPEYQCMVKRKE
-KKAQKDKDKPNSTT-------------------------NGSPEM--------VGIKDS
DTK----------------------------QLEPEKLP----------ML--NGVKPVS
PEQEELIHRLVYYQNEYEQPSEDDLKRI---------------TNTPIDGEDQSDVKFRH
ITEITILTVQLIVEFAKRLPGFDKLLREDQIALLKACSSEVMMFRMARRYDVQSD-----
SILFANNQPYTK---DSYSMAGMGETIDDMLRFCRQMYSMKVDNAEYALLTAIVIF-SER
PSLIEAWKVEKIQEIYLEALKAYVDNRRRPKSGAV--FAKLLSVLTELRTLGNQNSEMC-
-FSLKLKNKK----LPPF--LAEIWDVMP-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------
>D_mel1 NP_724456.1 ecdysone receptor, isoform A [Drosophila melanogaster]
M-----------------------------------------------LTTSGQQQSKQK
LSTLPSHILLQQQL------AASAGPSSSV--------SLSPSSSAALTLHVASANGGAR
ETTSAAAVKDKLRPTPTAIKIEPMPDVIS-VGTVAGGSSVATVVAPAATTTSNKPNSTAA
PS-TSAAAANGHL-VLVPNKRPRLDVTEDWMSTPSPGSVPSSAPPLS-------------
----------------------------PSPGS---------------------------
-QNHSYNMSNGYASP-MSAG-----------------SYDPY-SP-TG---KTGRDDL--
SPSSSLNGYS--------------------------ANESCDAKKSKK------------
---GPA---------PRVQEELCLVCGDRASGYHYNALTCEGCKGFFRRSVTKSAVYCCK
FGRACEMDMYMRRKCQECRLKKCLAVGMRPEC---------------VVPENQCAMKRRE
-KKAQKEKDKMTTSPSSQ-------------HGGNGSLASGGGQDF--------VKKEIL
DLM-----------------------TCEPPQHATIPL--LPDEILAKCQA--RNIPSLT
YNQLAVIYKLIWYQDGYEQPSEEDLRRI---------------MSQPDENESQTDVSFRH
ITEITILTVQLIVEFAKGLPAFTKIPQEDQITLLKACSSEVMMLRMARRYDHSSD-----
SIFFANNRSYTR---DSYKMAGMADNIEDLLHFCRQMFSMKVDNVEYALLTAIVIF-SDR
PGLEKAQLVEAIQSYYIDTLRIYILNRHCGDSMSLVFYAKLLSILTELRTLGNQNAEMC-
-FSLKLKNRK----LPKF--LEEIWDVHAIPPSVQSHLQITQEENERLERAERMRASVGG
AITAGIDCDSASTSAAAAAAQHQPQPQPQPQPSSLTQNDSQHQT----QPQLQPQLPPQL
QGQLQPQLQPQLQTQLQPQIQPQPQLLPV--SAPVPASVTAPGSLSAVSTSSEYMGGSAA
IGPITPATTSSITAAVTASSTTSAVPMGNGVGVGVGVGGNVSMYANAQTAMALMGVALHS
HQEQLIGGVAVKSEHSTTA
>D_sim1 FBpp0208736 FBgn0182106 EcR [Drosophila simulans]
MK------------------RRWSNNGGFM-RLPEESSSEVTSSSNGLVLPSGVNMSP--
-SSLDSHDYCDQDLWLCGNESGSFGGSNGH--------GLNQQQQSVITLAMHGCSSTLP
AQTTIIPINGNANGNAGSTNGQYVPGATN-LGALANG-----------------------
---MLNGGLNGMQ-QQIQNGHGLINST-----TP---STPTTPLHLQ-------------
----------------------------QNLGGGGGI-------------------GGMG
ILHHANGTPNGLIGV-VGGGGGVGLGVGGGGVGGLGMQHTPR-SD-SVNSISSGRDDL--
SPSSSLNGYS--------------------------ANESCDAKKSKK------------
---GPA---------PRVQEELCLVCGDRASGYHYNALTCEGCKGFFRRSVTKSAVYCCK
FGRACEMDMYMRRKCQECRLKKCLAVGMRPEC---------------VVPENQCAMKRRE
-KKAQKEKDKMTTSPSSQ-------------HGGNGSLGSGGGQDF--------VKKEIL
DLM-----------------------TCEPPQHATIPL--LPEEILAKCQA--RNIPSLT
YNQLAVIYKLIWYQDGYEQPSEEDLRRI---------------MSQPDENESQTDVSFRH
ITEITILTVQLIVEFAKGLPAFTKIPQEDQITLLKACSSEVMMLRMARRYDHSSD-----
SIFFANNRSYTR---DSYKMAGMADNIEDLLHFCRQMFSMKVDNVEYALLTAIVIF-SDR
PGLEKAQLVEAIQSYYIDTLRIYILNRHCGDSMSLVFYAKLLSILTELRTLGNQNAEMC-
-FSLKLKNRK----LPKF--LEEIWDVHAIPPSVQSHLQMTQEENERLERAERMRASVGG
AITAGIDCDSASTSAAAAAAQHQPQPPPQPQPSSLTQNDSQHQTQPQLQPQLQPQLPPQL
QGQLQPQLQPQLQTQLQPQIQAQPQLLPVSVSAPVPASVTAPGSLSAVSTSSEYIGGSAA
IGPITPATTSSITAAV-----------------------HFSMYANAQTAMALMGVALHS
HQEQLIGGVAVKSEHSTTA
