>A_pis1 XP_001949185.2 homeobox protein engrailed-2 [Acyrthosiphon pisum]
M--MMMTN----------------------------------------------------
-------------------CLQQSVCAEAAA-------MQAMELHRRNSGGG--------
-------------------------------------------------GDQSI-----G
KSGRDDGSATEY------NDDRVQ------------PTSGGRL-------NG-SAERPLK
FSIDNILRPEFG----------GGTGS-------LATSGGSPPTVFNPYDHH--------
-----------------------------HRHYHPHHHH-----LQ--------------
----QQQQQQQ-------------------------------------------------
QHLNHIDRLNHLNYQL-------HH----LNQ------------------LSHNAAAAA-
---------------SANTSVRAAATAINDAAG---PVSSDH--------EKSISSRRSS
SSSTA-------------------------------------------------------
--------EPLS-------------------SPIDLSCSDSQ------TYVNPAATANST
TVSTTAAA-------AAAAH---------STTNTTHAT------------------TTTG
SVDAAINAVADK------EGSQQWPAWVYCTRYS------DRPSSGR------SPRTRRA
KK-KDK--------------------QQQDEKRPRTAFSGDQLARLKKEFTENRYLTERR
RQELANELGLNEAQIKIWFQNKRAKIKKASGT------------------KNPLALQL-M
AQGLYNHSTVMVTK------------------EEEEQLAAAQAMENN-------D-----
------------------------------------------------------------
-------------------------
>C_lec4 XP_014245624.1 homeobox protein engrailed-1a-like [Cimex lectularius]
---MALEN----------------------------------------------------
-------------------AVEKRTSA----------------FHR--------------
------------------------------------------------------------
------------------------------------------------------------
--IDLLTRPE------------------------------KFPGV---------------
------------------------------------------------------------
------------------------------------------------------------
-----LPRL---------------------------------------------------
------------------------------------PAYSPG--------KESIYPSSKE
SPPPA-------------------------------------------------------
--------QPEP-------------------APTLSFSVDN--------ILSPEFGKVAR
RVAASLPQ-------SACPR---------KGVEEVPSP------------------TKID
PV------IPDD------PNGPVWPAWVYCTRYS------DRPSSG--------PRSRRI
KR-KDK---------------------AKEDKRPRTAFSGEQLARLKSEFSINRYLTERR
RQALAGELGLNEAQIKIWFQNKRAKIKKASGS------------------RNPLALQL-M
AQGLYNHSTVPMSD------------------EEDDENSMQNGLSH--------------
------------------------------------------------------------
-------------------------
>C_lec5 XP_014246084.1 segmentation polarity homeobox protein engrailed-like [Cimex lectularius]
---MVEMS----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------GEGQEGTRV-------
-----TPSPPSS-------------------ERALKFSIEN--------ILRPEFG----
--------------------------------------------------------TKST
PV------VREK------NEETVWPAWVYCTRYS------DRPSSGR------SPRTKRI
KR-KEK---------------------NADDKRPRTAFSGEQLARLKTEFNVNRYLTERR
RQALAAELGLNEAQIKIWFQNKRAKIKKASGS------------------RNPLALQL-M
AQGLYNHSTVPVKD------------------D---------------------------
------------------------------------------------------------
-------------------------
>D_mel1 FBpp0087198 FBgn0000577 en [Drosophila melanogaster]
---MALED-RCSP--QSAPSPITLQMQHLHH---QQQQQQQQQQQMQHLHQLQQLQQLHQ
QQLAAGVFHHPAMAFDAAAAAAAAAAAAAAH-------AHAAALQQRLSGSGSPAS----
-------------CSTPAS--------------------STPLTIKEEESDSVI-----G
DMSFHNQTHTTN------EEEEAEEDDDIDV-DVDDTSAGGRLPPPAHQQQS-TAKPSLA
FSISNILSDRF-----------GDVQK-------PGKSMENQASIFRPFEAS--------
-----------------------------RSQTATPSAFTRVDLLE--------------
----FSRQQQAA-----------------------------AAAATAAM---------ML
ERANFLNCFNPAAYPR-------IHEEIVQSR------------------LRRSAANAVI
PPPMSSKMSDANPEKSALGSLCKAVSQIGQPAA---PTMTQP--------PLSSSASSLA
SPPPASNASTISSTSSVA------------------------------------------
---TSSSSSSSG-------------------CSSAASSLNS--------SPSSRLGASGS
GVNASSPQPQPIPPPSAVSR---------DSGMESSDD------------------TRSE
-----TGSTTTEG-----GKNEMWPAWVYCTRYS------DRPSSG--------PRYRRP
KQPKDK---------------------TNDEKRPRTAFSSEQLARLKREFNENRYLTERR
RQQLSSELGLNEAQIKIWFQNKRAKIKKSTGS------------------KNPLALQL-M
AQGLYNHTTVPLTK------------------EEEELEMRMNGQ----------------
-----------------------------------------------------IP-----
-------------------------
>D_sim1 FBpp0224300 FBgn0044189 en [Drosophila simulans]
---MALED-RCSP--QSAPSPVTLQMQHLHHQQQQQQQQQQQQQQMQHLHQLQQLQQLHQ
QQLAAGVFHHPAMAFDAAAAAAAAAAAAAAH-------AHAAALQQRLSGSGSPAS----
-------------CSTPAS--------------------STPLTIKEEESDSVI-----G
DMSFHNQTHTTN------EEEEAEEDDDIDV-DVDDTSAGGRLPPPAHQQQS-TAKPSLA
FSISNILSDRF-----------GDVQK-------PGKSMENQASIFRPFEAN--------
-----------------------------RSQTATPSAFTRVDLLE--------------
----FSRQQQAA-----------------------------AAAATAAM---------ML
ERANFLNCFNPAAYPR-------IHEEIVQSR------------------LRRSAANAVI
PPPMSSKMSDANPEKSALGSLCKAVSQIGQPAA---PTMTQP--------PLSSSASSLA
SPPPASNASTISSTSSVA------------------------------------------
---TSSSSSSSG-------------------CSSAASSLNS--------SPSSRLGASGS
GVNASSPQPQPIPPPSAVSR---------DSGMESSDD------------------TRSE
-----TGSTTTEG-----GKNEMWPAWVYCTRYS------DRPSSG--------PRYRRP
KQPKDK---------------------TNDEKRPRTAFSSEQLARLKREFNENRYLTERR
RQQLSSELGLNEAQIKIWFQNKRAKIKKSTGS------------------KNPLALQL-M
AQGLYNHTTVPLTK------------------EEEELEMRMNGQ----------------
-----------------------------------------------------IP-----
-------------------------
>C_hook2 en-PA--to--C_hookeri_NQII01000299.1_1_en-PA_FBpp0087198_FBgn0000577_engrailed
---ALREH--CTP--VQSPAPLSLALQALHG---TPQSEIGDKNRLQHLRDVTELARSHD
DTFPPFFFHTATPQIPGASGTATTVQHRSST-------AQVESLRHAVACGVRPTA----
--------------RTPTA--------------------KSSDTYHENQIDGLV-----I
LLDISCLLRPIN------RKVEAMEQGKLDR-QIRSPRRTTHLPFRTKHRQI-TAHVTEA
MAIKHCLDKFI-----------GNIRK-------LGKSMINTSSLYFSHTCT--------
-----------------------------RTHTHTSGDRTRIAVLG--------------
----GERPGHYA-----------------------------TAAPRVGM---------RL
HGGKFLYCFSPVAYSR-------ISQGERVVT------------------LDRREEKEVI
EHPLEIKMAMYDVQQRGLGLVCKQGS-VNNPPP---PTHLSD-------PLLESSPSVVR
PPTPPPITPVFRARVMIS------------------PPLPLSSWGSGWPGPRVRAASCPR
LFRPHEESPPPP-------------------PLAATAAASP--------PLSP-------
--ASSTLS-------SSSPA----------------------------------------
--------VPEDKVDPPINGPTLWPAWVYCTRYS------DRPSSG--------PRSRRI
NRNKDK---------------------KPEEKRPRTAFSGEQLARLKHEFAENRYLTERR
RQELARELGLNEAQIKIWFQNKRAKIKKASGH------------------KNPLALQL-M
AQGLYNHST---------------------------------------------------
------------------------------------------------------------
-------------------------
>F_exs2 XP_029674962.1 segmentation polarity homeobox protein engrailed-like isoform X1 [Formica exsecta]
---MSSTS----------PAP---------------------------------------
-----------PMGLDTGSESEIRSNHLISRLDQDSEDAEKRDRARRTECSNADSD----
-------------CESDTS--------------------EVLSVGSEPTPTSVVGVRVCG
TMRYHDQELTMT------MTAELT-----------PSSGRGEFRDEENTRTSETSSPASS
TSCNDLYYQRTSSNH------VSAPSP-------PGYSQPPSSPTASSVRSP--------
-----------------------------ASSSATASSPGRPEAIQEAI-----------
-VPRYQSGHQQH-----------------------------LLSRYSSR---------ES
EISDYPTRVHGIGHEI-------IYPT--VER------------------LHRTP----I
SVPLVTRLSLSPPSAMTVTGLQATTPGVLHPAACRDPRETAT--------LMPHHSQHLH
HPNAHTHLQQSSQVQHVPANSVHQHRLSVSKLLQRDPGSPASPTGTREENGRT-------
--LPAANGVPNSIGNNGNHHHNNHNNNNNLQHQSLKFSIDN--------ILKADFG---R
RITDPISLKKS-RPKKVSSRPIDLTKDFLESSSDASERSSSETTTTTTTNTSPTSVSTGN
SASKATGSTATD------PGKMLWPAWVYCTRYS------DRPSSGRRPSRVAGPRTRRV
KR-TDGR-----------------GGGTPEEKRPRTAFSGEQLARLKREFAENRYLTERR
RQQLSRDLGLNEAQIKIWFQNKRAKIKKASGQ------------------KNPLALQL-M
AQGLYNHSTVPLTK------------------EEEEQAAELQAK----------------
------------------------------------------------------------
-------------------------
>D_sim2 FBpp0327509 FBgn0182565 en [Drosophila simulans]
---MSTLA-------STRPPPLKLTIPSLEE-----------------------------
--------------------------------------AGDHAQERRAGGGGQEVG--KM
HP----------DC--------------------------LPLPLVQPGNSPQV-----R
EEEEDEQTECEE--QLNIEDEEAEEEHDLDLEDPASCCSENSVLSVGQEQSE-AAQAALS
AQAQARQRLLI-----------SQIYR-------PSAFSSTATTVLPPSEGP--PFSPED
LLQLPPSTGTFQE---EFLRKSQLYAEELMKQQMHLMAAARVNALTAAA-----------
----AGKQLQMA-----------------------------MAAAAVAT---------VP
SGQDALAQLTATALGLGPGGAVHPHQQLLLQRDQVHHHHHMQNHLNNNENLHERALKFSI
DNILKADFGSRLPKIGALSGNIGGGSVSGSSTG---SSKNSG--------TTNGNRSPLK
APKKSGKPLNL-------------------------------------------------
---AQSNAAANS-------------------SLSFSSSLAN--------ICSNSNDSNST
ATSSSTTN-------TSGAP---------VDLVKSPPP------------------AAGA
GATGASGKSGEDS-----GTPIVWPAWVYCTRYS------DRPSSGR------SPRARKP
KKPATSSSAAGGGGGGVEKGEAADGGGVPEDKRPRTAFSGTQLARLKHEFNENRYLTEKR
RQQLSGELGLNEAQIKIWFQNKRAKLKKSSGT------------------KNPLALQL-M
AQGLYNHSTIPLTR------------------EEEELQELQEAASAAAAKEPC-------
------------------------------------------------------------
-------------------------
>A_pis3 XP_008189874.1 LOW QUALITY PROTEIN: segmentation polarity homeobox protein engrailed-like [Acyrthosiphon pisum]
---MALETERCSPNNASSPGP-------------------TDNNRRPGLDDCSDQ-----
-----------TKEVVSSSASSSTTTSPQQP----QPDVTVSAFRPVRDGAAADGDDDRM
PPKAVAEESSLLACSKPLSICSPLQNKTAVAVDPLYNRHSSPPPLQQPVRKKSS-----T
HVQKAQQVTTDVPRWVQLQQQQQHVAHNGDH---------GPLQPPSNAAAAAAVEYTMA
MAAAAAAAAGSGGHVPHGFPFNSWMYRFNFLPIVPAAAEYFREIQHHNLQHPTDGGSPET
TDDRPPAALHLQSQHAEFARQLQLNGTVGNLHHHHNPVVPSPQVVQSAAHQPLQPPPPPP
PPPQPSSQQPPMMPTGYVSRPASTSGSSDVSSSYGCGGGPLMAAGAGTTKNCSSYRSPSP
RSPSPFRLAFSVDNILRPEFGSKLHHHLQQQQEHQHHLHHHHHQPLPQHNRLGRPLSASP
PPPTAAKLHFSTLLQNKPHTQQSTLS-LHRPA----PTRPKA--------AVVGPKRPAP
AVAPDKVNKRK-------------------------------------------------
---PAQQPLPAC-------------------SPVISNNNNNC----YD-------SDNSK
SANGSRNNQHHHKPDDSGNEQE----------------------------------SAGS
DATGSGDQQS--------NDKEMWPAWVYCTRYS------DRPSSGECENGL-SPRSRRM
KR-NDK---------------------VPEEKRPRTAFSGEQLVLIEDKFNEIRYLTESQ
RHELSTSWVLNEALDKIWFR-QXGKIKKFSGS------------------KNPLXLQL-M
AQGLYXHITVAMSD------------------EEMDDHMTVASS----------------
------------------------------------------------------------
-------------------------
>C_hook1 en-PA--to--C_hookeri_NQII01000084.1_1_en-PA_FBpp0087198_FBgn0000577_engrailed
VLQMGHLQ--------QKPHHRQLQSRRQRHR-----------HLRMG--------HLHQ
RKLIPTAYNQPTLAFTTNPPAATAAESGATP-------GHAQYSAARLGSSTPPSQ----
-------------CSVYDR--------------------HPSLSIRTPENTSGV-----R
AMGFKSTITVSP------SNGHSQHYTEPHL-AAPTTSPGEDVPVPPSENQE-EIADTLI
FSIPNLYNNK-----------FTWCQK-------RGRKKETKXXXXGSFKPP--------
-----------------------------RRQSALACQATQP------------------
----RLYQRPRRLT--------------------------LNGSPASTTILLSRH-----
---DYPTRYSVSGIPP-------THSAIPHDR------------------LSGTQSVPVV
SRPLNSGLALQGRPAFNLGWYCSDSAIFGRPQP---RTWEEG--------QFEGEGVAAP
SPPAGAPGSAV-------------------------------------------------
---PRSTPAAAL-------------------SRTGSSTCTYTTT-RVPATAADALPGPGV
AVTSSYTRPLHVVPPPHANKAWEI--------------------------------TTEG
RRTANTETASTSC-----GVPQLWXSWQHCTGHA------SRRRRTA------KYRQTRD
PR-----------------------AQRSAFQPRKRTFSSRHLTRVKKLFSQSRYMIHRD
RKQMRVEIGLRHNRISRWFIQEDVRFSTNSGT------------------PPPSPLRL-L
RQGNFASAHNGKGK------------------QNENFGLNMNDK-----------L----
------------------------------------------------------------
-------------------------
>F_exs1 XP_029661733.1 homeobox protein engrailed-1a-like [Formica exsecta]
---MIYHRME--------------------------------------------------
------------------------------------------------------------
------------LC----------------------------------------------
------------------QNREKMNNDVYDLRRTRSLSNENEAYSNGNEQGD-RSPNVNR
ESIEYVSDSSCEG--------YREFQK---------------------------------
------------------------------------------------------------
----QQTERRNLSP--------------------------IAASSAFTIDNILGR-----
------------------------------------------------------------
-------------------------------------------------NEKRDQTSRID
SSGDKEEDQEEMDDRIEG------------------------------------------
-----------------------H-----FVRPTA-----------IPATRPDLEGGLYT
HTGFSYPD----------------------------------------------GALTDS
SAYSATSLASASL---------LYSSWFAQTK------------PGQLFGLQ-APKPSGR
RS-----------------------RKPGIDRKPRQAYSAKQLERLEAEFKIDKYLSVSK
RMELSKCLNLTEVQIKTWFQNRRTKWKKQLTS------------------RLKIAQRQ--
--GLFPPTYFPTTQYPLLPYYAAPLMFGGPLSDDANSSLPTRST----------------
------------------------------------------------------------
---------VSSSDTV---------
>G_bue2 GBUE021017-PA
---MSKFIID--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------SMLPK---------------------------------
------------------------------------------------------------
----YHQQYQPQM-----------------------LPGGLSSSGTASTEQ---------
----------------------TSYSTTSSSGSA----------------SSGTAGLSC-
NSPPPPPV----RMYPYV-----HGPQTPALP-------------------FGAPSMTAF
SSMAAVVDAA-------------------------------------DKSCRY-------
-----NASSAES-----------------MAGYSLHHQNGV----------------SVS
AASASMAAAAQFYHQAAAASA-----------------------------------ATDP
LTSCATQVASASS-QPMPDIPR--YPWMSITDWMSP---FDRVVCGMLPG----------
-------------------------PNGCPRRRGRQTYTRFQTLELEKEFHFNHYLTRRR
RIEIAHALCLTERQIKIWFQNRRMKLKKELRA------------------VKEINEQ---
------------------ARRERE--------EQERLSKEKQGK----------------
------------------------------L--DVGGV------------------DPHK
IM---SLEKNSVADMIKPTVGKVQT
>C_lec2 CLEC025113-PA
---MSKFIID--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------SMLPK---------------------------------
------------------------------------------------------------
----YHQQYHHQL-----------------------LNPVITSGSDSSA-----------
----------------------VNYSSTATNNSS----------------SSS-------
NSPPPSLVSSASRMYPYVAAHHHHGQQAAGLAAF--AGAAPG--------GMGAFSSPSS
AALAAVVDAAT----------------------------------GGDKSCRY-------
---TGNVPTADS-----------------MVNYSLHHQNST--------------SSSVS
AASASMAAAAQFYHQAAAASA-------------------------------------DP
LSSCTTQVASAATGQPMPDIPR--YPWMSITDWMSP---FDRVVCGMLPG----------
-------------------------PNGCPRRRGRQTYTRFQTLELEKEFHFNHYLTRRR
RIEIAHALCLTERQIKIWFQNRRMKLKKELRA------------------VKEINEQ---
------------------ARRERE--------EQDRMNKEKQAK----------------
------------------------------IGSESGGG-----------QHHQIH-DPHK
MM--GGLDKSSGQDLLKAVVTKVPT
>C_lec3 CLEC025236-PA
---MNSYF----------------------------------------------------
---------------------------------------------EQTGFYGSHHH----
------------------------------------------------------------
------------------QSSTAAH-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
----HHDQTAAAYR----------------------FPLGLGMSPYASSQHH--------
-----------------------HHHSLHQSRPP-------------------------Q
DSPYDASVAAACKLYSATNDNQTSVNYSTTKPDC--SKTEGG--------HQNGYAAVVA
AAAKDVWQSAS-------------------------------------------------
---AGSTPSANP-----------------LVRPSACTPDSR-----YPGLTEAAGGSPGS
ASRTSASSLAPSWNQCSIN-------------------------------------TASS
QAPVGTQIHQQAG-------NHTFYPWMAIA-----------------------------
-------------------------GANGLRRRGRQTYTRYQTLELEKEFHTNHYLTRRR
RIEMAHALCLTERQIKIWFQNRRMKLKKEIQA------------------IKELNEQEKQ
AQAQKAAAAAALAA------------------QQQQDH----------------------
------------------------------------------------------------
-------------------------
>C_lec1 CLEC025152-PA
---MSSYQFVNSLA----------------------------------------------
------------------------------------------------------------
------------SC----------------------------------------------
---------------YQQQGGQRSGASPVDH--------------PQSPAGD--------
--------------------------------------------YYPNVNYPAGCY----
------------------------------------------------------------
----SPQQYPAQY---------------------------MQQSPGGMMDYTQLH-----
---------------------SAQHQRLASHLQP----------------LHGVPSPGAV
SPILNNNNPSVTNLSGSTSCKFA-------------DSTTSGA------NGISSPQDLTT
SSAPGGRTSPP-------------------------------------------------
---LGKTSLHSPS------------------NPTSRTPTAP-----LP--TSQSSSSPAS
STSSSSST------------------------------------------------PGAP
GAGGGNGTSGSAGGKPTPGNPPQIYPWM------------KRVHLGQSTV----------
-------------------------NANGETKRQRTSYTRYQTLELEKEFHFNRYLTRRR
RIEIAHALCLTERQIKIWFQNRRMKWKKEHKMA--SMN------------VIPYHYHM--
------------SQPYGNPYQFTH------------------------------------
------------------------------------------------------------
----------------------LTT
>N_lug1 XP_022188976.1 homeobox protein engrailed-like ceh-16 [Nilaparvata lugens]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------MKT
SYSSSDE-----------------------------------------------------
-----STPGEDS-------------------QWTSGHHSDFS----IDFILNEAGPGYRR
RLQRSGTP-------EAANRTE-------ISLGNSPPLD---------------------
-----------------------GFAWLQCTRYR-------------------PPKLQRN
RR-KEGR------------------QRRQPGRNPRIPFSAEQVALLEQRFRASQYLGGSE
VAKLSTMLCLSDTRVKIWFQNRRARERRERQTN--SSNSTNSLPDKQEKSSNPVLGES-P
AKSQMKILPTSQTS-AFMPYSLKL-ASNSTMDNNSSYNLIKNVANSNMDNNKCYNLAKNV
SNSSMDNKSYNFVKDATNTKMEINIYNRIKTASNSMNDHSIVKNYTFY-QEAPLELSPHA
RVENRRLNITTCK------------
>M_ext1 Medex_00100153-RA
---MCT------------------------------------------------------
------------------------------------------------------------
------------AC------------------------------------------R---
------------------VAGEVQDGCVCDV-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------ADGAPGE------GPKLKCN
LR------------------------KHKPNRKPRTPFTTQQLLSLEKKFREKQYLSIAE
RAEFSSSLHLTETQVKIWFQNRRAKAKRLQEA---EIEKLKMAAVAA---ARPHALYG-P
AASPYFHH----------PHHQPPPGAGHHPHHHHAADLLAHHA----------------
------------------------------HLSALLGRHPMLPPP-----GLCVPPPPPA
PRPPSPLS-----------------
>M_ext2 Medex_00096568-RA
---MKPVL----------------------------------------------------
------------------------------------------------------------
----------RLLC----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------GVLTGGSTTTNE----------
------------------------------------------------------------
------------------------------------ETSPPAS------PRAVSLDQRRS
SPTSSEENQ---------------------------------------------------
---YGGSPPPSP-----------H-------RPPPPHHLASLLAPHHPAFLHLAKS----
--------------PPAAHEPD-------DDGDDDDDY------------------DKDA
KKEGSTSGGGAGGG----------------------------GSSGNGGGGG--------
----------GG------------GSSNKRKKKTRTVFSRSQVFQLESTFDMKRYLSSSE
RAGLAASLHLTETQVKIWFQNRRNKWKRQLAA---ELEAANMAHAAQRLVRVPILYHE-A
AAAAAAAAAQGAAQGGGAPASSGHHGVALHP-HHHHHHLEAAGA----------------
------------------------------VATSSATTTATFPPPLYYHHAHSLPASPVA
SR-------APLSSLV---------
>N_lug3 XP_022207918.1 segmentation polarity homeobox protein engrailed-like [Nilaparvata lugens]
---MATGVVTEEES-SGYESKRCLQKKRMKSG--------GVVNLRNGLDEMRE------
-------------------CCSQESQEEEED---DDEEISVGCPSPVPGDEGASSS----
-------------CSDGGR-----------------------------------------
------------------TSSMSSGSTTVDCRTRRSCDSEEENDRPEDEYFK-PLKRLKM
MKIDKVSYSIGGS--------KTKISR---------------------------------
------------------------------------------------------------
----RPRGREERAA--------------------------VAAAAAGCS-----------
----------------------VRRQSVPDEG----------------------------
------------------------------------STTASGVKSFSILDILNHRPSRET
SAGVGGSIPKIVRPWDYG------------------------------------------
---ADSCPPHAH-----PHHHHPH----LQVRPKSADFCPKSAD--FCASSTCSSGRSST
AGSDCCTSPDILNCSLAAPGSR---------------------------PHPHPHAASRG
KAAKSADNSPLD-------------ALYQMTSKTFEELNGESGSDGQ------ANHLNLF
NS----------------------RQQPKKKRKSRTAFTNTQIFELEKRFLYQKYLSPAD
RDEIAAQLGLSNAQVITWFQNRRAKMKRDMEELKKDVESAKVLA------THQSFLENVQ
NLGILKKKSVVTSD----------------------------------------------
------------------------------------------------------------
---------EKGMTVV------IEK
