>A_pis1 XP_008185917.1 insulin-like receptor [Acyrthosiphon pisum]
MCGECD----------KIR-------------------------CLR----DSC------
------------------------------------------------PGL---------
--------------------------------GGCR---------L-----CGNF-----
--------------------------SSNIYYEH---------------------Y-NFL
RPSSSAKFSKVNPKHYRKPWLIATKSVWKSDFLCI-------ALWCVAILSVSQ------
------------ASAEHQTQITSLPPIVAQPTNNSG---------------VHFSAGRIC
QSKDIRNKAE-NLNALRGCRVIEGFLQIVLIDNANETSYESLSFPELREITGYLLLYRVN
GLKSLAKLFPNLSVIRGQDL-------FMSYAIAIYEMVHLQELGLYNLMDVVRGAVYIT
KNPMLCFTQTIDWIRIAPSG-KESHDIYDNRPVNACPV---CPWT---------------
-NDISCSVSNHTNEPLCWNT---EHCQRI-CPPECGNLSCTD------DGTCCHEQCLGG
CT--GKNHDDCFACKY-LADERDCVKECPAETLTYQNRRCILERDCYRMPRSRDLQN---
---GLHLQSWKPFNNKSCVMECPPGFEEVPTENSYGKVFKCQQCSGP-CRKVCIAANV--
-ESIQSAQKLKGCVIINGS--LEIQIRGGM--NIVKELEESLSMIEEITGYLKVVRSFPL
VSLTFLRKLHVIRGE-TLESS------------KYALVVLDNQNLVELWDWSTRKPDGEL
RIERGQIFFHFNPKLCIYRIKQLQTNLGDRFKNVDDLEVAPNSNGDKMACTVKKLNVSTE
VVLSNSVLLKWSP--------------FEHYDTR---TLLGYVVYYLEAPYKNVSLYDGR
-DACGGDGWKTDDVESTEA----------TTYDLVALITGLKPYTQYAYYVKTYTMASE-
---SNGAQSDIDYFRTMPGTPSPPQNLRVKSVTADSINIEWMPPAEPNGELKHYIIKYTS
INISGDSLL--KRDYCQNS----------------PNVNEFPDSYSGSLNEMVNNDKKEN
CNCTDQPEKKQSK---IKDEQQIQIMIEFEN--------------NLQNILYVKTNPKSD
T-------------------------------------SPKKKRD------VSNFDLQEF
-------PNSTIRINLLSDADKN---------------LENENK-------------KI-
--VVPSNQLTFTLHENLTHFTSYNIELYVCREWL--TNEIKEPNQNISNCSIQKAMTTAQ
TSKKESADRIDQ--LTVKAVNANTTSPGSIKIFWKEPEVSNGPIVSYQLEYKKVG-DHLN
---PPVVCITRQQ----YQQSDY---SHTLSNVAPGNYSFRLRARSLADYGEFTQYSYFL
IPEALSITTPQ---LMFIIFMVTGMIGAV--IMLIFYVLHRYYKNKLASTRLFVTCN--P
DYVSC---EYQTDEWEIPRDDV--EVLEPLG-RGSFGMVYRGNWKK-KEN-EIVPCAI-K
TV--TENNNMMVRHDFLSEANVMKEF-CSAHVVRLYGVVSQGQPAFVLMELMPQGDLKSY
LLKHRPEM------------TTDPSLKPPTLRDNLRMAIEIADGMSYLSFKKYVHRDLAA
RNCMVSDNNIVKIGDFGLTRDIYQTDYYRKDS-------------EGMMPIRWMAPESLQ
SGLFTCFSDVWSYGIVLWEMVTLAAQPYRGEIDKNVISYVSSGGIMEKPDNCPDIIYDCM
KLCWRFKASERPTFAEIVKMFL------PCA-RADFAQTSFFHNELQSETQRLDVSENGI
TETESLERERKQTERDQITTALENQAHYWGGSLPVERLAPKADLEEDDDDDED-------
------------------------------SDNELQRLHIENFACKRPP-----------
---------------------------NGYM-----------------------------
------------------------------------------------------------
---------------SIHNGNGINTTIC--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>G_bue1 GBUE019859-PA
MGRSV-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
SVGL------------------------------------------SAETSKNNDSLSIC
GDVEIWNPQDKDATRLKKCSVVEGYVRLMEVDAG-----EDFVFPDLREITGYLMVFRVR
GFDSLGRVFPKLGVIRGNVL-------FANFALIITESFDLKTIGLTSLSHIVKGKVWIA
SNVNLCYVTTVDWDSIVRDS-RK-HYLEGNKSPNECPV---CR-----------------
----NCTKS-PTGKTSCWNL---TSCQATACPSTC-PNNCYN------ETTCCHEHCLGG
CS--GDKADNCYSCKH-YRLADKCIKSCPAGTYVYAGWRCTNESECYGFPK---------
---TPSNNHWKPHDG-QCVLDCPFGYHEQEVYIGGAKRFQCQKCEGGFCRKECNGASI--
-KNKNDSVLMSGCTVVRGS--VVISLSGSGK-DIISELENNLNTVEEITGLLKITDSYQL
TSLNFLKNLKYIHGN-ERYKS------------KYSLVVEGNKNLKLLWDFDNKRT--KL
KI-NGLVYFGNNPKLCVNVIQQLLDKA--DIPA-SDAFYPNMTNGVKSVCDLKNLTTSYI
NVTSNAVNITWKA---------------EYHDLR---KVMGYVIYIKETIFKNVTVFDGR
-NECGRGGWTVYDVDGSE---------------AEYKIVSVKPYTSYAFYVETVTINAD-
----FGAKSEIKYFNTLPGIPNPPSYVNVITNSSSELVITWPPPLEPNGNLSHYLLS-IY
ELDDKSTLNNAVENHCEGKDAY-----------FVPSNSTR---YSGSSDRFNHYLDRH-
-FTSQLSDEEKAR--------QTQVAMLIED--------------KMNNYIYVKN-----
--------------------------------------PKRPKRDTIF---VNEAEPVIF
NHT----LQETTVKTQIDHSNKTQYKTNYTPV------SENQNLPIIQRDDT-IKKVILD
HEKIDKSITLKTV-KNLKHFTKYRVEVQACRQRT----QKELDSSLDNHCS-DSASELIK
TCPSVTADSIPNESLSPKVLNENP---GTVELKWEIPKDPNGIVLLYTVEYRR---SGYN
---PITEIVSQKE----FLKSNS---VYILKKLRPGNYSVRVRASSSSGVGPYTTSKYFY
IKDDSSIHSYI-------YLILGTLLFILPPAIAYCVYYLRK----TEKNKLFISVN--P
EYSHK---TYVTDAWEIPRNHI--DLIKEIG-QGSFGMVYEGLLNS-------KPCAV-K
TV--NTQASDGEKKEFLNEASVMKAF-DTYHVVKLLGVVSLGEPVYVVMELMPNGDLKSF
LRSHRPDVC-------------DPHLRPPSVRRLLQMSAEIADGMAYLSAKKYVHRDLAA
RNCMVAENLTVKIGDFGMARDIYIGDYYRKGT-------------RGLMPVRWMAPESLR
DGIFLSASDVWSYGVVLYEMVTLAAQPYQGLTNDQVLRYIMDGGVMERPENCSDKMFDLM
RRCWRQNPGDRPGFLEIVETLH------QDV-SLNFHAVSFYDSDQGKQHRRLIELN---
-------------IQSS-NKPF--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>G_bue2 GBUE021108-PA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---ELCFTDTVDWSRIVKGE----PFLY-RKTNLPCPA---CPK----------------
----SCPTS-------CWNS---THCQVI---------DKVI------AEAECNEQCIAG
CT--GPGPHQCTACKH-LLRQGVCTNTCDDNEFTYQKRHCVTEEKCKNMTFSGIGKRFI-
---LEESRPWFTWDR-TCIQNCPKDFERDE-------KKGCRKCSGA-CRKVCPGLVV--
-DSTQSAQTLEFCTHITGN--LEIQIQSNSSVNITDELDKFLGLIEEIEGYLKVIRSFPL
VNLYFFRNLRVIRGL-QTSSSRKELLQKDNPPHNYAFRVLDNPNLQELFDWNRPAR-KNF
TIENGRIFFHLNPKLCLKYVEEFIQIT--NITNITDLEVDKTFNEKMFACNVKNISVYVS
VKTSNSFVVGIKSD------------ILNISSSE--QDWVRVLVYYKKAPSMNVTSHYDD
-NVCKDDDWKFNDFKTEYGDD-----GDGTPLIRPQLITQLEPFTQYAYYVRTYSLG---
--------SPIHYVRTLPTKPSSPENLQGYSDSSDKIIFGWLPPSHPNGLLKEYIIRIVL
LEDDQDLPK--FRNYCANPAHFTGN-------------------TTPPPDFKT-------
-IIKEDKSKELTIPKMLCDQSDFDK---FGK--------------ISESFLQDHHIK---
----SCERSMY------------TIINENVLKPKFSS-RSKERRS------TKKANQNTR
EN-----KDDEDVHSF------------------------GKNGTTYNTDGT-IKTETI-
--SVSSNVTSYTL-TNLMHFGRYLIEIKVCREKAP---EEDMKYFLDSQCS-DMSFITYR
TLKSYSADIVDHNSIVIQVTNKSA------TVKWKKPSSYNGVILNYILEYKKIDEENPN
LHFKATECIAAFS----NKSSIT---SFALTNLNYGEYAVRIQTISLAGKSPFSGPVNFY
IVDDSYSNWMEKLAVIIVVTLVCIFGALL--SAKGMVYYYQKKL--KETNILIETIN--P
EYTSV--NGYIEDDWELSRDDI--VLVNEIK-QGNFGMVYEGLLLP-----ENRKVAV-K
TV--KETAPPRDNYDFLNEANVMKAFSGAHHVVKLLGVVSKGTPALVVMELMVLGDLKSF
LRLSRD----------------SPQYPPPSASRLNLMAAQISDGMVYLEALKFVHRDLAA
RNCMVSEDLTVKIGDFGMTRDIYDTDYYRKGN-------------KGLLPIRWMAPESLN
DGVFTSFSDVWSFGVVLWEMVTLATQPYQGMSNEEVLQHVISGNKLDTPVYCPPLLKMIM
HSCWKWKPKLRPTFVHILNLLD------PTL-NNEFRSNSYYHSVDRERTRLVESED---
-------------YRDNEHTSL-----------LLLPSSSSVEFHPSNND----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>G_bue3 GBUE020965-PA
MM----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------KQELRRHDKTYSIKWQS----------------VMFDHFIQGSSLIK
TSGVLFFGILLFSSLVNGSHKADIPSALRIYSEVV----------------HNDEDASVC
QSKDIRNTVD-MFVELQGCKVIEGFVQIVLIDKAEPADYVNISFPELREITGYLVLYRVQ
GLKSLSKLFPNLSVIRGNTL-------FLDYALVVYEMLQLQDIGLSSLTNILRGGVYFA
KNPMLCFAESIDWDIIAPHG-KGDHHIMGNKNNFECPL----------------------
------------------------------------------------------------
---------SCFACKH-FLYNNECVERCPQGTYEYLNRRCVTDKECLNMPKPRENTDH--
---NTKNKPWKPFKK-ECVLECPPGHVEKQVFVKGEMRMDCEKCKD--------------
--------------------------------NMVRELEDNFNTIEEINDYLKIVRSFPL
ISLNFLPNLREIHGR-KLESS------------KYALVVLDNQNLIELWDWNNRST--GL
TIGNGRLFFHFNPKLCYDKIEELRKKT--NLSAHSDLEIARNSNGDKTACNVDKLNVTVY
KKTAVAALIKWRQ--------------FENNDPR---TLLGYVVYSIEAPAKNISIYDRR
-DAC-DDEWRVDDVSVQEDTDAS------EEKEVNHIIAQLKPYTQYAFYVKTYTIATE-
---TRGAQSPIKYFRTEPDIPSEPHGISIQSNSSSELVLRWKPPTHPNGNVTHFIVTAVL
EPDNEEDVE--HQNFCLEPLLF-------PDIRRVPSKNPFQD-MVGPKDERNGSTDNES
CSCNQKFIDNQLR------MKEIA----FED--------------YLQDNIFIKRESYE-
-----------------------------------EYPNGKEKRE------IPKSFSSVF
DE-----SDNSIADSLFENES--------------------SDKDNYSVNGV-FKRFRQ-
--IVFGENYSIVI-RNLKHFSKYRISIQACREV-----EESEDKSKIQNCS-KEGVIAGR
TLPMSDADNLDGDQVFWEVSNTTH---GIVKLKWEEPVNPNSMILTYQIEYWRTDIENYK
---PTVECISRNQ----YKALNK---GYILKNLSPGNYSLRIRASSLSGNGMYTKINYFF
IEEDSVSPVLH---TIIIVTIIMLFIFII--IIPFIVLYIRRHIEYGRSIKLIASVN--P
EYVPSG-KVYTPDDWEVPRENV--ELIKEIG-QGSFGMVYEGTLKD-TGIENSRPCAI-K
TVSCNSKTQERDRIEFLNEASVMKAF-NTHHVVKLLGVVSQGQPTLVIMELMAHGDLKAY
LRSCRPDG------------G-YFPQTPPTLKDTLRMAVEIADGMAYLAAKKFVHRDLAA
RNCMVTDDLTVKIGDFGMTRDIYETEYYRKGSLLKSNSTEKQSKARGDIEDFEIAPSSVN
SN--------------------------------------RNNGRM-TPNGC--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------ITY------------------------------
------------------------------------------------------------
--------------------NDVKTTTC--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>G_bue4 GBUE020810-PA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------VRWMAPECLK
DGVFSSLSDVWSYGVVLYEMATLASQPYQGLSNEQVLKFVIDGGVMDRPDNCPDTLYHTM
LMCWQQKTRSRPSFMNLVGMLK------EHS-NPDFAAVSFYDSEEGQEIRGIEVTE---
------------------ETPL-----------FVSRVIEDFSL----SDDES-------
-SNPIKNCSNTGD-------EDEIDDADDYGDISLRNTSDSWIRSEGPPGGV--------
---------------------------EGFGV----PHMV--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>G_bue5 GBUE009720-PA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MTWVVMVLVAWQ------
TACL---------AAITGDGVTNKDGEVAKKTEGV-----------------LTKGDGVC
SSIDIRNGVE-NFKYLNGCRVIEGYLQIVLLEHSTPDLFENKTFPELREVTGYVIFYRVN
GLRSIGQLFPNLSLIRGERL-------FIDYALLITQMPVLREIGLVGLTTVLRGSVALF
NNP---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>F_exs1 XP_029679542.1 insulin receptor-like [Formica exsecta]
MRTRKS-------------------------------LLPIVLLCVTVVGLAIC------
----------------------------QEKRW---------------PKT-----TTKH
R--------------DKSAK--------------------------------GKYDPD--
------------------YADRTREDSEELYYDRS----------------SATDY----
---------GPDALHKLKTKL-AYRNAYRNNRA------------------------IDN
SRST----DVGFKNNQQSSQSSNLPNSHMKSSEEVG-------REKGRRYKNVTIADGIC
QSIDIRNSVG-FFAILRNCRVIEGFLQIVLIENNTEADFENVSFPELREITGYFLLYRVD
GLKSLSKLFPNLEVIRGDIL-------LTDYAFMIYEMKNLQEIGLTSLTKISRGGVRIE
KNPSLCFTNTVNWSFIVPAGE---NFIKENVNAQNCPHMKGCS-----------------
----QCP------GGYCWTA---QHCQLL-------------------ERSTCHEQCLGK
CY--GPSDSECYVCKH-FRHDGRCIESCPPNLYAYLSRRCISKDECQKMNQFRRF-----
---SKTDETWRPFNN-SCVTQCPDGYEDDVD---EKNATTCRICTGQ-CRKIGSGAII--
-RHISDAQSFRGITVVKGA--LEFQIRNGNP-NIMNELADAFGLIEEITEYVKITHSFPI
TSLDFFKKLKVIKGE-ILDIN------------NASFVVLDNPNLSSLFPSSQ-----NI
TIERGRLFFHYNPKLCLSKIEQFGKTV--NITNFTDLEVQPESNGDKVACNIVNINITIM
ERAADYVNLTWDS--------------YKPSEGQ---QLLNYLLNYIETENENVM-YEA-
-NACGNNTWQTVDVGTSRNST------------VSKNITNLKPYTKYAAYVKTFTARNKN
SFISPVGQSEIIFFRTKSAIPSVPTNVSTTVISDSEILFKWAPPVYPNGPIGYYMISGTF
QPDDEKELI-DSRDYCIDTLV----------------SETEKE-EIHEVTIKTPLISNPN
SFCSKDASAKLAI------SKQFEI---FCH--------------KNMTISYLSPGWKD-
----YCVFNTY------------NSPDSRFYDLANNLSSAQEKQKMAMN--VSST-----
--------------------------------------ITGSNIAISHIDNE---VFVY-
--NVTAGNNSYHL-KNLRHYSLYTITIAACGV------KVDDD---TPMCS-SIQYANAR
TKMRPNADDIQN--VKVHVSNDTI-----VEVIWESVKNPNAFTVSYTIEYTNLDVKDAK
---KSTECIRRKAPYTGHKERYN---NHYIKNLSPGRYSLRIRSTSLAGDGTFTKVIYFS
IGLSDHSQIIL-------ATLLTIVVLLV--SMIVVTLLIKSHQKKRTQERLIASANP-P
NYITE--TKYVIDSWEVPRENV--EILEELG-LGNFGMVYRGYLDG------TVQVAI-K
TI--SENASQREKNEFLNEASVMKNF-STWHIIKLLGVVSMGNPPFVIMELMENGDLKTY
LRRIRD------------------TQLVPDASRIIRMAAEIADGMAYLESKKFVHRDLAA
RNCMVSKDLVCKIGDFGMARDIYETDYYKIGK-------------KGLLPIRWMAPENLS
DGVFTSDSDVWSFGVVLYEILTLAEIPYQGFSNEEVLHHVLRKGMLHIPRNCPETVQKIM
EKCFKWRPSERPTFMEIVAELE------PFL-NQDFCEKSFYHADEGIEIRSLGIKK---
-------------VYHN-AAPIR---FHWGH--ETARWVKDF------EDNVT---LLDQ
MKAGTSRGRIFKN-----------------------------------------------
----------------------------GFQ-----------------------------
------------------------------------------------------------
-----------------HFGNVTNFEDV--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------PLDR--------------------------------------------
-------------------------------------------------
>N_lug1 XP_022188928.1 insulin receptor-like [Nilaparvata lugens]
MG----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------WWIEHNKSPELCGR---CPA----------------
----NCK--------HCWNA---KRCQLTQQGDGA-QLSDTGVTVAGQLPEKCHPLCLGG
CY--GPSAHECVACRGVFTPDNMCVRQCPPGTVKWLERRCIYTETCQNHTTADPNIIK--
---NNNDTNFFVFNG-SCVHECPEGFEKGPN--------GCRQCTSSHCRKTCEGQVV--
-DSLSAAQNLTGCTHIVGS--LIISLKTGSDKFIQPELQQSLGSIQEIDGSLKIVRTFPL
VSLNFLRNLRIIHGKKLLFND------------NKSFVVAENHNLQELWDWNQRPS--RL
QILNGSVFFHYNPKLCLSLIKSFIKEI-NFTKTIGLLDISEESNGDKFPCKTVNLNVRVL
KRYNESVELYIEK----------------PKDKE---MFSRYILYYVKSPFQNIS-YEEP
-DDCGDYGWKTKDISSDWKLD--------EPHNITYPITQLEPNTQYAFYVKTYTID---
---SFALKSGVQYFRTLPSKPTFPTKLIATSESSSSITLKWNPPSIANGKLEKYIVHGYK
QKMDMAFYL--NRDFCIYPLQYREVVITTP--TVLPEVNQTT--EFNETAISKYKDESEK
CVCEEKVKVEAIKSKQTHDNDDLQM---FCD--------------NSRSYMYLPNRALDI
DKGFECEKSFFAALYERPFGNEGMRYNYDSIDIQGSSQSNADQKS------INTQDNETH
DRSI-GIVDQ----------------------------LSEADEFVIDDNGQ-IARFFL-
--HIPGNMTETKV-ENLPYFSEYTIEVRACREID--SEEPLESRTLASRCS-FSSITTHR
TQQNKTADFIPF--VKHKIFNKTT-----AMFRWGKPANPNGIIVSYSFEYRSIDRSSSL
---HQTICVSIEE----YNNNGKKGYNYKLENIPRGKYAYRIRALSMASEGEYSESSYFE
IEEEFSFSFKL-------IFAVCFIMMTV--FMIICSLYYWR----KKPVVMFPDVN--P
EYQSIYNCRYVEDEWELCRENV--EIVKELG-KGTFGMVYEGILKP-----NNVPCAI-K
TV--SARQNESEYFDFLLEASIMKSFSESNHIIRLLGVVSRGTPPLVVMELMALGDLKMF
LRSTRD----------------SSLRPPPTGRTVLHMAAQIADGMAYLESKKFVHRDLAA
RNCMVADDLTVKIGDFGMTRDIYETDYYRKGT-------------KGLLPIRWMAPESCY
DGIFSSHSDVWSYGVVLWEISTLAEQPYQGKSNEEVLAYVLAGNSLQAPLFCPEVIKPIM
LSCWNFRPTKRPSFLQIVNTLE------PHT-NDYFKTVSFFHSTEAIELRKNLKMY---
-------------DYHNLNKML-----------LLSTLLNNEDTNE--ANSSS------S
HDSPSSSHSNLNNGS----QHNYCIDDKD-------------------------------
---------------------------DNYVTGTNSPAVI--------------------
------------------------------------------------------------
----------------------TENNDCSKN-----------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------RRVLTNGQAHLTR----
-------------------------------------------------
>C_hook1 augustus-scaffold862-size931216-processed-gene-3.1-mRNA-1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------LGG
CT--GTTASDCISCKD-FSFQGHCVKQCPAFTFEFMNRRCIQEDECSNMLVPRELLDD--
---YKSSKPWKPFNG-SCILDCPPDYMETQL---DNQMYRCTTCKGP-CRKECTGVNV--
-DSIASAQKLRGCTYIKGS--LEIQIRGGK--NIVKELEESLSMIEEIDGYLKIVRSFPL
VSLNFLKNLRIIHGN-FLDTD------------KYSLVVLDNQNLQELWDWNTRSE--NL
TIKHGRLFFHFNPKLCLNKIEKLKNVT--NMPEMSELDVARNSNGDKVACNIQTLEVKIT
NKIKYGVVISWKQ--------------FQHYDPR---SLLNYVVYSIEAPYQNVTLYDGR
-DACGTDGWKVDDVPVTKEER------------VDYALTTLKPFTQYAFYVKTYTIATE-
---RLGAQSPIYYFRTLPDTPSAPQLVQAASNSSSSVVVQWQPPVSPKGNITHYIVSGYW
VFDDARILF--DRNYCYDTIT----------------PHEQKQ-LTIPTDRSTPKPVDAA
CSCEKEETNEKSK----IEESEVQFQIDFED--------------TLHNMVYVKR-----
--------------------------------------KNRSKRE------VAGGFHMMF
-------NDDKGRKSFDEDFSKNKFV-------------------NKVIGGV-YHSFNV-
--EVLGS-NLVVL-GNLSHYALYHIEVQACRD------KVPEDEPNAMICS-EPTFAMVR
TLKLENADNIDPKSLMVEVTNHSR-----VNLKWNEPPQPNGIIVAYQIEYRIVDIENYK
---PTPECIPSTT----FQK-DG---FYMLRRLLPGNYSVQVRANSLAGYGEYTPKNYFY
IKDTTASGFDL----LIGALVGTVLVLLL--IFAGAFFLRRKFIPGVPNMRLIASVN--P
EYVST---VYVPDEWEVPRKKI--DLLRELG-QGSFGMVYEGIGHDVVEGQPEIRCAI-K
TV--NENATDRERSEFLNEASVMKAF-NTNHVVKLLGVVSQGQPVLVVMELMAFGDLKTY
LRSHRPDA------------GETSAQQPPTLKQILQMAIEIADGMAYLTAKKFVHRDLAA
RNCMVAEDLTVKIGDFGMTRDIYETDYYRKGT-------------KGLLPVRWMAPESLK
DGVFTSHSDVWSYGVVLWEMATLASQPYQGLSNDQVLRYVIDGGVMERPENCPDRLYELM
RLCWQQKPPGRPQFMELVELLL------PEV-SARFHEVSYYHTAEAEEARAQHLSA-TI
A------------ASNDPSTPL-----------RITRDIEDFSLGDSDVDEGD-------
-------------------LEDEATEDVSRAELVLSDSRRGRIV----------------
--VGEGDF--------VNSLGGENICSLGF----PSPRAT-FPLA---------------
---------TVATLAAP---------------ARTSRSSPLT------------------
---------------SAHAQFAVRLSRC------LLGPLHYGRNQTLADGAEP-----TL
VPPFHFRHA--------------------------------SRCPR------HSETAAAA
SRPPHNPV--------------APNISPAALFINTPQCAVYS------------------
---------CWLPSRRPTWTTRHVEAAWP-RLDTPRLRRANISRRSRKSDGSSLSLALA-
---------CLPCAWDPLASSLAGYIGRGLSRQLFPILIPGKPAAVTKY
>C_lec1 CLEC010029-PA
MKSFC---------------------------------------CFRVRV----------
----SPVT----------------------------------------PNWENI------
---------------DGNVMHGAEK-------EICR------------MCKLGWY-----
-----------------------IEETKRIFWHRGIKSLACL-------------Y-AFL
YKTKTVKLGIFTCQKMFKKWRKRNAISWNV------------------------------
------------------------------------------------------------
---------------LNGCQIVEGFVHIVLIDKATDADYANITFPELKEITDYLLLYRVH
GLRSLGSIFPNLAVIRGNHL-------FKDYALVVFEMLHLQEIGLSSLTHILRGSVNLS
KNPVLCFVDTIDWDLIAHNG-KGVHHIAGNKLQNECPM---CPPI---------------
-NH-TCPTSATTGEPLCWNS---HHCQRV-CPKHC-NGSCNA------AGDCCNASCIGG
CT--GSGSDNCISCRH-VLFENKCVSKCPANTYKYMNRRCIVESVCYDMPKPVEIVDS--
---NIGHNPWKPFQG-ECIMECKSGYIEKEVILKGQKRNQCEPCEGV-CKKECPGANV--
-DSIAAAQKLRGCTYIKGA--LEIQIRGGS--NVVKELDENLSMIEEIEYYLKIVRSFPL
VSLNFLKNLREIHGK-KLESS------------KYGLVVLDNQNLIELWDWKSREP--SF
HIRRGKLFFHFNPKLCISKIDKLREVA--QLPEYTDLEVAINSNGDKVACNVTELIAEVK
TRSPQGALIRWKQ--------------FEHYDTR---TLLGYVVYSIEAPYRNITLYDGR
-DGCGGDGWRVDDIAPMAEDEKRKLEKEGQELWLKFVLTRLKAYTQYAFYVKTYTIATE-
---RSGAQSPILYFRTAPYIPSEPRSLTAYSNSSFEIVINWLPPSKPNGNVTYYIVTGQW
EKGEEEHLE--QRNFCLE------------------------------QTTDKPDSSNKN
CACANKVPDNKIR------EKEIH----FED--------------HLQNTIYIKRTD---
--------------------------------------SVRNKRD------VSDRTTGKF
IL-----MENVMGEGF-------------------------------------QESFTR-
---IVRGGTSLVV-KNLRHFAHYNIAVNACREL-----EEDENKNNTGTCS-SSAFVTAK
TLPLANADNIDDQFLQWEISNKSL---GFVLLRWNEPPRPNGFIVAYQIEYRRTDIENFK
---PNIECITRKQ----FRDANN---SYMLKNLGPGNYSLRVRATSYGGEGNFTPVKYFY
IEEESQISVVY-------ISLMFSTALII--TALVCVIYFRRQYTQVPNRKLIASVN--P
EYVPT---VYEPDDWEVPRTRV--DLIKEIG-QGSFGMVWEGILKN-VDGTQELPCA---
-------------------------------------------PTLVIMELMCRGDLKSY
LRSHRPDLPD--------------NPKQPCLKRILRMAAEIADGMAYLSAKKFVHRDLAA
RNCMVAEDLTVKIGDFGMTRDIYETEYYRKGS-------------KGLLPVRWMAPESLK
DGVFTSHSDAWSYGVVLYEMATLASQPYQGLSNDQVLRYVIEGGIMERPERCPDKLFQVM
KLCWRHKPSSRPSFLELVTLLQ------DDV-DPDFQNVSFYHSEEGVDLRAAVSTE---
------------------DTPL-----------SISREIEDFSL----SDEEDYKEPHSS
TSM---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>C_lec2 CLEC025326-PA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------MLLAFWRIWWLL-
TIAL-----------------------------------------------SSTVMGRTC
PSMDIRNNVT-NFNLLRGCSVIDGFLHIVLIDKSSQQDFENVTFPDLREVTEYVLFYQVN
GLTSLGEVFPNLAVIRGEKL-------FLDYSFIVFQMPDLKTLKFKSFI-ILRGSVVIA
NNKNLCYDNTIDWDKVAVSG-VR-EYLFPNDTEKNCS----CP-----------------
----SCS------DGLCWSE---KNCQLD------------------LAESSCHQECVGG
CT--GSGPSNCVSCRH-LYFRGKCVPECPDGYYSFNSRHCISKEDCINSSSTYHKMRRN-
---DGAHLVWFIWGN-SCVTECPPKFEKTPD------GKSCQRCSGM-CKKVCSMGNV--
-DSLQAAQNLRDCTHIDGN--LEIHIGTGKPEVVAKELEENLGMIEEIEGNLRIIHSFPL
DSLGFFKNLKVIHGY-KDKKGTNNL-------VNHSLFVLDNQNLKEIWNWDTRPAGRNF
KILNGYPFFHYNPMLCYKHIEELTSIA--GIQDIKTIEITRESNGGRFACNKLSLNVTVH
LVYENAIALAIEQ--------------PEFTNMAKYYQMMRFVAYYMEAPHQNVTELNT-
-NECSESKWKMHDISGLNEPFD----GGPPNGSIYHIITRLEPYTQYAFYVKTYTVD---
---STGIQSPI----------------------------HWSPPEKPNGKLVSYVVSGFI
QEYHPDFLS--TRNFCKKPYVHIPP-------------------TTPPPKFMTHVKTKDE
CVCN---------------VSTIPIEDEFEP--------------PLVTTELCETAD---
-----------------------------------ELAKSPPLYE------YDGCHKYVY
ET-----LEQPPFLKIYENDNIGRYERGISMIEEDDDLVLNEDVEMLGRDGS-LVKFHR-
--IFPAEANVALI-GGLRHFSTYTIEVKACRE------RVEGELQRSANCS-ISAFITLK
TLSDSKADEIVG-GLRVQVENRTA------ILNW-VPPKSNGMTVSYQIELTRTDRDEMK
---PMPECIPVQD----AK--NG---AFMLEDLEFGEYKIRLRSQSLAGPGKFTAPVYFT
ISGQFAKDMMA-------VAVLTVVILLVILVSVTLAVWYYRKNLMINQPVLIASVN--P
EYCGL---LHFDEEWELPRERV--HIVKELK-RGNFGVVCEGLLVP-----EGRVVAVKK
AI--NENCSPHEIAAFLNEAMVMKQFVDGPHIVKLIGVVSRDVPALVVMEMMANGDLKTY
LRECR-------------------NKNVPSSQRMLLMAAQIADGMAYLEAAKFVHRDLAA
RNCMVSDNGVVKIGDFGMTRDIYETDYYRKGN-------------KGLLPIRWMAPESLN
DGVFTSKSDAWSYGIVLWEMATLASQPYQGLSNEQVLQFVISGNKLELPPVYPKPFKSLT
AWCWRWKPKFRPSFIEILRELE------EYM-TVSFRQVSFFNSEAGLQASRDV------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>C_lec3 XP_014242610.1 insulin receptor-like isoform X1 [Cimex lectularius]
MNGMR-------------------------------------------------------
-----PRNS------------------MEGGAWWGVGGGHG------GPSL---------
----------------------------------------------LAVHQCTLL-P---
-----ESLLHLAQVRDRVAALRRRAQHARV------------------------------
-------------NSLLRDSAPTKQNSWRTGPSPISTCERTDLTFCVMLLAFWRIWWLL-
TIAL-----------------------------------------------SSTVMGRTC
PSMDIRNNVT-NFNLLRGCSVIDGFLHIVLIDKSSQQDFENVTFPDLREVTEYVLFYQVN
GLTSLGEVFPNLAVIRGEKL-------FLDYSFIVFQMPDLKTLKFKSFI-ILRGSVVIA
NNKNLCYDNTIDWDKVAVSG-VR-EYLFPNDTEKNCS----CP-----------------
----SCS------DGLCWSE---KNCQLD------------------LAESSCHQECVGG
CT--GSGPSNCVSCRH-LYFRGKCVPECPDGYYSFNSRHCISKEDCINSSSTYHKMRRN-
---DGAHLVWFIWGN-SCVTECPPKFEKTPD------GKSCQRCSGM-CKKVCSMGNV--
-DSLQAAQNLRDCTHIDGN--LEIHIGTGKPEVVAKELEENLGMIEEIEGNLRIIHSFPL
DSLGFFKNLKVIHGY-KDKKGTNNL-------VNHSLFVLDNQNLKEIWNWDTRPAGRNF
KILNGYPFFHYNPMLCYKHIEELTSIA--GIQDIKTIEITRESNGGRFACNKLSLNVTVH
LVYENAIALAIEQ--------------PEFTNMAKYYQMMRFVAYYMEAPHQNVTELNT-
-NECSESKWKMHDISGLNEPFD----GGPPNGSIYHIITRLEPYTQYAFYVKTYTVD---
---STGIQSPIQYVRTLPSQPKMPAKLEGISNSSSEILLHWSPPEKPNGKLVSYVVSGFI
QEYHPDFLS--TRNFCKKPYVHIPP-------------------TTPPPKFMTHVKTKDE
CVCN---------------VSTIPIEDEFEP--------------PLVTTELCETAD---
-----------------------------------ELAKSPPLYE------YDGCHKYVY
ET-----LEQPPFLKIYENDNIGRYERGISMIEEDDDLVLNEDVEMLGRDGS-LVKFHR-
--IFPAEANVALI-GGLRHFSTYTIEVKACRE------RVEGELQRSANCS-ISAFITLK
TLSDSKADEIVG-GLRVQVENRTA------ILNW-VPPKSNGMTVSYQIELTRTDRDEMK
---PMPECIPVQD----AK--NG---AFMLEDLEFGEYKIRLRSQSLAGPGKFTAPVYFT
ISGQFAKDMMA-------VAVLTVVILLVILVSVTLAVWYYRKNLMINQPVLIASVN--P
EYCGL---LHFDEEWELPRERV--HIVKELK-RGNFGVVCEGLLVP-----EGRVVAVKK
AI--NENCSPHEIAAFLNEAMVMKQFVDGPHIVKLIGVVSRDVPALVVMEMMANGDLKTY
LRECR-------------------NKNVPSSQRMLLMAAQIADGMAYLEAAKFVHRDLAA
RNCMVSDNGVVKIGDFGMTRDIYETDYYRKGN-------------KGLLPIRWMAPESLN
DGVFTSKSDAWSYGIVLWEMATLASQPYQGLSNEQVLQFVISGNKLELPPVYPKPFKSLT
AWCWRWKPKFRPSFIEILRELE------EYM-TVSFRQVSFFNSEAGLQASRGAHSSETV
------------------PEELNCD--------TVASCPSPTNLMD--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>C_lec5 XP_014256336.1 insulin-like receptor [Cimex lectularius]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------FKKWRKRNAISWNVVFS------------------------LMC
VLSLIF----------------HTATTHRYITDDHG--------------KTVLNEPGVC
SSKDIRNSVE-SFSQLNGCQIVEGFVHIVLIDKATDADYANITFPELKEITDYLLLYRVH
GLRSLGSIFPNLAVIRGNHL-------FKDYALVVFEMLHLQEIGLSSLTHILRGSVNLS
KNPVLCFVDTIDWDLIAHNG-KGVHHIAGNKLQNECPM---CPPI---------------
-NH-TCPTSATTGEPLCWNS---HHCQRV-CPKHC-NGSCNA------AGDCCNASCIGG
CT--GSGSDNCISCRH-VLFENKCVSKCPANTYKYMNRRCIVESVCYDMPKPVEIVDS--
---NIGHNPWKPFQG-ECIMECKSGYIEKEVILKGQKRNQCEPCEGV-CKKECPGANV--
-DSIAAAQKLRGCTYIKGA--LEIQIRGGS--NVVKELDENLSMIEEIEYYLKIVRSFPL
VSLNFLKNLREIHGK-KLESS------------KYGLVVLDNQNLIELWDWKSREP--SF
HIRRGKLFFHFNPKLCISKIDKLREVA--QLPEYTDLEVAINSNGDKVACNVTELIAEVK
TRSPQGALIRWKQ--------------FEHYDTR---TLLGYVVYSIEAPYRNITLYDGR
-DGCGGDGWRVDDIAPMAEDEKRKLEKEGQELWLKFVLTRLKAYTQYAFYVKTYTIATE-
---RSGAQSPILYFRTAPYIPSEPRSLTAYSNSSFEIVINWLPPSKPNGNVTYYIVTGQW
EKGEEEHLE--QRNFCLEPYDNKRT-----------SHSIAKP-EQHPETTDKPDSSNKN
CACANKVPDNKIR------EKEIH----FED--------------HLQNTIYIKRTD---
--------------------------------------SVRNKRD------VSDRTTGKF
IL-----MENVMGEGF-------------------------------------QESFTR-
---IVRGGTSLVV-KNLRHFAHYNIAVNACREL-----EEDENKNNTGTCS-SSAFVTAK
TLPLANADNIDDQFLQWEISNKSL---GFVLLRWNEPPRPNGFIVAYQIEYRRTDIENFK
---PNIECITRKQ----FRDANN---SYMLKNLGPGNYSLRVRATSYGGEGNFTPVKYFY
IEEESQISVVY-------ISLMFSTALII--TALVCVIYFRRQYTQVPNRKLIASVN--P
EYVPT---VYEPDDWEVPRTRV--DLIKEIG-QGSFGMVWEGILKN-VDGTQELPCAV-K
TV--NDQAADRDRIEFLNEASVMKAF-NTHHVVKLLGVVSQGQPTLVIMELMCRGDLKSY
LRSHRPDLPD--------------NPKQPCLKRILRMAAEIADGMAYLSAKKFVHRDLAA
RNCMVAEDLTVKIGDFGMTRDIYETEYYRKGS-------------KGLLPVRWMAPESLK
DGVFTSHSDAWSYGVVLYEMATLASQPYQGLSNDQVLRYVIEGGIMERPERCPDKLFQVM
KLCWRHKPSSRPSFLELVTLLQ------DDV-DPDFQNVSFYHSEEGVDLRAAVSTE---
------------------DTPL-----------SISREIEDFSL----SDEEDYKEPHSS
TSSKMSNGSTTPN-----------------------------------------------
----------------------------GYV-----PQHV--------------------
------------------------------------------------------------
----------------------VKTTKC--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>M_ext1 Medex_00067447-RA
MLHM--------------------------------------------------------
------------------------------------------------PEM---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------HFDEL------------------------------LERVHQHIIKTDTN
MRQAVTT---ELKLERTEKENDKSAHNSAQYASTA-----------SSCNAVMTIELRRD
ANNKKCLPYIVK-DYMTSERQ---KWRTRRENATACAAVQRCS-----------------
----HCA------DGHCWGEDGVDACQKT-------------------PTEGCHAECLGG
CS--GPGPTDCLACRH-VELDGVCVPACPYDRYEYMGRRCMTAEECRSIPKSDIIQQKEC
EMESSKDKSWIPYAG-KCSQTCPPDHQQDGD--------VCLPCRGH-CQTICGDGTVVR
LTSLACMQAIRHCNYLNGS--LVIELRSSDA-GVIKELEESLTSIEEIEGYLEVAQSTSL
VSLKFLRGLRIIHGR-QLESD------------KSALVVRSNPKLERLFPWDQMN---KL
EILAGRLKFHDNPMLCITEVNALQRFA--GLSNYTAEEVSAESNGNENICKTINLGTEYT
VINSTCVEVSWKN----------------IVQSE---TLLGYTVHYVEANDYNVTLDDAN
DDSCGEKGWKVDYVITHNEKL--------VPEKVYHSISNLKPYTLYAFFVQTYTIAPE-
---AEKGLSQMFYFRTHPARPSVPRSPTVLNSSSSHITLSWEPPLFHNGNLTHYIILGKL
YLDNETSVT--HRDFCNFPMDALT--------------------HTATLNTSSSSNISET
SCCEKKMCAAG-------DTSQFNNI--FQSRTAELDDELCGQPSSLYNVLYSNR-----
-----------------LFGEQGGFIN-----------SLEPNKT------IEEYFSSGN
LLNS-KIPDNTVG---------------------------------LNIGGV-QLNFMK-
--KVNASSSSTII-ENLAHYGEYSIKIVACREPYI---NETDDDWFQSRCS-PTSLIHAR
TDIDENADDINSTSVSVNLTD------DKVFLSWDSPPKPNGLVVKYDVSYRLVN-EARI
---PTPMCVSMAE----FIQYGG---LIELPNLTPGKYQVSVRATSLAGNGKFTQATYFR
VVSIATHPDMT-----VIISCITFVVIIV--TLLGAYIWLEK------------------
-------VAWIQSNTTVTRGAS----------NDPFCLPF--------------------
------------------------AF-ASMYIHLYLWSIK------IVLCLALVGDLRQY
SSRHPSHI--------------------PVYTDPLLLF----------------------
-----------------------------------------------LFPV---------
----------------------------------TVLQLVLAGGCLEPAVDCPVSLRHLM
TYCWRRSADHRPTFLQVLDFLESSPSSGPSI-DDDFRQVSFYHSEAGVQLRSKYDFR---
------------------------------------------------AHEEELVHLLGD
TNSTASSGEYFTP-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>M_ext2 Medex_00078894-RA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------KTF----------------
---SLGINF---------------------------------------------------
------------------------------------------------------------
----VCD-----------------------------------------------------
-------------------------------RYDFLGRRCVTETECREMVDPHPMAPGAD
LVESYKDKVWWPFNG-SCVQSCPTGFKEFKS--PDHDSWSCRQCSGGSCLRKCNGTTV--
-ESISTAQLFKGCTYINNG--LEIQIKGGR--DVVDELEKNLNSIEEIEGYLKVSRSFPL
LNLNFLKNLRVIHGK-LLDQG------------KFALVVIENSNLEDLWNWTSRSD--GL
QIKNGSLFFHFNPKLCLSKIDKLREIS--GAPNFTNSEVARESNGDKMACEVTKIKAYVQ
TKASRGAVIEWEP--------------VTDLPKE---SLLGYIVYYIEAPHANVTYYNGR
-EACINFGWRATDVTVDDEKP-------------SKLLAQLKPFTQYAFYVKTYTITNR-
-----GGRSEIQYFTTLPDRPSLPTKFVSFSNSSSEIVLSWKAPVHPNGVLSHYVVTGVW
RQDDQKRLD--YRDYCTYPLKPRSD-----------------DVLLVPPDESSENQTKNC
CAYT---------PNNFEITDKVV----FEHM------------CKSKYLQYSKYSEKSQ
V-----------------DSEVDACYNYLHMYLHEELLINKTKQELQM---IRVGENGWQ
RHP--HLPDIYSERPVFPNLAENYFE---------------------MENGA-YKNFTY-
--KVDAKDSTFVL-RRLHPFALYTISLFACRKPLYFVDENGKNGSDYNFCS-YASIVNTR
TLADPTLDEINFKQMAVDSFNHSS---SDVYVSWKEPKKPNGAIVTYHVEYRMIDIENFK
---PIIECVTRKQ----HERSGG---GSVIRNLSPGNYSFRVRATSLAGEGKFTDVLYYW
VGEKPWTSSVT-------KTLIVVFVCLI--VFVLAALALVESGDAVAQWKPDTAIEAEP
LLLPT---VQSYSQREAPQKNIYSDTKTECGDKADLKMVPNGTAND--------------
------------------------YF----------------------------------
------------------------------------------------------------
--CY-----------FNLT-----------------------------------------
------------------------------------------------------------
----------------------------------NFHEVR--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>D_mel1 FBpp0083519 FBgn0283499 InR [Drosophila melanogaster]
MFNMPRGVTKSKSKRGKIKMENDMAAA---ATTTACTLGHICVLCRQEMLLDTCCCRQAV
EAVDSPASSEEAYSSSNSSSCQASSEISAEEVWF---LSHDDIVLCRRPKFDEVETTGKK
RDVKCSGHQCSNECDDGSTKNNRQQRENFNIFSNCHNILRTLQSLLLLMFNCGIFNKRRR
RQHQQQHHHHYQHHHQQHHQQHHQRQQANVSYTKFLLLLQTLAAATTRLSLSPKNYKQQQ
QLQHNQQLPRATPQQKQQEKDRHKCFHYKHNYS---------YSPGISLLLFIL---LAN
TLAI---QAVVLPAHQQHLLHNDIADGLDKTALSVSGTQSRWTRSESNPTMRLSQNVKPC
KSMDIRNMVS-HFNQLENCTVIEGFLLIDLINDASP---LNRSFPKLTEVTDYIIIYRVT
GLHSLSKIFPNLSVIRGNKL-------FDGYALVVYSNFDLMDLGLHKLRSITRGGVRIE
KNHKLCYDRTIDWLEILAENETQLVVLTENGKEKECRLSK-CPGEIRIEEGHDTTAIEGE
LNA-SCQL--HNNRRLCWNS---KLCQTK-CPEKC-RNNCID------EHTCCSQDCLGG
CVIDKNGNESCISCRN-VSFNNICMDSCPKGYYQF-DSRCVTANECITLTKFE-------
---TNSVYSGIPYNG-QCITHCPTGYQKSEN------KRMCEPCPGGKCDKECSSGLI--
-DSLERAREFHGCTIITGTEPLTISIKRESGAHVMDELKYGLAAVHKIQSSLMVHLTYGL
KSLKFFQSLTEISGDPPMDAD------------KYALYVLDNRDLDELWGPNQ-----TV
FIRKGGVFFHFNPKLCVSTINQLLPMLASKPKFFEKSDVGADSNGNRGSCGTAVLNVTLQ
SVGANSAMLNVTTKVEIGEPQKPSNATIVFKDPR---AFIGFVFYHMIDPYGNST-KSSD
-DPC-DDRWKVSS----------------PEKSGVMVLSNLIPYTNYSYYVRTMAISSE-
---LTNAESDVKNFRTNPGRPSKVTEVVATAISDSKINVTWSYLDKPYGVLTRYFIKAKL
INRPTRN---NNRDYCTEPLV----------------KAMENDLPATTPTKKISDPLAGD
CKCVEGSKKTSSQ---EYDDRKVQAGMEFEN--------------ALQNFIFVPNIRKSK
N--GSSDKS---------DGAEGAALDSNAIPNGGATNPSRRRRDVALEPELDDVEGSVL
LRHVRSITDDT--DAFFEKDDENTY----------------KDEEDLSSNKQFYEVFAK-
--ELPPNQTHFVF-EKLRHFTRYAIFVVACREEIP-SEKLRDTSFKKSLCS-DYDTVFQT
TKRKKFADIVMDLKVDLEHANNTE---SPVRVRWTPPVDPNGEIVTYEVAYKLQKPDQV-
---EEKKCIPAAD----FNQT-----AGYLIKLNEGLYSFRVRANSIAGYGDFTEVEHIK
VEPPPSYAKVF-------FWLLGIGLAFLIVSLFGYVCYLHKRKVPSNDLHMNTEVN--P
FYASM---QYIPDDWEVLRENI--IQLAPLG-QGSFGMVYEGILKSFPPNGVDRECAI-K
TV--NENATDRERTNFLSEASVMKEF-DTYHVVRLLGVCSRGQPALVVMELMKKGDLKSY
LRAHRPEERDEAMMTYLNRIGVTGNVQPPTYGRIYQMAIEIADGMAYLAAKKFVHRDLAA
RNCMVADDLTVKIGDFGMTRDIYETDYYRKGT-------------KGLLPVRWMPPESLR
DGVYSSASDVFSFGVVLWEMATLAAQPYQGLSNEQVLRYVIDGGVMERPENCPDFLHKLM
QRCWHHRSSARPSFLDIIAYLE------PQCPNSQFKEVSFYHSEAGLQHREKERKE---
------------------RNQLD----------AFAAVPLDQDL----QDREQ----QED
ATTPLRMGDYQQNSSLDQPPESPIAMVDDQGSHLPFSLPSGFIASSTPDGQTVMATAFQN
IPAAQGDISATYVVPDADALDG----DRGYEIYDPSPKCAELPTSRSGSTGGGKLSGEQH
LLPRKGRQPTIMSSSMPDDVIGGSSLQPSTASAGSSNASSHTGRPSLKKTVADSVRNKAN
FINRHLFNHKRTGSNASHKSNASNAPSTSSNTNLTSHPVAMGNLGTIESGGSGSAGSYTG
TPRFYTPSATPGGGSGMAISDNPNYRLLDESIASEQATILTTSSPNPNYEMMHPPTSLVS
TNPNYMPMNETPVQMAGVTISHNPNYQPMQAPLNARQSQSSSDEDNEQEEDDEDEDDDVD
DEHVEHIKMERMPLSRPR------QRALPSKTQPPRSRSVSQTRKSPTNPNSGIGATGAG
NRSNLLKENWLRPASTPRPPPPNGFIGR-------------------EA
>D_sim1 FBpp0218373 FBgn0191454 InR [Drosophila simulans]
MFNMPRGVTKSKSKRGKIKMENDMAAATTTTTTTACTLGHICVLCRQEMLLDTCCCRQAV
EAVDSPASSDEAYSSS-TSNCQASSEISAEKVWF---LSHDDIVLCRRPKFDEVETTGKK
RDVKCRGHQCSNECDDGSTKNNRHQREKFNIFSNCHNILRTLQSLLLLMFNCGIFNKRRR
RQHQQQQHHHHQHHPQHHHQQHHQRQQAHVSYTKFLLLLQTLAAATTRLSLSPKNY-NQQ
QLQHNQQLPRATPQQKQQEKDRHKCFHYKHNYY---------YTPGISLLLFIL---LAN
TLAI---QAVVLPAHQQHLLHNDIADGLDKTALSVSGTQSRWPRSESNPTMRLSQNVKPC
KSMDIRNMVS-HFNQLENCTVIEGFLLIDLINDASP---LNRSFPKLTEVTDYIIIYRVT
GLHSLSKIFPNLSVIRGNKL-------FDGYALVVYSNFDLMDLGLHKLRSITRGGVRIE
KNHKLCYDRTIDWLEILAENETQLVVLTENGKEKECRLSK-CPGEIRIEEGHDSTAIEGE
LNA-SCQL--HNNRRLCWNS---KLCQTK-CPEKC-RNNCID------EHTCCSQDCLGG
CVIDKHGNESCISCRN-VSFNNICMDSCPKGYFQF-DSRCVTANECTTLTKFE-------
---TNSVYSGIPYNG-QCITHCPTGYQKSEN------KRMCEPCPGGKCDKECSSGLI--
-DSLERAREFHGCTIITGTEPLTISIKRESGAHVMDELKYGLAAVHKIQSSLMVHLTYGL
KSLKFFQSLTEISGDPPMDAD------------KYALYVLDNRDLDELWGPNQ-----TV
FIRKGGVFFHFNPKLCVSTINQLLPMLASKPKFFEKSDVGADSNGNRGSCGTAVLNVTLQ
SVGANSALLNVTTKVEIGEPQKPSNATIIFKDPR---AFIGFVFYHMIDPYGNST-KSSD
-DPC-DDRWKVSS----------------PEKSGVMVLSNLIPYTNYSYYVRTMAISSE-
---LTNAESDVKNFRTNPGRPSKVTEVVATAISDSKINVTWSYLDKPYGVLTRYFIKAKL
INRPTRN---NNRDYCTEPLI----------------KAMENDLPATTPTKKIPDPLAGD
CKCVEGSKKTSSQ---EYDDRKVQAGMEFEN--------------ALQNFIFVPNIRKSK
N--GSSDKS---------DGAEGAALDSNAIPNGGAGNPSRRRRDVALEPELDDVEGSVL
LRHVRSITDDT--DAFFEKDDENTY----------------KDEEDLSSNKQFYEVFAK-
--ELPPNQTHFVF-EKLRHFTRYAIFVVACREEIP-SEKLRDTSFKKSLCS-DYDTVFQT
TKRKKFADIVMDLKVDLEHANNTE---SPVRVRWTPPVDPNGEIVTYEVAYKLQKPDQV-
---EEKKCIPAAD----FNQT-----AGYLIKLNEGLYSFRVRANSIAGYGDFTEVEHIK
VEPPPSYAKVF-------FWLLGIGLSLLIVSLFGYVCYLHKRKVPSNDLHMNTEVN--P
FYASM---QYIPDDWEVLRENI--IQLAPLG-QGSFGMVYEGILKSFPPNGLDRECAI-K
TV--NENATDRERTNFLSEASVMKEF-DTYHVVRLLGVCSRGQPALVVMELMKKGDLKSY
LRAHRPEERDEAMITYLNRIGVTGNVQPPTYGRIYQMAIEIADGMAYLAAKKFVHRDLAA
RNCMVADDLTVKIGDFGMTRDIYETDYYRKGT-------------KGLLPVRWMPPESLR
DGVYSSASDVFSFGVVLWEMATLAAQPYQGLSNEQVLRYVIDGGVMERPENCPDFLHKLM
QRCWHHRSSARPSFLDIIAYLE------PQCPNSQFKEVSFYHSEAGLQHREKERKE---
------------------RNQLD----------AFAAVPLDQDL----QEREQ----QED
ATTPLRMGDYQQNSSLDQPPESPIAMVDDQGSHLPFSLPSGFIASSTPDGQTLMPTAFHN
IPAGQGDISSAYVVPDTDALDG----DRGYEIYDPSPKCAELPTSRSGSTGGGKLSGEQH
LLPRKGRQPTIMSSSMPDDVIGGSSLQPSTASAASSNGSSHTGRPSLKKTVADSVRNKAN
FINRHLFNHKRTGSNASHKSNASNAPSTSSNTNLTSHPVAMGNLGTIESGGSGSAGSYTG
TPRFYTPSATPGGGSGMAISDNPNYRLLDESIASEQATILTTSSPNPNYEMMHPPTSLVS
TNPNYMPMNETPVQMAGVTISHNPNYQPMQAPLNARQSQSSSDEDNEQDEDDEDEDDDVD
DEHVEHIKMERMPLSRPR------QRALPSKTQPPRSRSVSQTRKSPTNPNSGVGATGAG
NRSNLLKENWLRPASTPRPPPPNGFIGR-------------------EA
