>A_pis1 XP_029347438.1 ecdysone-induced protein 74EF isoform X1 [Acyrthosiphon pisum]
----------------------MPFMDDVLLWCPEA------------ETKID---DFTE
CLGNEVSSLGELLQSEISSELDNAL-DGGGSS----------------------------
VQDGGEHSGDDDIFKQLSDSSALLEQFF-DFVNCDIK---EENNNNVM------------
------------------------------------------------------------
----------------STGNKNHAA--------------------VALLQELQRTN-AGK
KFNITTANPLLA-----EKLLNPVSQLNPSLNQNSDMFI-------NQNKYIKTEPSIN-
-DIGKQTVRPTSPPPTTTTVGNE--KDENIDFLDHLRI-------------AGNGGVGN-
----------------------PGAAD----HLPPRQQ-----------------LSF--
------------------------ALPHGFHHAG-------SLP---------PSPADSG
VSDVDSSSSG-HTSTDTE--LRARLQP------------------------------HQY
HHQVSSCGRR----------------------TS------PDPPS---------------
-------------NVQCHQQQQQQQQQQQQQQQQQ---------------------QQQQ
QQQQQQDLFSRIYGVNAPPPGAYHHPSPASPSP--------KHPLFMRNNHP--------
--------------------------YGGGVAGYHPSTVGGYGPAVSPTSD--------G
HFAMPPCPPVAALPGAGTVIGRGSVIQAAAANCYQPNGAGAANLNDLYYMDF-GA---PT
AAAAMYHQKTVGNKSGNNKKPK-KYGTVGRPSVAGSPGAVQQQTCPATGPKRKSREGSTT
YLWEFLLKLLQNSDYCPRFIKWLNREKGVFKLVDSKAVSKLWGEHKNKPDMNYETMGRAL
RYYYQRGILAKVDGQRLVYQF--------VDVPKDIVEIDCSGA
>G_bue1 GBUE008361-PA
----------------------M-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GGGGYYTAGSG----
--------SPPR----------ASVIQAAASSSH----------DDLYLLEL-GF-----
----------------NNRIKK-K----LKRPKTGDAT-----QCQGQGPKRKSREGSTT
YLWEFLLKLLQDREYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKNKPDMNYETMGRAL
RYYYQRGILAKVDGQRLVYQF--------VDVPKDIVEIDCTSA
>F_exs1 XP_029678074.1 ecdysone-induced protein 74EF isoform X1 [Formica exsecta]
MPVPVSQTPTLTSTLVPKEESNMPFIDDELFWYSDN------------DGKM----DLTQ
CLQQSNTGQ----SVEFSPMELSAL-VGTPAAP------------------------NVP
AEEGAGMSTGEELFDPL------------DFLR-----ELEAEASQPTS-----------
------------------------------------------------------------
----------------TTTPSSY----------------------------------RRQ
RHNIAAANPLLA-----EKLAAPSTQ-------TSPTSIPYASRAEIKTENIKPEPSI--
-VDTREVQ-------------------PHDTGEKEQLGLASVKVEPGSTSATTTSSTGT-
-----------------R--LLHGILS----QHPQQHS-----------------LGLQN
GYGRHLTGHAQMGQPPY------TTAATSTPGSG-------SLP---------ASPADSG
VSDVESSTSS-GGNEDANLLLKARLNPNS--SLQPG------------------LASHHS
HLSSAALGRS---------------------------------------ACHSPGVYPST
ATFLP-------------------------------------------------------
-----------------------PSYHPHQHHPSQYHPHRGSSPHHQHSNHTMGSTMGPP
HHHHHHHQTQSLQHLHYRQPPSLSESYNNYVNSMYGGGG---------------------
QFATPCTPSPPRGPG-G---VPTSVIQAATSSVS----------DDLYLLEL-GF-----
----------------PPRSKKSK----LKKPRQGEGG--------GAAVKRKSREGSTT
YLWEFLLKLLQDREYCPRYIKWTNRERGVFKLVDSKAVSRLWGLHKNKPDMNYETMGRAL
RYYYQRGILAKVDGQRLVYQF--------VEVPKDIVEIDCTGA
>N_lug1 XP_022185398.1 ecdysone-induced protein 74EF [Nilaparvata lugens]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------MNPLDG-----HCHLPEDAM-------EAPLDLSVAA-TSVKLEYLTDDSDD--
-SDSHGG--------------------PNCKAYKKSL------IKRYLDTTAPAPL----
YIKREPGE-----HKGLQ--GLPGILS----HHPHAAL-----------------L----
--------------------------NYNASNTG-------SLP---------PSPADSG
VSDVDSSSSG-HTSNDE---LRSRLNPQP-------------------------------
PHQVTSCRRS------------------------------PDSAG-GLYTPHFLAPYPTY
TAASA-------------------------------------------------------
-----------------------PAPAPMRPHP---------PPHPHYTNHTHG------
-------------------RTNLSDGYASYMAALGGAPQTGVAGGA--------------
YFP---APSPPRLPGSG---VPTPVIQAAASSSSTSPA-----ADDFYLLEM-GF-----
----------------QRKLKK-Q----KRIRVAGDAM-------PGQGAKRKSREGSTT
YLWEFLLKLLQNREYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKNKPDMNYETMGRAL
RYYYQRGILAKVDGQRLVYQF--------VDVPKDIVEIDCSGA
>N_lug2 XP_022207261.1 ecdysone-induced protein 74EF-like [Nilaparvata lugens]
M--------------------EVPSTT----WFSEALCTSLYKDSHSPSSGLD---DESA
YISTNYTDLSDACRNQITHDDSKKFNNNSGES----------------------------
MSDTNRNSDSDNGDKNQGD---------------------SENNN---------------
------------------------------------------------------------
---------------------------------------------YLMLQAKHRLN-H--
------SHPTIH---------------------------------STQEEYIDLDKLY--
-QSHHRTLLNSSYSPASSS-----------------------------------------
HYQHN--------HQHLQ----------HTINHPHHHNILAQQLSCLHRQQHPTDLGIRG
QGH---------------------GHPHQGHPQG-------RIPLQGHPQGRIPPPGHPG
SSSQGHRSS---------------------------------------------------
------------------------------------------------------------
----------------------------------QLHHLHPPASVS-----------SST
SPTSLS----------------IPSPHL--------------NSDHNHRRNHLGHH----
------------QHL---PQQLPHAHAQQTTSALSINSSHHSYNNYPP---SVFNG----
--GTGTHPVGSQS---Q---GRDGYGQSSAGNEPN-------DYSSYAQQQYPNYNEDPD
SDSE----------SDHQRDIEAQ----PVKKRPGRPR----------GSRRKKPEK-LG
RLWEFIRDLLLNSETCPSLICWDNYEEGMFRFVHSDKVAKLWGAKRDNPDMNYEKLSRAM
RYYYKSKVLQPVFGRRLVYKFGPEAKGWKTDNPN-------FRC
>C_hook2 maker-scaffold212-size1131905-augustus-gene-1.5-mRNA-1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----AVTTGMLV------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VG--------------------------
------------------------------------------------------------
---AVLAART------------------------------PESPGPGHPQQHSGYGVPPH
GGFLT-------------------------------------------------------
-----------------------PFYHPHQPAR--------VPPHHYVGRQP--------
----------------------LGDGYGGY---LQPSHQANLYHQHQ------------Q
HFAAPPAPSPSRP---A---IPTSVIQAATSSVG---------PDDLYMLEL-GF-----
----------------QPRPVKKK----LKKSKSGEPG----------AVKRKSRE----
-----------DRDYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKNKPDMNYETMGRAL
RYYYQRGILAKVDGQRLVYQF--------VDVPKDIVEIDCTGA
>C_lec1 CLEC009111-PA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------LGSHLE-DP--------------------------RTTPT
HSENILSPNI------------------------------YKAESDSL-------ETKPL
AQDYP-------------------------------------------------------
-----------------------PHYFQ--------------------------------
---------------------FLTDGYGGAGGGGGGGGGGGGGGGGGGGAATGYMGPPQN
YFAPPQAPSPPR----------ASVIQAAASSSH----------DDLSIFDL-GF-----
----------------QHRMKK-K----VKRARSGESP-------TATGPKRKSREGSTT
YLWEFLLKLLQDRDYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKNKPDMNYETMGRAL
RYYYQRGILAKVDGQRLVYQF--------VDVPKDIVEIDCSGA
>C_lec3 XP_014251487.1 ecdysone-induced protein 74EF isoform X1 [Cimex lectularius]
----------------------MPFIDDDLLWCPDA------------DNKMV---DLSQ
CLD---TGGG---LGELTQTDLTGL-VGT-------------------------------
------IDEEEDIFKSF-----ELEQFF-DFNN-----EEREENNNVGA-----------
------------------------------------------------------------
----------------TNKNQTL-----------------------AFLQELQRNQANAR
KFNIAAANPLLAGPYFIEKLAAPGPV---------TTSTPTVGSSAEPFLRIKTE-----
-PDTRQGTLNGSNHYKAEGMGNCRFKIPQKPGENHFVGVDGQQMRRPVDTAVAPTVGGVG
YVKREPQD-----HKAL----LHGILS----HQPHAAA-----------------L----
------------------------LASYTASNTG-------SLP---------PSPADSG
VSDVDSSSSG-HTSNDE---LRARLQPPP--------------------------HTYYQ
HTTATSCRRS------------------------------PEAATPSM------GGLYPT
AHFLS-------------------------------------------------------
-----------------------PYYHQPQPYP---------------------------
-------------------NRTLTDGYGGAGGGGGGGGGGGGGGGGGGGAATGYMGPPQN
YFAPPQAPSPPR----------ASVIQAAASSSH----------DDLSIFDL-GF-----
----------------QHRMKK-K----VKRARSGESP-------TATGPKRKSREGSTT
YLWEFLLKLLQDRDYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKNKPDMNYETMGRAL
RYYYQRGILAKVDGQRLVYQF--------VDVPKDIVEIDCSGA
>D_mel1 NP_730287.1 Ecdysone-induced protein 74EF, isoform A [Drosophila melanogaster]
----------------------MPFIDDALLWCPDN------------DGRLVGGLDLGT
CIADDSTANG---TENLNPSIQSAGNPNNPQQSVGGEILGSVESAGNELNGAAARNVNVV
VEPLCGGDSSDELFRSFSESNFEIESLLSDLATVEVKVENEENNNNVITDDDFASVAAAV
VANDDLLAKENAQLSAQGLVDSVAASLADSGDAGGQQALLAFGSSSSAASAIAAAAAALC
GDLINNNNNNSNSNNNSNGNGNHGGGGGGASSGGGVAGDCATKLEYALMGGQPLAE-EPR
FVTSAAANPLLV-----EKLMSKCLNIEKRMDKLSDTEIPIVKQSTSPAPQQQLQQQHHL
QQQQQQQPHNGSTFAGATALLHI--KTEQNTLLTPLQLQQQQQQQQGLHGAAGNGGSSNG
NNAHQQQQPLAIPQRPL----LHNLLSGGAIHNPHHR-----------------------
--------------------------NYTTATTG-------SFP---------PSPADSG
VSDVDSSSSGGQPCADE---LKARLGMPPATSASAAAAAAAAAAAAAHLHTGTFLHPNLY
QNNAANSLRNIWNRSVGVPDNYYGSSGAGSGGTQPGGPGNPQTPG-YLTTSYFNAPTAAT
AAASQRGTTINGYH-SLHQQQQQQQQSQQSQQQQQLAHQQLSHQQQQALHQQLSHQQQQQ
QQQQQQ----------------HPHSQLNGPHP---------HSHPH--SHPHS------
-------------------HPHAGQHTHSTIAAAAAAAAASVVSSSSS---AVAAA--AM
LSASAAAAATAAAAA-G---GSQSVIQPATSSVS---------YDLSYMLELGGF-----
----------------QQRKAK-K----PRKPK------------LEMGVKRRSREGSTT
YLWEFLLKLLQDREYCPRFIKWTNREKGVFKLVDSKAVSRLWGMHKNKPDMNYETMGRAL
RYYYQRGILAKVDGQRLVYQF--------VDVPKDIIEIDCNGV
>D_sim1 FBpp0323369 FBgn0184127 Eip74EF [Drosophila simulans]
----------------------MPFIDDALLWCPDN------------DGRLVGGLDLGT
CIADDSTANG---TENLNPSIQSAGNPNNPQQSVGGEVLVSVESAGNELNGAAARNVNVV
VEPLCGGDSSDELFRSFSESNFEIESLLSDLATVEVKVENEENNNNVITDDDFASVAAAV
VANDDLLAKENAQLSAQGLVDSVAASLADSGDAGGQQALLAFGSSSSAASAIAAAAAALC
GDLINN-----NSNNNSNGNGNHVGGGGGAGSGGGVAGDCATKLEYALMGGQPLAE-EPR
FVTSAAANPLLV-----EKLMSKCLNIEKRMDKLSDTEIPIVKQSTSPAPQQQLQQQHHL
-QQQQQQPHNGSTFAGATALLHI--KTEQNALLTPLQLQQQQQQQQGLHGAAGNGGSSNG
NNAHQQQQPLAIPQRPL----LHNLLSGGAIHNPHHR-----------------------
--------------------------NYTTATTG-------SFP---------PSPADSG
VSDVDSSSSGGQPCADE---LKARLGMPPATSASAAAAAAAAAAAAAHLHTGTFLHPNLY
QNNAANSLRNIWNRSVGVPDNYYGSSGAGSGGTQPGGPGNPQTPG-YLTTSYFNAPTAAT
AAASQRGTTINGYH-SLHQQQQQQQQSQQSQQQQQLAHQQLSHQQQQALHQQLSH--QQQ
QQQQQQ----------------HPHSQLNGPHP---------HSHPH--SHPHS------
-------------------HPHAGQHTHSTIAAAAAAAAASVVSSSSS---AVAAA--AM
LSASAAAAATAAAAA-G---GSQSVIQPATSSVS---------YDLSYMLELGGF-----
----------------QQRKAK-K----PRKPK------------LEMGVKRRSREGSTT
YLWEFLLKLLQDREYCPRFIKWTNREKGVFKLVDSKAVSRLWGMHKNKPDMNYETMGRAL
RYYYQRGILAKVDGQRLVYQF--------VDVPKDIVEIDCNGV
>M_ext1 PNEQ01062987.1 M_extradentata Eip74EF
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------PLLL-----SWLLIECVQISLQVIVKVTRTYSCLKYSMSPKENPNFSQHKPR
-QEAIQSPQQPANYTGRKRGNAC--GPDRDTHPPPLPVRMRIPSARQKMCSAGTPKSGD-
NPSNNDARALLAPSRPLVRH-----LNGAKIFSPQNRGYIL--------------ISFGG
NGTR----------PRFCTLWSSVTSPKSGKGRGSGGGRKTSLPVTS------PASANSE
RAPVDPESSR---------------------------------------WEGTFIY-KIV
CMGRDGEVRRRWMRDRAINGRKITNRTPGAGVLDPAAPGVKDQPRLAGRTLIFDALKGRA
SKRVAAGEGFFGRDIGLIPGLRGSRDEAVSNSVPMIMRAARPRGASQGIIRQ-----DSH
MQKSGD----------------RPRQEL--------------NPERLRGRRGAGVA----
-------------------RSHSSEHIAQTRDGVEVASSGGRVRRVSV---CIFQG--RV
VACSGASPAAAES---G---GGEQLLRKTTKISN---------YCLVLLSNIPKFH----
----------------QHSVPPYQ-------------------LLNAASSRLVAQGSGQI
QLWQFLLELLADSSN-ASCIAWEG-TNGEFKLTDPDEVARRWGERKSKPNMNYDKLSRAL
-YYYDKNIMSKVHGKRYAYKF-----------------------
>M_ext2 PNEQ01084081.1 M_extradentata Eip74EF
P--------------------NVP------------------------------------
-------------QQQVTQVITARSNLQQSAT----------------------------
FQQQQNIQHSKQVQNLQHQQQQNLQ---------------QQQQN---------------
------------------------------------------------------------
------------------------------------------------LQQQQNL--HQQ
QQNLQQQQQNLQQQN-LQQQNMQQQNLQQQNLQQQNLQHQNLQQQQNLQQQQNLQQQQN-
-LQQQQNLQQ--------------------------------------------------
-------------QQNLQQQQMHSNLATQQNYIPQQTA----------------NISIKT
DNTA--------------------GDPSAATSAA---DRFTAVP---------TTAATAS
ASSASTASSS------------------P-------------------VLCSTIFPSDLR
PCCASVSLSGGW-RGCGTTSSYPETVATASAATSTAAKCSTASAA-TSTTAKCSAAKCAA
AMQQQ--QQLLSQQQQLQLQLQ-QQQQLQQQQLQQQLQQQQPQLQQQQLPPQ-----HQQ
QQLPPQ----------------HQQQQL--------------PPQHQQQQLPPHQQ----
------------QQL----PPHQQQQLPPQNAAANAATATNAGTTTSATT-TTATA--AS
TAATAASTAATSATT-A---TAASTTAASAATLL---------YNLVFLLTNNKYF----
----------------KQNVPEHK----PKLPS------------QRHSNDVPSRSGYDW
QVLEFPLNIW----YCISFTTFAQEVVGFILLTLPKK----------------DDVLRVL
R-------------------------------------------
