>A_pis1 XP_029347438.1 ecdysone-induced protein 74EF isoform X1 [Acyrthosiphon pisum]
----------------------MPFMDDVLLWCPEA------------ETKID---DFTE
CLGNE-VSSLGE-LLQSEISS-------------------ELDNAL-DGGGSS-----VQ
DGGEHSGDDDIFKQLSDSSALLEQFF-DFVNCDIK---EENNNNVM--------------
------------------------------------------------------------
--------------STGNKNHAA--------------------VALLQELQRTNA-GKKF
NITTANPLLA-----EKLLNPVSQLNPSLNQNSDMFIN---------QNKYIKTEPSIND
IGKQTVRPTSPPPTTTTV--GNEKDENIDFLDHLRI-------------AGNGGVGN---
------------------PGAAD----HLPPRQQLSF-----------------------
---ALPHGFHHAGSLP-----------PSPADSGVSDVDSSSS-----------------
----GHTSTDTE---LRARLQPHQY----HHQVSSCGRR---------------------
---------------------------TS------------------PDPPS--------
------------N-------VQCHQQQQQQQQQQQQ-QQQQQ------------------
---QQQQQQQQQQDLFSRIYGVNAPPP---------GAYHH--PSPASPS----------
-----------PKHPLFMRNNHPYGGGVAGYHPSTVGGYGPAVSPT--------SDGHFA
MPPCPPVAALPGA---GTVIGRGSVIQAAAANCYQPNGAGAANLNDLYYMDF-GAPTAAA
AMYHQKTVGNKSGNNKKPK-KYGTVGRPSVAGSPGAVQQQTCPATGPKRKSREGSTTYLW
EFLLKLLQNSDYCPRFIKWLNREKGVFKLVDSKAVSKLWGEH-KNKPDMNYETMGRALRY
YYQRGILAKVDGQRLVYQFVDVPK------DIVEIDCSGA
>G_bue1 GBUE008361-PA
----------------------M-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GGGGYYTAGSG-------
-----SPPR-------------ASVIQAAASSSH----------DDLYLLEL-GF-----
-------------NNRIKK-K----LKRPKTGDAT-----QCQGQGPKRKSREGSTTYLW
EFLLKLLQDREYCPRYIKWTNREKGVFKLVDSKAVSRLWGLH-KNKPDMNYETMGRALRY
YYQRGILAKVDGQRLVYQFVDVPK------DIVEIDCTSA
>F_exs1 XP_029678074.1 ecdysone-induced protein 74EF isoform X1 [Formica exsecta]
MPVPVSQTPTLTSTLVPKEESNMPFIDDELFWYSDN------------DGKM----DLTQ
CLQQSNTGQSVE-FSPMELSA--------------L-----------VGTPAA-PNVPAE
EGAGMSTGEELFDPL------------DFLR-----ELEAEASQPT--------------
------------------------------------------------------------
-------------STTTPSSYR----------------------------------RQRH
NIAAANPLLA-----EKLAAPSTQTSP-------TSIPYA--SRAEIKTENIKPEPSIVD
TREVQ--------------------PHDTGEKEQLGLASVKVEPGSTSATTTS-------
-----------STGTRLLHGILS----QHPQQHSLGLQNGYGRHLTGHAQ------MGQP
PYTTAATSTPGSGSLP-----------ASPADSGVSDVESSTS-----------------
----SGGNEDAN-LLLKARLNPNS--SLQPGLASHHSHL---------------------
-----------------------------------------------SSAAL-GRSACHS
PGVYPSTATFLP------------------------------------------------
--------------PSYHP---HQHHPSQYHPHRGSSPHHQHSNHTMGSTMGPPHHHHHH
HQTQSLQHLHYRQPPSLSES---YNNYVNSMYGGGG---------------------QFA
TPCTPSPPRGPG-------GVPTSVIQAATSSVS----------DDLYLLEL-GF-----
-------------PPRSKKSK----LKKPRQGEGG--------GAAVKRKSREGSTTYLW
EFLLKLLQDREYCPRYIKWTNRERGVFKLVDSKAVSRLWGLH-KNKPDMNYETMGRALRY
YYQRGILAKVDGQRLVYQFVEVPK------DIVEIDCTGA
>N_lug1 XP_022185398.1 ecdysone-induced protein 74EF [Nilaparvata lugens]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----MNPLDG-----HCHLPEDAMEAP-------LDLS-V--AATSVKLEYLTDDSDDSD
SHGG---------------------PNCKAYKKSL------IKRYLDTTAPAPL----YI
KREPGE-----HKGLQGLPGILS----HHPHAALL-------------------------
-----NYNASNTGSLP-----------PSPADSGVSDVDSSSS-----------------
----GHTSNDE----LRSRLNPQP-----PHQVTSCRRS---------------------
-----------------------------------------------PDSAG-GLYTPHF
LAPYPTYTAASA------------------------------------------------
--------------PAPAP---MRPHP---------PPHPHYTNHTHG------------
-------------RTNLSDG---YASYMAALGGAPQTGVAGGA--------------YFP
---APSPPRLPGS------GVPTPVIQAAASSSSTSPA-----ADDFYLLEM-GF-----
-------------QRKLKK-Q----KRIRVAGDAM-------PGQGAKRKSREGSTTYLW
EFLLKLLQNREYCPRYIKWTNREKGVFKLVDSKAVSRLWGLH-KNKPDMNYETMGRALRY
YYQRGILAKVDGQRLVYQFVDVPK------DIVEIDCSGA
>N_lug2 XP_022207261.1 ecdysone-induced protein 74EF-like [Nilaparvata lugens]
M--------------------EVPSTT----WFSEALCTSLYKDSHSPSSGLD---DESA
YISTN-YTDLSD-ACRNQITH-------------------DDSKKFNNNSGES-----MS
DTNRNS---------------------DSDNGDKNQGDSENNN-----------------
------------------------------------------------------------
-------------------------------------------YLMLQAKHRLNH-----
----SHPTIH-----------------------------------STQEEYIDLDKLY-Q
SHHRTLLNSSYSPASSS-------------------------------------------
-HYQHN-----HQHLQ--------HTINHPHHHNILAQQLSCLHRQ---QHPTDLGI-RG
QGHGHPHQGHPQGRIPLQGHPQGR--IPPPGHPG-----SSSQ-----------------
----GHRSSQLH--------HLHP-----PASVSSSTSP---------------------
---------------------------TSLSIP-------------SPHLNS--------
--------------------DHNHRRNHLGHHQHLP-QQLPH------------------
---AHAQQTTSALSINSSHHSYNNYPP---------SVFNG--GTGTHPV----------
-----------GSQSQGRDG---YGQSSAGNEPNDYSSYAQQQYPNYN------------
--------------------------EDPDSDSE---------SD---------------
-------------HQRDIEAQ----PVKKRPGRPR----------GSRRKKPE-KLGRLW
EFIRDLLLNSETCPSLICWDNYEEGMFRFVHSDKVAKLWGAK-RDNPDMNYEKLSRAMRY
YYKSKVLQPVFGRRLVYKFG--PEAKGWKTDNPNFRC---
>C_hook2 maker-scaffold212-size1131905-augustus-gene-1.5-mRNA-1
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------M--------------
------------------------------------------------------------
------------------------------------------------------------
--AVTTGMLV--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------VGAV---------------------------------------------
---------------LAAR-----------------------------------------
---------------------------T-------------------PESPGPGHPQQHS
GYGVPPHGGFLT------------------------------------------------
--------------PFYHP---HQPAR---------VPPHHYVG----------------
-------------RQPLGDG---YGGYL---QPSHQANLYHQH------------QQHFA
APPAPSPSRP---------AIPTSVIQAATSSVG---------PDDLYMLEL-GF-----
-------------QPRPVKKK----LKKSKSGEPG----------AVKRKSRE-------
--------DRDYCPRYIKWTNREKGVFKLVDSKAVSRLWGLH-KNKPDMNYETMGRALRY
YYQRGILAKVDGQRLVYQFVDVPK------DIVEIDCTGA
>C_lec1 CLEC009111-PA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------LGSHLE-DPRTTPTHSENILSPNI---------------------
-----------------------------------------------YKAES------DS
L-ETKPLAQDYP------------------------------------------------
--------------PHYFQ-----------------------------------------
---------------FLTDG---YGGAGGGGGGGGGGGGGGGGGGGAATGYMGPPQNYFA
PPQAPSPPR-------------ASVIQAAASSSH----------DDLSIFDL-GF-----
-------------QHRMKK-K----VKRARSGESP-------TATGPKRKSREGSTTYLW
EFLLKLLQDRDYCPRYIKWTNREKGVFKLVDSKAVSRLWGLH-KNKPDMNYETMGRALRY
YYQRGILAKVDGQRLVYQFVDVPK------DIVEIDCSGA
>C_lec3 XP_014251487.1 ecdysone-induced protein 74EF isoform X1 [Cimex lectularius]
----------------------MPFIDDDLLWCPDA------------DNKMV---DLSQ
CLDTG--GGLGE-LTQTDLTG--------------L-----------VGT----------
----IDEEEDIFKSFE-----LEQFF-DFNN-----EEREENNNVG--------------
------------------------------------------------------------
-------------ATNKNQT-----------------------LAFLQELQRNQANARKF
NIAAANPLLAGPYFIEKLAAPGPVT---------TSTPTV--GSSAEPFLRIKTEP---D
TRQGTL-NGSNHYKAEGMGNCRFKIPQKPGENHFVGVDGQQMRRPVDTAVAPTVGGVGYV
KREPQD-----HKAL--LHGILS----HQPHAAAL-------------------------
---LASYTASNTGSLP-----------PSPADSGVSDVDSSSS-----------------
----GHTSNDE----LRARLQPPPHTYYQHTTATSCRRS---------------------
-----------------------------------------------PEAAT------PS
MGGLYPTAHFLS------------------------------------------------
--------------PYYHQ---PQPYPNR-------------------------------
---------------TLTDG---YGGAGGGGGGGGGGGGGGGGGGGAATGYMGPPQNYFA
PPQAPSPPR-------------ASVIQAAASSSH----------DDLSIFDL-GF-----
-------------QHRMKK-K----VKRARSGESP-------TATGPKRKSREGSTTYLW
EFLLKLLQDRDYCPRYIKWTNREKGVFKLVDSKAVSRLWGLH-KNKPDMNYETMGRALRY
YYQRGILAKVDGQRLVYQFVDVPK------DIVEIDCSGA
>D_mel1 NP_730287.1 Ecdysone-induced protein 74EF, isoform A [Drosophila melanogaster]
----------------------MPFIDDALLWCPDN------------DGRLVGGLDLGT
CIADDSTANGTENLNPSIQSAGNPNNPQQSVGGEILGSVESAGNEL-NGAAARNVNVVVE
PLCGGDSSDELFRSFSESNFEIESLLSDLATVEVKVENEENNNNVITDDDFASVAAAVVA
NDDLLAKENAQLSAQGLVDSVAASLADSGDAGGQQALLAFGSSSSAASAIAAAAAALCGD
LINNNNNNSNSNNNSNGNGNHGGGGGGASSGGGVAGDCATKLEYALMGGQPLAEE-PRFV
TSAAANPLLV-----EKLMSKCLNIEKRMDKLSDTEIPIVKQSTSPAPQQQLQQQHHLQQ
QQQQQPHNGSTFAGATAL--LHIKTEQNTLLTPLQLQQQQQQQQGLHGAAGNGGSSNGNN
AHQQQQPLAIPQRPL--LHNLLSGGAIHNPHHR---------------------------
-----NYTTATTGSFP-----------PSPADSGVSDVDSSSSG----------------
----GQPCADE----LKARLGMPPATSASAAAAAAAAAAAAAHLHTGTFLHPNLYQNNAA
NSLRNIWNRSVGVPDNYYGSSGAGSGGTQPGGP------------GNPQTPG-YLTTSYF
NAPTAATAAASQRGTTINGYHSLHQQQQQQQQSQQS-QQQQQLAHQQLSHQQQQALHQQL
SHQQQQQQQQQQQHPHSQL---NGPHP---------HSHPH--SHPHS------------
-------------HPHAGQH---THSTIAAAAAAAAASVVSSS------------SSAVA
AAAMLSASAAAAATAAAAAGGSQSVIQPATSSVS---------YDLSYMLELGGF-----
-------------QQRKAK-K----PRKPK------------LEMGVKRRSREGSTTYLW
EFLLKLLQDREYCPRFIKWTNREKGVFKLVDSKAVSRLWGMH-KNKPDMNYETMGRALRY
YYQRGILAKVDGQRLVYQFVDVPK------DIIEIDCNGV
>D_sim1 FBpp0323369 FBgn0184127 Eip74EF [Drosophila simulans]
----------------------MPFIDDALLWCPDN------------DGRLVGGLDLGT
CIADDSTANGTENLNPSIQSAGNPNNPQQSVGGEVLVSVESAGNEL-NGAAARNVNVVVE
PLCGGDSSDELFRSFSESNFEIESLLSDLATVEVKVENEENNNNVITDDDFASVAAAVVA
NDDLLAKENAQLSAQGLVDSVAASLADSGDAGGQQALLAFGSSSSAASAIAAAAAALCGD
LINN-----NSNNNSNGNGNHVGGGGGAGSGGGVAGDCATKLEYALMGGQPLAEE-PRFV
TSAAANPLLV-----EKLMSKCLNIEKRMDKLSDTEIPIVKQSTSPAPQQQLQQQHHL-Q
QQQQQPHNGSTFAGATAL--LHIKTEQNALLTPLQLQQQQQQQQGLHGAAGNGGSSNGNN
AHQQQQPLAIPQRPL--LHNLLSGGAIHNPHHR---------------------------
-----NYTTATTGSFP-----------PSPADSGVSDVDSSSSG----------------
----GQPCADE----LKARLGMPPATSASAAAAAAAAAAAAAHLHTGTFLHPNLYQNNAA
NSLRNIWNRSVGVPDNYYGSSGAGSGGTQPGGP------------GNPQTPG-YLTTSYF
NAPTAATAAASQRGTTINGYHSLHQQQQQQQQSQQS-QQQQQLAHQQLSHQQQQALHQQL
SH--QQQQQQQQQHPHSQL---NGPHP---------HSHPH--SHPHS------------
-------------HPHAGQH---THSTIAAAAAAAAASVVSSS------------SSAVA
AAAMLSASAAAAATAAAAAGGSQSVIQPATSSVS---------YDLSYMLELGGF-----
-------------QQRKAK-K----PRKPK------------LEMGVKRRSREGSTTYLW
EFLLKLLQDREYCPRFIKWTNREKGVFKLVDSKAVSRLWGMH-KNKPDMNYETMGRALRY
YYQRGILAKVDGQRLVYQFVDVPK------DIVEIDCNGV
