>A_pis1 XP_001942520.2 broad-complex core protein isoforms 1/2/3/4/5 [Acyrthosiphon pisum]
M-----------------------------------------------------------
-----------------------------------------TNNHLNTISGQDQQYCLRW
NNHQTNLTNVFVQLFQSEEFTDTTLFCEGGPPVKCHKMVLAACSSYFQSVFAE-VP-GKH
SAVVL-KDVGHSEMKAILDYMYKGEVNIAHDQLAALLKVAEMLKVKGLVQDNTYQPQSAT
------PTVEEDRNIISTSSPNHV-SPDGNTSASKDLAININNNNEHNDSPPHSTGITHQ
-------------SPFYNKNYYGKSPPLV----------------DLRPGRSNVPMWPMP
AMQLSSTPVTNAMFGGSYDAMIAG-------HP---------------------------
--------GMSPLRRKKLSSMLMGRDTPILRTVLGQGQADSSQQL--ALPLYG---SEAM
EHHRPQSNGSEHSSQFSKIKLEGSEPHSPYPPDMS------------MNDDDEM-----I
RMGKMN-NSSSPQSIYGDSKS---------------------------------------
--------------------------------------GIVTPGIATYVPSHKPEWKRYK
QY-----------TRQDIMS-------------------AIDAVRTGM-SALQASRKFGV
PSRTLYDKVKKLGITTS-----RPFRRSGVNNGNL-------------------------
--------------------GFAYGLGP-----------GTSSVMFTGQMSGAEDESGHS
TAMEHATAGFLHHAL-----------------------------------GLSGVPLKSD
HETSNNGHS------------PRSDRMDDGGSPCSPELIKYAGHREDTQSPTPTDNDDQA
Q------DLSVSR---KSESSMQATPTSRIIMAPISQTPS-------------------V
PMLAA-------------------------------------------------------
--------GNDDRD----------------------------------------------
---------------
>G_bue4 GBUE001543-PA
M-----------------------------------------------------------
--------------------------------------------------SGPQQYCLRW
NNHRSNLLTVFDQLLQNEAFTDVTLACEGGTSVKCHKMVLAACSSYFQGLFTE-LP-CRH
PVVVL-KDVRYSEMKAILEYMYRGEVNVAHDQLAALLKVAEALKVKGLVEENGTVPRLKN
--------SDEEGNAISTSSCTANTAVPPSSSVT-------------EGSPPHSSTGRSD
----------------YSRFSYGKGE-------------------ERSSSRVSFPLWGVS
GLPLTTPPPPNSPYSSA-------------------NLNRCYEAITA-------------
--------DMPPLRRKKLSSLLMSRDTPILRTVLGQGQADSSQ-----------------
----PESTSEDAPSPFTDISA--------------------------VDEEERQ------
--NKFALHSSSPQSFYGDNKGIIFSDQT--------RTLILNTTNEGKKLFEKKP-----
----------------------------------NVESNGILSGIATYVPTPKPEWKRYK
QY-----------TRNDIMS-------------------AIDAVRNGM-TALQASRLFKV
PSRTLYDKVKKLGITTN---RERPFRRSSNGNGSA-------------------------
--------------------AFPYSMS------------GTGSLVYGNT----KDDNAYS
SAV--MEQGFLHHTLEAHNIKREE------------------------IEREAAVAMVAA
CNIADNSSG------------EISSPHANDRSQ-SPNLIKYA--RPSSASPTSPMDDESD
RVE----DLSISRKADTPTGPRVIMPPM-------SQSSA--------------------
------------------------------------------------------------
------------------------------------------------------------
----------PH-LH
>G_bue3 GBUE005702-PA
MAA-------------------------SQQQP---------------------------
-----------------------------------------NGALPLPPPQSPQQFCLRW
NNYQTNLTNVFDQLLQSESFVDVTLACE-GHSVKAHKMVLSACSPYFQSLFFD-NP-CQH
PIVIL-KDIKWTELKAAVEFMYKGEINVSQDQIGPLLKVAETLKIRGLADVNGE-QELG-
-------RTGDDGVSVS-------------------------------------RKKR--
---------------------------------------------RRSSGDDSAAEDSLS
ESLDGRAP---------------------------------LELVTTSPQP---------
--------PQTP-----------------------------------QLPTHSALLSLPL
PPPPPPPPPPSST----------------------------------ANSDEME------
------------------------------------------------------------
----------------------------------------IKPGIAEMIREEER------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------VSVDCSHHA-------------------------------------------
------------------------------------------------------------
---------------
>M_ext3 Medex_00067579-RA
M-----------------------------------------------------------
---------------------------------------------QHASAESPQQFCLRW
NNYQSNLTNVFDQLLQSESFVDVTLACD-GHSVKAHKMVLSACSPYFQALFFD-NP-CQH
PIVIL-KDIKWPELKAVVEFMYKGEINVSQEQIGPLLKVAESLKIRGLADVNGE-PEFGG
DAKKWSSSSSSQGAAVAAHDLSPD----------------------GAASPAHRHKKR--
---------------------------------------------RRMSGERASPEEGDA
ASGGGEPPPAPAAPA---------------------GLDMTLAASQPPPPP---------
--------PPPP-----------------------------------PPPPHGLSLGDSL
PPPPPPPPVP-------------------------------------AHPDDME------
------------------------------------------------------------
----------------------------------------IKPGIAEMIREEERHVTC--
--------------------------------------------------------LFRE
PA----------------------------------------------------------
------------------------------------------------------------
-----------HYS----------------------------------------------
------------------------------------------------------------
-----------------DSSARHISPFD--------------------------------
------LFILSNC-----------------------------------------------
------------------------------------------------------------
-F--------P----
>C_hook1 maker-scaffold4790-size194163-augustus-gene-0.5-mRNA-1
M-----------------------------------------------------------
---------------------------------------------------GSEHYCLRW
NNHQSNLLGVFSQLLQDESLVDVTLACAEGHSIRAHKVVLSACSSYFQTLFVD-HP-NRH
PIVIL-KDVRFAELRTLVEFMYKGEVNVEYCQLSALLKTAESLKVKGLAEMTNI------
------REGEGQKSGGPASAPETPRLTPEELPVTSGT-VKRLLEEDAETPSPSRRREDSD
----------------NDSCDEGGGD-------------------VNAMPDDLSPCPGPS
DMTVATSCSNPAVPSSCS------------------GVGSRLPSPHSSEPI---------
---------PGPSGM-----------MPVQQVPLSQGASDVSG-----------------
----CDRSCSTIGTGYPG----------GEP----------------VKPGDMV------
-----------------DEQSVSYGVPG--------RLGVADPVSECVKLSGGNP-----
--------------------------------MKHVGVKDVLTILAMVVVDMSRTWTVMV
VH------------------------------------------------------PRWA
PGNK----------------VEQP------------------------------------
--------------------QFFHLLVGRHDVGGDEVVCRSC------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------VDQGHHLLPVD-------------------------------I
HWDA--------------------------------------------------------
------------------------------------------------------------
---------------
>M_ext4 Medex_00066470-RA
M-----------------------------------------------------------
----------------------------------------------MTSALSSQRFCLRW
NNHQSNLLTVFDQLLHDESFVDVTLAVE-GRLLKAHKMVLSACSPYFQALFVG-HP-DKH
PIVIL-KDVPYCDMKSLLDFMYRGEVSVDQERLTAFLKVAESLRIKGLTEVNEE------
---------KYDLPSITSSLLSSV-PPPVVTTHT-------------PPPPPHLHRIHPI
-----PSQR------------------------------------RNLSMPSATPLLGSA
LTAPKRKRGRPRKLSGSS------------------GGAAGAQAATTPADG---------
--------------------------AAAQKTSTGNGEVDNSAR----------------
PAQVPDPVVAQSSPEMLE-------------VKMSVDFQQSGASGG-RPPDGEI------
-----------------GNDSTAMATEP--------SSDQADTQQKNGHIAYSND-----
----------------------------------CTQLNSACSVLVSLVPDCTSRVQSFF
MF-QWCLALAGCAPRANFIA------------------LALETVRLS-------------
-------------------------------------------------ECKYG------
-----YGLLRVNNM----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>C_hook3 augustus-scaffold63-size1621153-processed-gene-11.1-mRNA-1
M-----------------------------------------------------------
------------------------------------------------SQGSSENFSLRW
DSFHSNLSTSFHTLLQGEELVDVTVAAE-GRFVQAHKLVLSVCSPYFKSLFKV-NP-CQH
PIVIL-KDVGHKELVSMLEFMYRGEVNVSQEDLAEFLKTAELLQIKGLTGDDTPGLMFYN
I----CNGAQEQGEQETKSKDTPA-----------------------REPPPPPPDPQP-
---------------------------------------------PKVRTPQKSPVK---
----KRMRQEPR-QESPQY------------NPP--RRSPSIPHATMPQT----------
---------STPSRKPVSST--------------SESSVDADY-----------------
----PSRDVEYVDVPTAK----------LEPVEIDSDIEEVD-----ANFDEST-DFS--
--EFFA-GQSSQQQSFQDFSGV--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>C_hook4 maker-scaffold63-size1621153-augustus-gene-13.2-mRNA-1
M-----------------------------------------------------------
------------------------------------------------SQGSSENFSLRW
DSFHSNLSTSFHTLLQGEELVDVTVAAE-GRFVQAHKLVLSVCSPYFKSLFKV-NP-CQH
PIVIL-KDVGHKELVSMLEFMYRGEVNVSQEDLAEFLKTAELLQVKGLTGDDTPG-----
----------EQGEQDTKSKDTPA-----------------------REPPPPPPDPQP-
---------------------------------------------PKVRTPQKSPVK---
----KRMRQEPR-QESPQY------------NPP--RRSPSVPHATMPQT----------
---------STPSRNPVSST--------------NESSLDSKY-----------------
----PSRDLEYVEMPTTK----------VEPVEFDSDIEEVD-----TNFDEST-DFS--
--EFFA-GQSSQQHSFQDFSAVGLPDGQ------------SGASQALGIPQEGEQV----
-------------------------------------VENLLTA-SKFIEDDMEAERATG
SA------------ENEVVYGSR--GKPQ---------LVHDGYLFCL-HKRSASHYLHI
PF---EEFDNKGGLQIIRSRTGRPQLINNGYLFSV----RKYHGDRVYWQCMQRVSCNCS
ARVNTCGNEVTVMC----GLQIVYSVRGKQQLVHDGYLYSVNRMIGDRV-----------
-----------YWECIQHRCCRAR------------------------------------
-ARSCGNEL---------------------------------------------------
------------------------------------------------------------
---------IVAC--------------------------------------------GDH
SHPPHT-EKIRERG----------------GV----------------------------
-------------VE
>C_hook5 maker-scaffold1138-size564540-augustus-gene-1.4-mRNA-1
MCAGDVWYVSSRKGSYQLIYDGSIYNCDSRNGPK-SFWRCSQLREGCRARCSVLGDTLFL
GHFQHNHPPNSDK-------IARKFCFSELIPTNIQNVEKAPLNSPKMANSDSEQFSLRW
NNFHSNLSSGFHAFLQGEDLVDVTLAAG-GKFLQAHKLVLSVCSPYFKELFKV-NP-CKH
PIVIL-KDVGHKELEDILEFMYRGEVNVRQDDLTEFLKTAEMLQVKGLTGDDSS------
--------SDQQGSSHVPPPPSPA---PSQSSVKVKP----------RKPQPKAPPLDSM
-----PPSP------------------------------------MMDDLPARSPAADVN
PPPFKRMKQEPQPQPSPQP------------PPQQFKQESQLQPQYKPQTM---------
---------SSPSPRRLPPA--------------SPLSVDDSS-----------------
------RGVEFVEVTKPK----------MEPVDIESDVEEVD-----AGLDDKT-DFS--
--DFFG-GESSQSH--QDAPGMGM----------LPGMSMSGMSQDMGMPQDGGQ-----
------------------------------------------------------------
------------------------------------------------------------
---------GRISLSLVC--RARPSALAA-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------AC-----------------------------------------------
------------------------------------------------------------
---------------
>D_mel1 NP_726750.1 broad, isoform A [Drosophila melanogaster]
M-----------------------------------------------------------
--------------------------------------------------DDTQHFCLRW
NNYQSSITSAFENLRDDEAFVDVTLACE-GRSIKAHRVVLSACSPYFRELLKS-TP-CKH
PVILL-QDVNFMDLHALVEFIYHGEVNVHQKSLQSFLKTAEVLRVSGLTQQQAE------
-------DTHSHLAQIQNLANSGG-RTPLNTHTQ-------------SLPHPHHGSLHDD
G----------GSSTLFSRQGAGSPPPTAVPSLPSHINNQLLKRMAMMHRSSAAAAAEET
SHAFKRLRGSDNSLPLSGAVGSGSNNNSPDLPPLHARSASPQQTPADFSTIKH-------
----HNNNNTPPLKEEKRNG-------PTGNGNSGNGNGNGNG----ASNGNGISISDKL
GSLTPSPLARAGADDVKS-----------EPMDMVCSNNN-------ANANDEH------
-----------------SNDSTGEHDAN--------RSSSGDGGK---------------
--------------------------------------GSLSSGNDEEIGDGLASHHAAP
QF--------IMSPAENKMFHAA-------------------AFNF----------PNID
PS-------ALLGLNTQ---LQQSGDLAVSPQGPHSIT----------------------
---RSAATS-----------------PTSSTSSPPSPP---TALISPTS----SLKGSLA
AA---------VYSLHSHAHGH----VLGHATSPPRPGSVGSSVG----SNLCTSTSMGC
GVNSGNNSG------------------------------N----NNGNNANNNSNNGNA-
---------TNNN---NNSSSSSTSPGSQATAAGGTVTQAGTPPLPLRMPPP---TSGGI
NEPQ-------ECPYCR-RTFSCYYSLKRHFQDKHEQSDTLYVCEFCHRRYRTKNSLTTH
KSLQH-------RGSSGMLKRLLKTTAIKHGLVGHGHGHGHVHHPHAHHHALSHPRTSLY
DFTSELGQP-PPGIQ
>D_sim1 XP_016037686.1 broad [Drosophila simulans]
M-----------------------------------------------------------
--------------------------------------------------DDTQHFCLRW
NNYQSSITSAFENLRDDEAFVDVTLACE-GRSIKAHRVVLSACSPYFRELLKS-TP-CKH
PVILL-QDVNFMDLHALVEFIYHGEVNVHQKSLQSFLKTAEVLRVSGLTQQQAE------
-------DTHSHLAQIQNLANSGG-RTPLNTLTH-------------SLPHPHHGSLHDD
G----------GSSTLFSRQGAGSPPPTAVPSLPSHINNQLLKRMAMMHRSSAAAAAEET
SHALKRLRGSDNGLPKTFKAGLARRM----------------------------------
-----------PLKEEKRNG-------PTGNGNSGNGNGNGNG----ASNGNGISISDKL
GSLTPSPLARAGADDVKS-----------EPMELVCSNNN-------ANANDEH------
-----------------SNDSTGEHDAN--------RSSSGDGGK---------------
--------------------------------------GSLSSGNDEEIGDGLASHHAAP
QF--------IMSPAENKMFHAA-------------------AFNF----------PNID
PS-------ALLGLNTQ---LQQSGDLAVSPQGKLTTN----------------------
---ATTTTTTINNLITNNNNNYDYSLPTKNSNSQKTPSPTTTTLTTPTT-----------
-------------------------------TTPTRPTAITSASG---ICGLNLSTFAAN
GSSSGGSNGGLSMTALLPQQQQQQQQHQMSQQQQQQQQQQ----QQGNSSSGQQQQSNGI
LACS---TPKANT---PTTTQQQMYAAVMAAAASASASTSGSANSSLNNSNSTLNTSGGL
NNSAS-GGDDFRCNPCN-KNLSSLTRLKRHIQNVHMRPTKEPVCNICKRVYSSLNSLRNH
KSIYH-------RN--------LKQPKQEPGVGATQAAANSFYHQQHQQQQLNHHSSS--
---------------
>D_sim3 FBpp0325479 FBgn0188167 br [Drosophila simulans]
M-----------------------------------------------------------
--------------------------------------------------DDTQHFCLRW
NNYQSSITSAFENLRDDEAFVDVTLACE-GRSIKAHRVVLSACSPYFRELLKS-TP-CKH
PVILL-QDVNFMDLHALVEFIYHGEVNVHQKSLQSFLKTAEVLRVSGLTQQQAE------
-------DTHSHLAQIQNLANSGG-RTPLNTLTH-------------SLPHPHHGSLHDD
G----------GSSTLFSRQGAGSPPPTAVPSLPSHINNQLLKRMAMMHRSSAAAAAEET
SHALKRLRGSDNGLPKTFKAGLARRM----------------------------------
-----------PLKEEKRNG-------PTGNGNSGNGNGNGNG----ASNGNGISISDKL
GSLTPSPLARAGADDVKS-----------EPMELVCSNNN-------ANANDEH------
-----------------SNDSTGEHDAN--------RSSSGDGGK---------------
--------------------------------------GSLSSGNDEEIGDGLASHHAAP
QF--------IMSPAENKMFHAA-------------------AFNF----------PNID
PS-------ALLGLNTQ---LQQSGDLAVSPQGKLTTN----------------------
---ATTTTTTINNLITNNNNNYDYSLPTKNSNSQKTPSPTTTTLTTPTT-----------
-------------------------------TTPTRPTAITSASG---ICGLNLSTFAAN
GSSSGGSNGGLSMTALLPQQQQQQQQHQMSQQQQQQQQQQ----QQGNSSSGQQQQSNGI
LACS---TPKANT---PTTTQQQMYAAVMAAAASASASTSGSANSSLNNSNSTLNTSGGL
NNSAS-GGDDFRCNPCN-KNLSSLTRLKRHIQNVHMRPTKEPVCNICKRVYSSLNSLRNH
KSIYH-------RN--------LKQPKQEPGVGATQAAANSFYHQQHQQQQLNHHSSS--
---------------
>C_lec1 CLEC000821-PA
M-----------------------------------------------------------
--------------------------------------------QQTAQLPQPPEVCLKW
NSYHSNMRATFPNLLNNEQFVDVTLACE-GRSIKCHKVMLSACSSYFEELLSQ-NP-CQH
PIVFM-RDLKFWEVQALVEFMYSGEVNVTQDRLPSLLAAADALQIKGLAGPSTG------
-----ASSAQEDDRLSAGDTDDTA---------TIQHI---------HHQPLLQKRVRK-
---------------------------------------------RKSTNPTAYPVRSQC
IAQALSSTINKAQAHSNQT----------------HQPNSSLQHQLKHKSM---------
----HSAGNAKPSAGVLTSS---GYSPPA-----KSKREDDSS-----------------
----PNSPLALIKD---------------EPLDLGIDSKETL-----TNYRQRC-GTSIL
PNDRDT-GHISRREDLKDENGVSDEDM---------EEQHEDDEFDGGGYDSKQE-----
------------------------------------------------------------
-------------NRDCKRFSNG-----------D----DEDSVRGS---------REST
PK----------------------------------------------------------
------------------------------------------------------------
-----------KDKL---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>F_exs1 XP_029671050.1 broad-complex core protein isoforms 1/2/3/4/5 isoform X1 [Formica exsecta]
M-----------------------------------------------------------
--------------------------------------------------VDTQHFCLRW
NNYQSSITSAFENLRDDEDFVDVTLACD-GKSLKAHRVVLSACSPYFRELLKS-TP-CKH
PVIVL-QDVAFSDLHALVEFIYHGEVNVHQRSLSSFLKTAEVLRVSGLTQQADQ------
-------TDRDELSHVRALAAGGN-HLPFHDKTE-----EIVFPRGGSPPTP--------
-----------------------------VTPTPTTV-QQLLRRAQIRRNAPERRTPDPH
DETAKRPRVPSPPLNNN-------------------------------------------
--------DATPTDFSMVKS------NHLSTKVEGNGVHDENS-----------------
----------LVEDNIKC-----------EPLELTGGNGG-------ANAGNNE------
-----------------DSSDSGAAASD--------------------------------
--------------------------------------RPPASASSNEHEPEPEHTSGAQ
NF-----------LPESKLFTST----PG-------------SFNFSM-AALT---TDHT
PL-----SVKFPGLSHG---LQTP-DLAGTSQDREVAE----------------------
---EDGGWQSAINI------EYQRQIQQSNQSDTSADRCGETAMQPSQE----QQQQELP
-----------IIDLLDNIKDQME-IVLKSEPVSPRMDELESC----LLSGHTIEDHEDL
DSAAHDNRD---------------------RDCHREKQQQ----QQQTSGRSSNSDAESR
WLRPRNGSLQNKH---EDQASRVVAPKEQQAQYSNRT-----------------------
-----------YCNLCQ-KTFSRAWSLQRHLADTHFYVPQSLSCDQCGRSYKSRNSLVSH
KSQYH---ARKDRK--------------------------------------EHEAKCEV
TY-------------
>C_lec4 CLEC009497-PA
M-----------------------------RAP-----TTLRLSE---------------
KHIVYNMLSNKN--------ISSNCLFT-------------IPWARTRAMGDMQHFCLRW
NNYQSSITSAFENLRDDEDFVDVTLACD-GKSLKAHRVVLSACSPYFRELLKS-TP-CKH
PVIVL-QDVMFEDLHALVEFIYHGEVNVRQRSLSSFLKTAEVLRVSGLTQQSEA------
-----VSMGLDRGGGLADGR---------------------------GSPYHPRKSVHKH
R--------------------------------------------ERPNSTNESMEHQDN
AMPMKRPKTEPTNNHG--------------------------------------------
--------ERSPRED--------MEEPPMDFSTSGNNNTN---------------LRDKH
DVSPP-----AINSDIKP-----------EPIELTPHIHNER--------EDSN------
-----------------DSGGEVMSEGG--------GVTISGGGSGGGG-----------
--------------------------------------GGAPQGHTNMMQDHEDSIQSTH
NY------------LDSKLFAGA-------------------GFNFSMAAALAAD-----
---------SLAGLNNQPHGLGSSDSLAGTSQQGL----RKV------FTCVA-------
-----CGKVLCSKA------SLKRHVADKHASRHEEYRCAICERVYCS------------
------------------------------------------------------------
------------------------------------------------------------
-----------------PSPPHRLLPPY--------------------------------
---------ACRCEILEPDSFSHAATTQRRDK----------------------------
------------------------------------------------------------
---------------
>G_bue1 GBUE021143-PA
M-----------------------------------------------------------
--------------------WYRRGLVA-------------PPVVAETDDDMSQHYCLRW
NNYQSNMTSVFHHLLRSQAFVDVTLACN-EQSLKAHKVVLSACSSYFQKLLME-NP-CKH
PTIIMPQDICFSDLKFIIEFVYRGEIDVSQAELQSLLKTADQLKIKGLCEVPEK------
--------------ESSPPPPPEV---------------MTLGSPRRHRHRPHKRRLHES
--LSHIPQPDYQIGNCMDAATSTE---------------------GDIKLADETSRDGED
MMEISHSMSPSSHH----------------------HPEHEHEQQADHEPQEHKFENGRS
AEMTDRGVDAAPLEPSDLAR--------QDAETHSNHEYNDEGE----------------
PVKVKYETLRTIDQSE-------------TLGHLDASRESSD-----VKDDHNSMQTMMI
TPELLG-LLPTSHG---DSGGSGSSDMCEGCP----KQSKNWTADDMEAALDALS-----
------------------------------------------------------------
------STLYKIARREGIRLAAPFNAAPTTWNPEDLER-ALEAIRSGQTTVQRAAADYGI
PSGTLYGRCKREGIGLT---RNNPTPWSEQAMNDALEAVR--------------------
-----IGQMSINQA------AISFNLPY-------------SSLYG--------------
--------------------------RFKR----------------------------GK
FDSSNGNNG------------SDDEPHSEGPPTSQTNQGQ-----PSSNAPTQSQTSNGP
SALI---QAALSS---PPPPQPQIMLVQYQAPVQPPA----------------------I
HMYTQ-------------------------------------------------------
------------------------------------------------------------
----------P--AT
>C_lec2 CLEC025389-PA
MNQSRC--------------------------PQEATATCLSLAE---------------
------DVNNLE--------TVSRLLSS-------------PETEEGDEMVNSQHYCLRW
NNYQSNMTSVFHHLLRTQAFVDVTLACN-DQSLKAHKVVLSACSSYFQKLLLE-NP-CKH
PTIIMPQDVCFTDLKFIIEFVYKGEIDVSQAELQSLLKTADQLKIKGLCEVPDG------
----------KEGAEVTPLPHNTS---------------RRGLSLRQRRLATAKRRLQYR
ERLNHSNQS------------------------------------NLSQVPVENGGNDEN
MAEMGRVPTPPSTL----------------------VPTLEIQQSETHRDV---------
------AVDSSDLGVVDNNV----------------------------------------
--KVKFETLRAIEQDPL------------DMEQITDQVSTVQ-----TNDDDHGMHTMMI
TPELLG-LIPSSNS---DGSEAGSTNAKNGIGC---SSTKTWTQEDMGAALDALRNQTMS
LSKASLHFGIPSTTLWQRAHRLGIDTPKKDGPTKSWSEDSLNTALDALRTGSISANKASK
AYGIPSSTLYKIARREGIRLAAPFNAVPTAWVPEDLER-ALEAIRSGQFTVQRAATEFGI
PSGTLYGRCKREGIELS---RNNPTPWSEDAMLDALEAVR--------------------
-----NGQMSINQA------AIHYNLPY-------------SSLYG--------------
--------------------------RFKR-------------------------CKYEA
EGLSSGGEM------------ENDQPMIHQQQQSQTQQPQ-----------TQSQAQSQP
QAQP---PQAQTQ---QPQAQPQIMLVQYQQPLQMYQSAT--------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>C_lec3 CLEC025251-PA
M-----------------------------------------------------------
---------------------------------------------MGGLGGSEQQYSLRW
NDFHSSILSSFRHLRDEEDFVDVTLACD-GCSFTAHKVVLSACSPYFRTLLKA-NP-CQH
PIVIL-RDVREQDMEALLRFMYNGEVHIGQEQLSDFLKTAQTLQVRGLADVPAK------
----------EQQKLLTGSNPTVPWANNNNNESNVSS-IVQNPSDGGASPPPSKRS----
---------------------------------------------RSSELAQNSVIGNRF
SPSPASSLNTNNHHHHSEARES--------------LLSQALESTHNSVSS---------
--------NNQPKGNSDSSV-------HAQSTGEESNSSDTGLSERGAVSDRGLSISTMN
G---PHSMADLIQPKT-------------EPSEYGDHHNSLV-----MDPNRTP------
-----------------NFSAALLGLQG--------------------------------
-------------------------------------LPGLLPGPSGM------------
--------------------------------------------------------HNSG
PD---NSFVSRRGLDMMRVRATDP---------------R---------PCPK-------
-----CGKIYRSAH------TLRTHLEDKHTVCP-GYRCVLCGTVAKS------------
-----------RNSLHSHMSRQHRGISTKDLPVLPMPSPFDPELASRLLAKAGVKVSAAE
LRARASPTGPPRR-------PEVRLELKSSDDPEDLTVHN----NHSTPASRFCSVDIRP
LSP----PIRHPM---SSPPPPQMPPHHNNKDPRGPSTGSAILDTYLQFIAE---NSAGL
HLSAEQAA----------KMAAKVSEEQRRMA----------------------------
--------LMDDRG-------------------------------------VEESSEPED
DFSEEEHEPEPIKAE
>G_bue2 GBUE009398-PA
M-----------------------------------------------------------
--------------------------------------------------MAADHFCLRW
NNYQSNMVSELDILRTEEYLVDVSLCCE-GHKFTAHKVILSACSPYFRNVFKE-NP-CEH
PVVIL-KDVLPEDVEALLSFIYQGVVYISEKKLSSFLQTAELLQIKGLAGAASS------
--------LQDETAYSSTGKQNTS-------------------TNGGSSPVKRRKSAPVR
L--------------------------------------------------VKSGEEGDE
CVTMDADPSPNT------------------------------------------------
-----D--DSQP-------------------------ATDATN-----------------
---PPSNDPHVIKSELMS-------------YDHSQDMKQDEECSG-LEEEDES------
-----------------ENGCSVDGLGG--------SGLEDKGSFYLGQVKPPQT-----
--------------FSQ---------PDSQSQLCSLSQSPQNSSNAQLINSTGEMNSSS-
QF------------------------------------------------------PTTP
PN------------------QVLPENVSASGERNG----RR--------PCPL-------
-----CTKVISNKS------NLLKHMRIRHSDAYNPACCVLCNKIFKN------------
-----------KYSLRAHLNIYHK------EYINPGTAGGGGAQG---TQPVTNQQTTQN
MVTSPGPNGPQSM-------AQAQQTMVQAQSQIQANQQQ----QQQVTAMTMQQVANTA
TLA--------------PQLHLQAPPPYQALIHSPQQTNA--------------------
-----------FCIKAE----------------------------------------GTH
TTQLDLLS----------------------------------------------------
----------PY-IK
>N_lug1 XP_022185576.1 broad-complex core protein isoforms 1/2/3/4/5-like [Nilaparvata lugens]
MGSGGAG---------------------EQQF-------CLRWHNYQSSLLATL-PLLLD
G----DDLTDVTLCAGGKSLKAHRVVLSACSQYFKDLFKVTSGPAMGSGGAGEQQFCLRW
HNYQSSLLATLPLLLDGDDLTDVTLCAG-GKSLKAHRVVLSACSQYFKDLFKEMQP-LQH
PVIVV-PGAEFNDLCALVTFMYSGEVNIYQHQLSSLLTMADTLHIRGLAEFTAN-PSFLN
S-----SVGDQRKSSAAEPANNQP------------------------------------
---------------------------------------------RSKRAKMMTSATEDL
LLFPAATTKPPSSSSSSS------------------LLLHHSSHHHKPKT----------
---------HKP------------------------------------------------
-AVKPDPEIIASYWDTFG-------------QHMAEDLSQRV------------------
-----------------NSSGGGSGLVGVDEGLLLSSADLLMSQQEKQHQQVKQE-----
----------------------------------QQEQDGASPTTPPGPPSTTP------
-------------PDNNNTYTQP----------------TDLTQGNSMEPKLRGS-QNSG
PG--------------------------AGGGSKL-----YA-------TCFV-------
-----CGKQLSNQY------NLRVHMETHQNAH---YACTVCSHVSRS------------
-----------RDALRKHVSYRH-----------PQTAGGG--------------GDAAN
TNTSAGNRS-----------------------------------RQAATAALQQQ-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------P----
>N_lug3 XP_022205415.1 broad-complex core protein isoforms 1/2/3/4/5-like, partial [Nilaparvata lugens]
------------------------------------------------------------
---------------------------------------VTSGPAMGSGGAGEQQFCLRW
HNYQSSLLATLPLLLDGDDLTDVTLCAG-GKSLKAHRVVLSACSQYFKDLFKEMQP-LQH
PVIVV-PGAEFNDLCALVTFMYSGEVNIYQHQLSSLLTMADTLHIRGLAEFTAN-PSFLN
S-----SVGDQRKSSAAEPANNQP------------------------------------
---------------------------------------------RSKRAKMMTSATEDL
LLFPAATTKPP-SSSSSS------------------LLLHHSSHHHKPKT----------
---------HKP------------------------------------------------
-AVKPDPEIIASYWDTFG-------------QHMAEDLSQRV------------------
-----------------NSSGGGSGLVGVDE-----------------------------
------------------------------------------------------------
--------------------------------------------GNSMEPKLRGS-QNSG
PG--------------------------AGGGSKL-----YA-------TCFV-------
-----CGKQLSNQY------NLRVHMETHQNAH---YACTVCSHVSRS------------
-----------RDALRKHVSYRH-----------PQTAGGG--------------GDAAN
TNTSAGNRS-----------------------------------RQAATAALQQQ-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------P----
>C_hook2 maker-scaffold325-size972641-augustus-gene-7.10-mRNA-1
L-----------------------------------------------------------
--------------------YEISCVLA-------------NTFQSTLGMESQQQFCLKW
NSFGSNLATAFGNLFKSESLTDVILFCE-GVTFKAHRLILAACSKHFQDLFER-APLCPS
VLVIL-DGTSSSNMSALLEFMYKGEVHVSQESLSSFLKAAECLQVKGLSIEHEK------
-----LAVVQGAGSVSHDAQ---------------------------LDSPTGRKQAKI-
---------------------------------------------TSSGNGIKKEMPDGG
GSSSSSSVPESMLHPST-SGSSYTPIISPYMHPPHYRPAYEQRIPASAPHY---------
--------DTAPRKRHHRSL--------------SEAMPDAAMRA-S-------VLRDGS
KTLPPSEAEKL------------------SPMALSYRPQHPEA---ESQPEDKV------
----YG-AHLSRYDGGQDSAAASAATSV-----TYDRTAAVDAENNTKVSLESRH-----
------------------------------------------------------------
--------------------------------------------------------SSAD
PG----NSCKKL-------------------------------------QCPF-------
-----CERLYGYET------NLRAHIRQRHQGIR--VPCPFCSRTFTR------------
-----------NNTVRRHIAREHK------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------EEYSMKAFQQPQVH--------------------------NH
NHQ---------------------------------------------------------
---------------
>M_ext1 Medex_00080928-RA
------------------------------------------------------------
-----------------------------------------NTFQSTLGMESQQQFCLKW
NSFGSNLATAFGNLFKSESLTDVILFCE-GVTFKAHRLILAACSKHFQDLFER-APLCPS
VLVIL-DGTSSSNMSALLEFMYKGEVHVSQESLSSFLKAAECLQVKGLSIEHEK------
-----LAVVQ--GSVTHDSQ---------------------------LDSPTGRKQAKI-
---------------------------------------------TSSGNGIKKEVPDGG
GSSSSSSVPEPMIHPSTSSGSTYTPVISPYMHPPHYRPAYEQRIPASAPHY---------
--------DTAPRKRHHRSL--------------SEAVPDASMRA-S-------VLRDGS
KARPPSESEKL------------------SPMALSYRPLHPEA---ESQSEDKV------
----YG-AHMSRYDGGQDSAAAGAATSV-----TYDRTAAVDAENNTKVSMESRH-----
------------------------------------------------------------
--------------------------------------------------------SSAD
PG----NSCPE-------------------------------------------------
----------DLRV------NMELSTRQDEMHAN--MSVPYSEKS---------------
------------------------------------------------------------
------------------------------------------------------------
-----------------PENTPEIIPTN--------------------------------
---------AWNCGG---SGVKMSPLKGGGVQ--------------------------TQ
DGKYYV------------------------------------------------------
---------------
