>A_pis1 XP_008182895.1 homeotic protein ultrabithorax isoform X1 [Acyrthosiphon pisum]
-MNSY-FEQS--GFY------------------------GGHHHHQSSSA-----HHHDQ
N--AVAAAYR-----------------------------------FPIGLGMSPYA----
-------------------------SSQHHHHHGL---------SQSRAPQDSPYDASVA
AAACKLYGSSGGG----------------------GGGGGVGGGGGGG------------
----------------GGGGSGGGGGDQSSAAAVAAAGLNYTK-TEPCVGKSDAAAAAHQ
NGY-----ASSPKDVVWPGNAASAAANGSL------LRPNVCTPESRVG-----------
------------------YGSGNSVSGLDGAGASPNSARNSAGSL---------SASWN-
TCTGIN-NNGHQQQALQLNQ-------Q-QNNHTFYPWMAIAGQS---------------
----------------------------LGANGL-RRRGRQTYTRYQTLELEKEFHTNHY
LTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQEKQAQAQK-------A
AVLAAAQAAGDR------------------------------------------------
-------------------------------------------------
>F_exs1 XP_029663374.1 homeotic protein ultrabithorax-like [Formica exsecta]
-MNSY-FEQTAGGFY------------------------GSHHHQTGAAS-----QHHDP
A----TAAYRS----------------------------------FPLGLGMSHYA----
-------------------------SAQHHHHASSSLGIHPGGGSNTRPPQDSPYDASV-
ATACKLYSTTPEA-----------------------------------------------
---------------------------------TGHTTSSYSTTATKDCKQQDQ-TSTHQ
NGYAAVMAAAAVKDVWQSATSGANSQSNSV------VRPSACTPESTRV-----------
------------------SSYGGLVGGDPASSPG---NNSSSRSL---------TSSWN-
TCSLNS-SASQ-PVATQLHQ-------QPTANHTFYPWMAIA------------------
-----------------------------GANGM-RRRGRQTYTRYQTLELEKEFHTNHY
LTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQEKQAQAQK-------A
AAAAAVVHQQQGAGGGPEG-----------------------------------------
-----------------------------------------------AN
>N_lug1 XP_022206854.1 homeotic protein ultrabithorax-like [Nilaparvata lugens]
MMNSY-FEQS--GFY------------------------GGHHHQTAGAA---TGHHHDQ
T--PAAAAYR-----------------------------------FPLGLGMSPYA----
-------------------------SSQHHHHHSL---------HQSRPPQDSPYDASV-
AAACKLYSSSNDT-----------------------------------------------
---------------------------------GQQSSINYSTSSKPDCNKSE---SAHQ
NGYAAAV--AAVKDVWQSATTGGSANSSSL-VG--PVRPAACTPDSRY------------
------------------ASSVGLVGGDPASSPG--ATGGGRTSS---------ASSWN-
TCSLGS-SASQPTVATQLHQ-------Q-PSNHTFYPWMAIA------------------
-----------------------------GANGM-RRRGRQTYTRYQTLELEKEFHTNHY
LTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQEKQAQAAK-------A
AALAASQAQQQADH----------------------------------------------
-------------------------------------------------
>N_lug2 XP_022183795.1 homeotic protein ultrabithorax-like, partial [Nilaparvata lugens]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------VA------------------
-----------------------------GANGM-RRRGRQTYTRYQTLELEKEFHTNHY
LTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQEKQAQAAK-------A
AALAASQAQQQADH----------------------------------------------
-------------------------------------------------
>C_lec1 CLEC025236-PA
-MNSY-FEQT--GFY------------------------GSHHHQSSTAA-----HHHDQ
T----AAAYR-----------------------------------FPLGLGMSPYA----
-------------------------SSQHHHHHSL---------HQSRPPQDSPYDASV-
AAACKLYSATND------------------------------------------------
----------------------------------NQTSVNYST-TKPDCSKTE---GGHQ
NGYAAVV-AAAAKDVWQSASAGSTPSANPL------VRPSACTPDSRY------------
------------------PGLTEAAGGSPGSA-----SRTSASSL---------APSWN-
QCSINT-ASSQAPVGTQIHQ-------Q-AGNHTFYPWMAIA------------------
-----------------------------GANGL-RRRGRQTYTRYQTLELEKEFHTNHY
LTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQEKQAQAQK-------A
AAAAALAAQQQQDH----------------------------------------------
-------------------------------------------------
>C_lec5 XP_014240207.1 homeotic protein ultrabithorax isoform X1 [Cimex lectularius]
-MNSY-FEQT--GFY------------------------GSHHHQSSTAA-----HHHDQ
T----AAAYR-----------------------------------FPLGLGMSPYA----
-------------------------SSQHHHHHSL---------HQSRPPQDSPYDASV-
AAACKLYSATND------------------------------------------------
----------------------------------NQTSVNYST-TKPDCSKTE---GGHQ
NGYAAVV-AAAAKDVWQSASAGSTPSANPL------VRPSACTPDSRY------------
------------------PGLTEAAGGSPGSA-----SRTSASSL---------APSWN-
QCSINT-ASSQAPVGTQIHQ-------Q-AGNHTFYPWMAIAVS----------------
-----------------------------GANGL-RRRGRQTYTRYQTLELEKEFHTNHY
LTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQEKQAQAQK-------A
AAAAALAAQQQQDH----------------------------------------------
-------------------------------------------------
>D_mel1 FBpp0082793 FBgn0003944 Ubx [Drosophila melanogaster]
-MNSY-FEQA-SGFY-------------------------GHPHQATGMAMG-SGGHHDQ
TASAAAAAYRG----------------------------------FPLSLGMSPYA----
-----------------------------NHH-------------LQRTTQDSPYDASIT
AACNKIYGDGAGAYKQDCLNIKADAVNGYKDIWNTGGSNGGGGGGGGG------------
----------------GGGGAGGTGG----------------------AGNANGGNAANA
NG-------------------QNNPAGGMP------VRPSACTPDSRVGGY---LDTSGG
SPVSHRG---------GSAGGNVSVSGGNGNAGGVQSGVGVAGA----------GTAWNA
NCTISG-AAAQTAAASSLHQ---------ASNHTFYPWMAIAGECPEDPTKSKIRSDLTQ
YGGISTDMG-KRYSESLAGSL---LPDWLGTNGL-RRRGRQTYTRYQTLELEKEFHTNHY
LTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQEKQAQAQK-------A
AAAAAAAAAVQGGHLDQ-------------------------------------------
-------------------------------------------------
>M_ext2 Ubx-PA--to--M_extradentata_PNEQ01076519.1_1_Ubx-PA_FBpp0082793_FBgn0003944_Ultrabithorax
-MRVY-YDRT-SSFYPT--------------------PTNSAYRSEGVVT-----YHQPW
GSNSPSAISR-----------------------------------FPLYSGVAPFQ----
------------------------------HHVTL----------HQRRPQ---FSKRKP
HNCHAVFSQTTRVYETFCVTCDCDIIVSFRNMWSTRLARATAGGGGGG------------
----------------GGGGVPDPNAEKPPLLFTASSHLS--------------------
---------------------QLPPNSYQP------VNMIHCDRPRRPGLF---RQTRGR
LLLRSTE---------GNSDGIFYELLPHNTPSALMYGEGRKSY----------ASVRGS
PMRVPI-GNVAPSCPPSVWN---------LGLSSVFTWYAYIGLCYSDPLKKIIRSPLKL
YGR---RLM-SRSKNVFGGNLALYFSSWPGANGL-RRRGRQTYTRYQTLELEKEFHTNHY
LTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQEKQAQAQK-------A
AAAAAAAAAAQQQQAE--------------------------------------------
-------------------------------------------------
>D_sim1 FBpp0314200 FBgn0191744 Ubx [Drosophila simulans]
-MSKF-VFDSMLPKYPQFQPFISSHHLTTTPPNSSSAAVAAALAAAAASAS--ASVSASS
SNNNSSNTIAGSNTSNTNNSSSSPSSSSNNNSNLNLSGGSLSPSHLSQHLGQSPHSPVSS
SSPFQQHHPQVQQQHLNHQQQQHLHHQQQHHHQYSSL------SAALQLQQQQHHISKLA
AAAVASHGHA------------------HQQLLLTPPSAGNSQAGDSSCSPSPSASGSSS
LH---------RSLNDNSPGSASASASASAASSVAAAA---------------AAAAAAA
SSSF--AIP-TSKMYPYVSNHPSSHGGLSGMAGFTGLEDKSCSRYTD-------------
----------------TVMNSYQSMSVPASASAQFAQFYQHATAAASA-----VSAASAG
AIGVDSLGNACTQPASGVMPGAGGAGGAGIADLPRYPWMTLT------------------
------DWMGSPFERVVCGDF-------NGPNGCPRRRGRQTYTRFQTLELEKEFHFNHY
LTRRRRIEIAHALCLTERQIKIWFQNRRMKLKKELRAVKEINEQARRDREEQEKMKAQET
MKSAQQNKQVQQQQQQQQQQQQQQQQQHQQQQQQPQDHHSIIAHNPGHLHHSVVGQNDLK
LGLGMGVGVGVGGIGPGIGGGLGGNLGMMSALDKSNHDLLK-AVSKVNS
>G_bue1 GBUE021017-PA
-MSKF-IIDSMLPKYHQ-----QYQP----------QMLPGGLSSSGTASTEQTSYSTTS
SSGSASSGTAG------------------------------------LSCNSPPPPPV--
-----RMYPYV--------------HGPQ-------------------------------
TPALP-------------------------------------------------------
---------------------FGAPSMTAFSSMAAVVD------------------AADK
SCRY--NASSAESMAGYSLHHQNG------------------------------------
----------------------VSVSAASASMAAAAQFYHQAAAASAA------------
---TDPLTSCATQVASASSQ--------PMPDIPRYPWMSIT------------------
------DWM-SPFDRVVCGML-------PGPNGCPRRRGRQTYTRFQTLELEKEFHFNHY
LTRRRRIEIAHALCLTERQIKIWFQNRRMKLKKELRAVKEINEQARREREEQERLSKEKQ
GKL--DVGGVDPHKIMS-------LEKNSVA-----------------------------
-------------------------------------DMIKPTVGKVQT
>C_lec2 CLEC025113-PA
-MSKF-IIDSMLPKYHQ-----QYHH----------QLLNPVITSGSDSSA--VNYSSTA
TNNSSSSS------------------------------------------NSPPPSLVSS
AS---RMYPYVAAHH---------HHGQQ-------------------------------
AAGLAAFAGA--------------------------------------------------
-----------------APGGMGAFSSPSSAALAAVVD---------------AATGGDK
SCRYTGNVPTADSMVNYSLHHQNS------------------------------------
--------------------TSSSVSAASASMAAAAQFYHQAAAASA-------------
----DPLSSCTTQVASAATG-------QPMPDIPRYPWMSIT------------------
------DWM-SPFDRVVCGML-------PGPNGCPRRRGRQTYTRFQTLELEKEFHFNHY
LTRRRRIEIAHALCLTERQIKIWFQNRRMKLKKELRAVKEINEQARREREEQDRMNKEKQ
AKIGSESGGGQHHQIHDPHKMMGGLDKSSGQ-----------------------------
-------------------------------------DLLKAVVTKVPT
>C_hook4 Ubx-PA--to--C_hookeri_NQII01000662.1_1_Ubx-PA_FBpp0082793_FBgn0003944_Ultrabithorax
-KNHF-FQQG-KRFYSI--------------------CRAPTIMGNGEKA------SQTE
ITTFTKTCFHG----------------------------------FPLPLSVTQFS----
------------------------------------------ARALPRVTPGEAYCQPIN
ALKXXIFGIGMGLFKSSPVVLTEGLSVGYKNIWQ------DGGGLGGG------------
----------------GGEGASSEGKDQAPKIIALSDS----------SRRARAPGSGGI
NKPA-------------------------------GVPPDVIKDPSWRGGF---AEVPAS
EPVSIPG---------GVAPEFSHVGVVPDSAAGRRVFLGISRL----------LTTWNL
RCTSDG-SRNVSARSCTIRN---------SSRHASPHWLLVPAACTENVQPESISVSLLK
YVQLEAGIS-RRFNSLTAQKL---IRGW-RPNGCPRRRGRQTYTRFQTLELEKEFHFNRY
LTRRRRIEIAHALCLTERQIKIWFQNRRMKLKKELRAVKEINEQARREREEQ--------
------------------------------------------------------------
-------------------------------------------------
>C_lec3 CLEC025066-PA
-MSSY-FANSYMPDLRN-------------------------------------------
----------G---------------------------------------GVVPAE----
------------------------HPHQQHHY---------GAAVVPQGTEDPTACDPRQ
GIPPHHY----------------------------GGPPAAGQPPQGM--PYPRFPPYDR
MDIRAAGYYQNMDYRADSPGAMGHMGQNGHQTPVVYA-----------SCKLQAAVGNGI
GGP-------ESPPEMDMSHHAHP-----------------------------------H
QQQHHMG-----------PHQHQQAPPPPPNQAHMMYNSQQPTQAPHHPQQQVVQQPPPN
QPNQNNNNNNT------------------NLPSPLYPWMR--------------------
----------SQFE---------------------RKRGRQTYTRYQTLELEKEFHFNRY
LTRRRRIEIAHALCLTERQIKIWFQNRRMKWKKENKTKGDLVTNEGSDLSPQ-------T
SPQ---------------------------------------------------------
-------------------------------------------------
>C_lec4 CLEC025152-PA
-MSSYQFVNSLASCYQQ---------------------------QGGQRS----------
--------------------------------------------------GASPVD--HP
QSPAGDYYPNVNYPAGCY--------------------------------------SPQQ
YPAQYMQQSPGGMMDYTQL--------------------------------------HSA
QHQRLASHLQPL-HGVPSPGAVSPILNNNNPSVTNLSG---ST-----SCKFADSTTSGA
NGI-------SSPQDLTTSSAPGG--RTSPPLG--KTSLHSPSNPTSRTPT---APLPTS
QSSSSPA---------SSTSSSSSTPGAPGAGGG--------------------------
-------NGTSGSAGGKPTP---------GNPPQIYPWMKRVHL----------------
------------------------GQSTVNANGE-TKRQRTSYTRYQTLELEKEFHFNRY
LTRRRRIEIAHALCLTERQIKIWFQNRRMKWKKEHKMASMNVIPYHYHMSQP--------
------------------------------------------YGNPY-------------
------------------------------------------QFTHLTT
>C_hook1 Ubx-PA--to--C_hookeri_NQII01001419.1_1_Ubx-PA_FBpp0082793_FBgn0003944_Ultrabithorax
------SPDS----------------------------------RGGRRA----------
-----------------------------------------------------PGPQRH-
RCPL--------------------KRSQKHFSYEAYLSVPVFIGRVAQCRPAYAYTSKIV
ASCNRIHTNSGNFFKRESRSITAGAAPGLSHXWSGGGHRGVGGICGGR------------
------------------------------------------------KEGLVGVGNGDV
NMTG------ANKDDDDGADPPGPP---------EDLQPALRRLPGRRRGR---------
-GRSREA-----------SRRHTSSSSTVRRLLRGGRGGSPPGLQPERARGE--GVARPG
SGRRGP-GGVHEVGGRWSHP---------TGRPFFYPWMKTVVVCPVRSRSFSCRSDVED
LMFWRIPLF-SRYTRELVVCE---NPNFIGAPEK-HKRTRQSYTRFQTLELEKEFHFNRY
LTRRRRVEIAHALGLTERQIKIWFQNRRMKWKKKHYQLGRPVDAEAVEAAAA-------S
ASVSGGVGG---------------------------------------------------
-------------------------------------------------
>M_ext1 Ubx-PA--to--M_extradentata_PNEQ01018149.1_1_Ubx-PA_FBpp0082793_FBgn0003944_Ultrabithorax
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------SPTK
VSANKIFFRDDGAMGEVQIDVEGQNGLPTKVIWRCNETSAGGEGGPGG------------
----------------DRGSANSFLS----------------------LGRHVSLARTRL
QGKA------SPPRSSDTNTSPSP------------PRGTTINFPGKRLVT---AGDGRA
GGTHRHASAERNGFESGVVVGYVSVDLAPEA--------------------------WYV
SCSRGD-TAPDEPVNIALVL---------ISCHLWYRWLGINQVAAEDRHKGRVRQLVIH
VVGSSKLLS-ADFCFRFQGPR---LAQWLGMQEK-HKRTRQSYSRFQTLELEKEFHYNRY
LTRKRRIEIAHALGLTERQIKIWFQNRRMKWKKKHYQVGHDVQEAARGAVSN--------
------VPGADEDDA---------------------------------------------
-------------------------------------------------
>C_hook2 Ubx-PA--to--C_hookeri_NQII01000427.1_1_Ubx-PA_FBpp0082793_FBgn0003944_Ultrabithorax
--------------------------------------FNGRGGSGGVVARALASHHSDS
GS---------------------------------------------IPGGFTPGFS---
------------------------HRVQRGTYRNPSLDIP---------ADDATYPAAAT
VKCTHIYXALEGNYQRQCYVLQSRVVQSEKQLWRTGGDEESGGGGVTC------------
----------------DSDGAVGDVG----------------------AGVKEAGNASKT
NRV-------QSPTESLPGMWESC--RMMPLVG--GFSRGSPASPPPHSGIHAGGQEEVT
QSNSHRS-------------LLTSAPALFPSGAARV------------------------
GCTAGG-NQTHSIRKHSLFK---------NCAQVLYSWKKMFETCRYTPVTFSITNTLQA
YSRYKSPLP-KRLREGLGTGL---VSDWLRKHCR-RRKARTVFSDHQLTGLEKRFEAQRY
LSTPERVELANALHLSETQVKTWFQNRRMKHKKQLRKMNECSDDAMDSRPDT-------G
GVAETGGAAVRDEH----------------------------------------------
-------------------------------------------------
>C_hook3 Ubx-PA--to--C_hookeri_NQII01000093.1_1_Ubx-PA_FBpp0082793_FBgn0003944_Ultrabithorax
-MNKY-IEAA--------------------------GTYLGHPTHQTSTAGTTTTQHVQP
SRADEAGNVND-----------------------------------PLPLAATPTP----
------------------------------------------SNQLNQTTREKNYNILRH
SKCQNLFNMAGAFFKRDCITLYSNSSPSGEDDWPAGGLGGGGGGGGGG------------
----------------GGGGGGGGGG----------------------GGGGGGGGGGGG
EGD-------IIPDVTFGAYKACCGNLDIPPF----------------------LNDSVH
HGTGFRG---------SSSRLSVSLPEIPGLGGGAASNTVGTGY----------RGVWNP
NSPSVG-GAAQPPARCSLHD---------SQDSHYFQWLELKISCGGEPGQNSVVSKITM
YGGLNVDVQ-RQYSTRMAQEL---IPAWFSSSLL-KPRGQEEFNAYHGEGLSTPFDLSAF
LSRKRRIQGTHSMCLVKKQLKVWFKHIRMILQRVVSAVVRMIPQRVAGVAIR-------T
ILQRVASAAVR-------------------------------------------------
-------------------------------------------------
