>A_pis1 XP_029347438.1 ecdysone-induced protein 74EF isoform X1 [Acyrthosiphon pisum]
----------------------MPFMDDVLLWCPEA------------------------
--ETKI---DDFTECLGNEVSSLGELLQ--SEISSELDNAL-DGGGSS------------
--------------------------VQDGGEHSGDDDIFKQLSDSSALLEQFF-DFVNC
DIK---EENNNNVMST--------------------------------------------
--------------------------------------------GNKNHAA---------
-----------VALLQELQRTN-AGKKFNITTANPLLA-----EKLLNPVSQLN------
-PSLNQNSDMFINQ--NKYIKTEPSINDIGKQT---------------------------
----------------VRPTSPPPTTT--TVGNEKDENIDF---------LDHLRIA---
---------------GNGGVGNPGAADHLPPRQQLSFALP--------------------
-HGFHHAGSLPPSPADSGVSDVDSSSS-GHTSTDT--ELRARLQ----------------
---------------------------------------PHQYHHQVSSCGRR-------
---------------TSPDP----------------PSNVQC------------------
------------------HQQQQQQQQQQQQQQQQ---------------------QQQQ
QQQQQQQDLFSRIYGVNAPPPGAYHHPSPASPSPKHPLFMRNNHP-YGGGVAGYHPSTVG
GYGPAVSPTSD-GHFAMPPCPPVAALPGAGT-VIGRGSVIQAAAANCYQPNGAGAANLND
LYYMDF-GAPTAAAAMYHQKTVGNKSGNNK-KPKKYGTVGRPSVAGSPGAVQQQTCPATG
PKRKSRE--GSTTYLWEFLLKLLQNSDYCPRFIKWLNREKGVFKLVDSKAVSKLWGEHKN
KPDMNYETMGRALRYYYQRGILAKVDGQRLVYQFVDVPK----DIVEIDCSGA
>G_bue1 GBUE008361-PA
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--GGGGYYTAG------------SGSPPR-------ASVIQAAASSSH----------DD
LYLLEL-GF------------------NNR-IKKK---LKRPK-TGDAT-----QCQGQG
PKRKSRE--GSTTYLWEFLLKLLQDREYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKN
KPDMNYETMGRALRYYYQRGILAKVDGQRLVYQFVDVPK----DIVEIDCTSA
>C_lec1 CLEC009111-PA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------LGSHLE-DPRTTPTHSENILSP
NIYKAES------------DSL-ETK------PLAQDYPPHYF-----------------
----------------QFLT----------------------------------------
------------------------------------------------------------
-----------------------------------------DGYGGAGGGGGGGGGGGGG
GGGGGGAATGYMGPPQNYFAPPQAPSPPR-------ASVIQAAASSSH----------DD
LSIFDL-GF------------------QHR-MKKK---VKRAR-SGESP-------TATG
PKRKSRE--GSTTYLWEFLLKLLQDRDYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKN
KPDMNYETMGRALRYYYQRGILAKVDGQRLVYQFVDVPK----DIVEIDCSGA
>C_lec3 XP_014251487.1 ecdysone-induced protein 74EF isoform X1 [Cimex lectularius]
----------------------MPFIDDDLLWCPDA------------------------
--DNKM---VDLSQCLD---TGGGL-----GELTQTDLTGL-VGT---------------
--------------------------------IDEEEDIFKSFE-----LEQFF-DFNN-
----EEREENNNVGATNKNQTL--------------------------------------
------------------------------------------------------------
------------AFLQELQRNQANARKFNIAAANPLLAGPYFIEKLAAPGPVT-------
--TSTPTVGSSAEP--FLRIKTEP---DTRQGTLNGSNHYKAEGMGNCRFKIPQKPGENH
FVGVDGQQMRRP----VDTAVAPTVGGVGYVKREPQDHKAL---------LHGILSHQPH
AAAL------------------------------------------------------LA
SYTASNTGSLPPSPADSGVSDVDSSSS-GHTSNDE---LRARLQPPPHTYYQHTTATSCR
RSPEAAT------------PSMGGLY------PTAHFLSPYYHQPQPYP-----------
---------------NRTLT----------------------------------------
------------------------------------------------------------
-----------------------------------------DGYGGAGGGGGGGGGGGGG
GGGGGGAATGYMGPPQNYFAPPQAPSPPR-------ASVIQAAASSSH----------DD
LSIFDL-GF------------------QHR-MKKK---VKRAR-SGESP-------TATG
PKRKSRE--GSTTYLWEFLLKLLQDRDYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKN
KPDMNYETMGRALRYYYQRGILAKVDGQRLVYQFVDVPK----DIVEIDCSGA
>F_exs1 XP_029678074.1 ecdysone-induced protein 74EF isoform X1 [Formica exsecta]
MPVPVSQTPTLTSTLVPKEESNMPFIDDELFWYSDN------------------------
--DGKM----DLTQCLQQSNTGQS------VEFSPMELSAL-VGTPAAP-----------
-----------------------NVPAEEGAGMSTGEELFDPL------------DFLR-
----ELEAEASQPTSTTTPSSY--------------------------------------
------------------------------------------------------------
-----------------------RRQRHNIAAANPLLA-----EKLAAPSTQTS------
-PTSIPYASRAEIK--TENIKPEPSIVDTREVQ-------------------PHDTGEKE
QLGLA------------------------SVKVEPGSTSATTTSSTGTRLLHGILSQHPQ
QHSLGLQNGY--GRHLTGHAQMGQPPY------------------------------TTA
ATSTPGSGSLPASPADSGVSDVESSTS-SGGNEDANLLLKARLNPNS--SLQPGLASHHS
HLSSAAL-------------GRSACHSPGVYPSTATFLPPSYHPHQHHPSQYH---PHRG
SSPHHQHSN--HTMGSTMGP----------------------------------------
------------------------------------PHHHHHHHQTQSLQ------HLHY
RQ-----------------PPSLS-----------------ESYNNYVNSMYGGGG----
-----------------QFATPCTPSPPRGP-GGVPTSVIQAATSSVS----------DD
LYLLEL-GF------------------PPRSKKSK---LKKPR-QGEGG--------GAA
VKRKSRE--GSTTYLWEFLLKLLQDREYCPRYIKWTNRERGVFKLVDSKAVSRLWGLHKN
KPDMNYETMGRALRYYYQRGILAKVDGQRLVYQFVEVPK----DIVEIDCTGA
>N_lug1 XP_022185398.1 ecdysone-induced protein 74EF [Nilaparvata lugens]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------NPLDG-----HCHLPEDAMEA------
-PLDLSVAATSVK---LEYLTDDSDDSDSHGG--------------------PNCKAYKK
SL------IKRY----LDTTAPAPL----YIKREPGEHKGL-------QGLPGILSHHPH
AALL--------------------------------------------------------
NYNASNTGSLPPSPADSGVSDVDSSSS-GHTSNDE---LRSRLNPQP-----PHQVTSCR
RSPDSAG-------------GLYTPHFLAPYPTYTAASAPAPAPMRPHP-----------
-PPHPHYTN--HTHGRTNLS----------------------------------------
------------------------------------------------------------
-----------------------------------------DGYASYMAALGGAPQTGVA
GGA--------------YFP---APSPPRLPGSGVPTPVIQAAASSSSTSPA-----ADD
FYLLEM-GF------------------QRK-LKKQ----KRIRVAGDAM-------PGQG
AKRKSRE--GSTTYLWEFLLKLLQNREYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKN
KPDMNYETMGRALRYYYQRGILAKVDGQRLVYQFVDVPK----DIVEIDCSGA
>C_hook2 maker-scaffold212-size1131905-augustus-gene-1.5-mRNA-1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------AVTTGMLV----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------VGAVLA---------------A
RTPESPG------------PGHPQQHSGYGVPPHGGFLTPFYHPHQPAR-----------
VPPHHYV-------GRQPLG----------------------------------------
---------------------------DGYGGYLQPSHQANLYHQHQQ------------
------------------------------------------------------------
-----------------HFAAPPAPSPSR---PAIPTSVIQAATSSVG---------PDD
LYMLEL-GF------------------QPRPVKKK---LKKSK-SGEPG----------A
VKRKSRE-----------------DRDYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKN
KPDMNYETMGRALRYYYQRGILAKVDGQRLVYQFVDVPK----DIVEIDCTGA
>M_ext3 Eip74EF-PA--to--M_extradentata_PNEQ01093675.1_Eip74EF-PA_FBpp0074965_FBgn0000567_Ecdysone-induced
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----AEESEAVHICLEARCSEL--------------------------------------
-----------------------CFCMERV------KERELREDGRKARGTQLIAASTSL
PTCRLCGTRLLYTVLPASIHTA-HKKMVTQLTSIHFLI-----RHLKKNTLSLVMYLHGV
GDTIFPVTSHNMDGS------------PGKEK--------------------PFLFPFRH
PR------LARFHCGNKDTGAP-------PIKREPGDHKPL---------LHGILSQHHH
QHHHQVHPGL-----LTAHRTSAYTTH----SSTGSIRPHRRRLGRCLLRPGPQCRELRK
NYSVFKAGSLPPSPADSGVSDVDSSSS-GHTSNDE---LKARLQPTP------------A
RTPESPG------------PGHPQQHPGYGV-PHGGFLAPFYHPHQPAR-----------
VPPHHYV-------GRQPPAYFETGNEMCQTFSTTTTTTSKSSHYLETDFNDMQIVGHNL
LATRATATARRKG----KHSRQAGRRISGRHGCARGLRAGRVTHPHKKLSLVRRGEIAAG
KQEVLQWTDVDRF------PPPLPRHALGCMPAT-LAHICEYNHSVFIYKSPSTTSLYIC
VAFPALRSDTH-NRPGISDG---APSPTR---PSIPTSVIQAATSSVG---------PDD
LYMLEL-GF------------------QPRPVKKK---LKKPK-SGEPG----------S
VKRKSRE--GSTTYLWEFLLKLLQDRDYCPRYIKWTNREKGVFKLVDSKAVSRLWGLHKN
KPDMNYETMGRALRYYYQRGILAKVDGQRLVYQFVDVPK----DIVEIDCTG-
>D_mel1 NP_730287.1 Ecdysone-induced protein 74EF, isoform A [Drosophila melanogaster]
----------------------MPFIDDALLWCPDN------------------------
--DGRLVGGLDLGTCIADDSTANG---T--ENLNPSIQS---AGNPNNPQQSVGGEILGS
VESAGNELNGAAARN-------VNVVVEPLCGGDSSDELFRSFSESNFEIESLLSDLATV
EVKVENEENNNNVITDDDFASVAAAVVANDDLLAKENAQLSAQGLVDSVAASLADSGDAG
GQQALLAFGSSSSAASAIAAAAAALCGDLINNNNNNSNSNNNSNGNGNHGGGGGGASSGG
GVAGDCATKLEYALMGGQPLAE-EPRFVTSAAANPLLV-----EKLMSKCLNIEKRMDKL
SDTEIPIVKQSTSPAPQQQLQQQHHLQQQQQQQ---------------------------
----------------PHNGSTFAGAT--ALLHIKTEQNTL---------LTPLQLQQQQ
QQQQGLHGAA-----GNGGSSNGNNAH----QQQQPLAIPQRPLLHNLLSGGAIHNPHHR
NYTTATTGSFPPSPADSGVSDVDSSSSGGQPCADE---LKARLGMPP------------A
TSASAAA------------AAAAAAAAAAHL-HTGTFLHPNLYQNNAANSLRNIWNRSVG
VPDNYYGSSGAGSGGTQPGG----------------PGNPQTPGYLTTSYFNAPTAATAA
ASQRGTTINGYHS----LHQQQQQQQQSQQSQQQQQLAHQQLSHQQQQALHQQLSHQQQQ
QQQQQQQHPHSQL---NGPHPHSHPHSHPHS----HPHAGQHTHSTIAAAAAAAAASVVS
SSSSAVAAA------AMLSASAAAAATAAAA-AGGSQSVIQPATSSVS---------YDL
SYMLELGGF------------------QQR-KAKK---PRKPK-------------LEMG
VKRRSRE--GSTTYLWEFLLKLLQDREYCPRFIKWTNREKGVFKLVDSKAVSRLWGMHKN
KPDMNYETMGRALRYYYQRGILAKVDGQRLVYQFVDVPK----DIIEIDCNGV
>D_sim1 FBpp0323369 FBgn0184127 Eip74EF [Drosophila simulans]
----------------------MPFIDDALLWCPDN------------------------
--DGRLVGGLDLGTCIADDSTANG---T--ENLNPSIQS---AGNPNNPQQSVGGEVLVS
VESAGNELNGAAARN-------VNVVVEPLCGGDSSDELFRSFSESNFEIESLLSDLATV
EVKVENEENNNNVITDDDFASVAAAVVANDDLLAKENAQLSAQGLVDSVAASLADSGDAG
GQQALLAFGSSSSAASAIAAAAAALCGDLINN-----NSNNNSNGNGNHVGGGGGAGSGG
GVAGDCATKLEYALMGGQPLAE-EPRFVTSAAANPLLV-----EKLMSKCLNIEKRMDKL
SDTEIPIVKQSTSPAPQQQLQQQHHL-QQQQQQ---------------------------
----------------PHNGSTFAGAT--ALLHIKTEQNAL---------LTPLQLQQQQ
QQQQGLHGAA-----GNGGSSNGNNAH----QQQQPLAIPQRPLLHNLLSGGAIHNPHHR
NYTTATTGSFPPSPADSGVSDVDSSSSGGQPCADE---LKARLGMPP------------A
TSASAAA------------AAAAAAAAAAHL-HTGTFLHPNLYQNNAANSLRNIWNRSVG
VPDNYYGSSGAGSGGTQPGG----------------PGNPQTPGYLTTSYFNAPTAATAA
ASQRGTTINGYHS----LHQQQQQQQQSQQSQQQQQLAHQQLSHQQQQALHQQLSH--QQ
QQQQQQQHPHSQL---NGPHPHSHPHSHPHS----HPHAGQHTHSTIAAAAAAAAASVVS
SSSSAVAAA------AMLSASAAAAATAAAA-AGGSQSVIQPATSSVS---------YDL
SYMLELGGF------------------QQR-KAKK---PRKPK-------------LEMG
VKRRSRE--GSTTYLWEFLLKLLQDREYCPRFIKWTNREKGVFKLVDSKAVSRLWGMHKN
KPDMNYETMGRALRYYYQRGILAKVDGQRLVYQFVDVPK----DIVEIDCNGV
>N_lug2 XP_022207261.1 ecdysone-induced protein 74EF-like [Nilaparvata lugens]
M--------------------EVP----STTWFSEALCT--------------SLYKDSH
SPSSGL---DDESAYISTNYTDLSDACR--NQITHDDSKKFNNNSGES------------
--------------------------MSDTNRNSDSDNGDKNQGDS--------------
-------ENNN-------------------------------------------------
------------------------------------------------------------
-----------YLMLQAKHRLN-HSH----------------------------------
-PTIHSTQEEYIDL--DKLYQSHHRT----------------------------------
----------------LLNSSYSPASS--SHYQHNHQH------------LQH-TINHPH
HHNI-------------------------LAQQLSCLHRQQH------------------
-------------PTDLGIRGQGH----GHPHQGH---PQGRI------------PLQGH
PQGRIPP------------PGHPGSS------SQGHRSSQLHHLHPPAS-----------
-----------------------------VSSSTSPTSLSIPSPHLNSDHN---------
------------------HRRNHLGHHQ---------------HLPQQLP------HAHA
QQTTSALSINSSHHSYNNYPPSVFNGGTGTHP----------------------------
-----------------------VGSQSQGRDGYGQSSAGNEPNDYSS---------YAQ
QQYPNYNEDPDSDSESD----------HQRDIEAQ---PVKKR-PGRPR----------G
SRRKKPE---KLGRLWEFIRDLLLNSETCPSLICWDNYEEGMFRFVHSDKVAKLWGAKRD
NPDMNYEKLSRAMRYYYKSKVLQPVFGRRLVYKFGPEAKGWKTDNPNFRC---
>M_ext1 Eip74EF-PA--to--M_extradentata_PNEQ01062987.1_1_Eip74EF-PA_FBpp0074965_FBgn0000567_Ecdysone-induced
----------------------APL---LLSWLLIE-CVQISLQVIVKVTRTYSCLKYSM
S--------PKENPNFSFQHKPRQEAIQSPQQPANYTGRKRGNACGPD------------
-------------RDTHPPPLPVRAMRIPSARQKMCSAGTPKSGDN--------------
-------PSNN-------------------------------------------------
------------------------------------------------------------
---------------DARALLA-PSR----------------------------------
-----PLVRHLTNG--AKIFSPQNRG-------------YILISFGGNGTR-P-------
----------RF-CT-LWSSVTSPKSGK-GRGSGGGRKTSL-------------PVTSPA
SANSERAPVDPESSRWEGGT--------FIYKIVYCMGRDGE-VRRRWMRDRAIN---GR
KITNRTPGAGVLDPAAPGVKDQPR--------------LAGRTLIFD--------ALKGR
ASKRVAAGEGFFGRDIGLIPGLRGSR------DEAVSNSVPMIMRAARP-----------
-------------------------------RGASQSGIIRQDSHMQKSGD---------
------------------RPRQELNPERLRGR-------RRGAGVARSHS------SEHI
AQTRDGVEVASSGGRVRRVSVCIFQG----------------------------------
----------------RVVACSGASAPAAAESGGGEQALLRKTTKISN---------YCL
VLLSNIPKF------------------HQHSVPHPY------------------QLLNAA
SSRLVAQ-GSGQIQLWQFLLELLADSSN-ASCIAWEG-TNGEFKLTDPDEVARRWGERKS
KPNMNYDKLSRALRYYYDKNIMSKVHGKRYAYKF-------------------
>M_ext2 Eip74EF-PA--to--M_extradentata_PNEQ01084081.1_1_Eip74EF-PA_FBpp0074965_FBgn0000567_Ecdysone-induced
P--------------------NVP------------------------------------
---------------------------Q--QQVTQVITARSNLQQSAT------------
--------------------------FQQQQNIQHSKQVQNLQHQQ--------------
-------QQN--------------------------------------------------
------------------------------------------------------------
--------------LQQQQQNL-QQQ----------------------------------
-QNLHQQQQNLQQQ--QQNLQQQNLQQQNMQQQ---------------------------
-----------------------------NLQQQNLQQQNLQ-----HQNLQQ-QQNLQQ
QQNL---------------------------QQQQNLQQQQNLQQQQNLQQQQMH-----
-SNLATQQNYIPQQTAANISIKTDNTA-GDPSAAT--SAADRFTAVP------------T
TAATASA------------SSASTASSSPVL-CSTAIFPSDLRPCCASVSLSGGW-RGCG
TTSSYPETVATASAATSTAAK-------CSTASAATSTTAKCSAAKCAAAN---------
MQQQQQLLSQQQQLQLQLQQQQQLQQQQLQQQ----LQQQQPQLQQQQLPPQHQQQQLPP
QHQQQQLPPQHQQ---QQLPPHQQQQLPPHQ----QQQLPPQPNAAANAATATNAGTTTS
ATTTTAT----------------AASTAATAASTAATSATTATAASTTAASAATTLLYNL
VFLLTNNKY------------------FKQNVPE----GHKPK---------------LP
SQRHSNDVPSRSGYDWQSVLEFPLNIWYCISFTTFAQEVVGFILLTLPKK----------
------DDVLRVLR---------------------------------------
