>A_pis1 XP_008182895.1 homeotic protein ultrabithorax isoform X1 [Acyrthosiphon pisum]
-MNSY-------------------------------------------------------
-----FEQS---------------------------------------------------
------------------------------------------------------------
-GFYGGHHHHQSSSA---------------------------------------------
---------------------------------------HHHDQN-----AVAAAYR-FP
--------------IGLGMSPYA---------------SSQHHHHHGL------------
--------------SQSRAPQ------DSPYDASVAAAAC-KLYGSSGGG----------
-----------------------------------------GGGGGVGGG-----G----
-------------GGGGGGGSGGGG-----GDQSSAAAVAAAGL----------------
--------------------------------------------------NYTKTEPC--
-------------------------------------------------VGKSDAAAAAH
QNGY-----ASSPKDVVWPGNAASAAANGSL------------------LRPNVCTPES-
RVG---------------------------------------------------------
--------------------------------------YGSGNSVSGLDGAGASPNSARN
SAGSLSASWN-TCTGIN-------NNGHQQQALQLNQQ--------QNNH--TFYPWMAI
AGQS----------------------------------------LGANGL-RRRGRQTYT
RYQTLELEKEFHTNHYLTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQ
EKQAQAQKAAVLAAAQAAGDR---------------------------------------
------------------------------------------------------------
-----
>G_bue1 GBUE021017-PA
-MSKF-------------------------------------------------------
-----IIDSMLPKYHQ--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------QYQPQMLP---------------
--------------GGLSSSGTA---------------STEQTSYSTTSS----------
--------------SGSASSGTAGLSCNSPPPPPV------RMYPYV-------------
-------------------------------------------HGPQTPALP--------
---------------------FGAP-----SMTAFSSMAAVVD-----------------
------------------------------------------------------------
---------------------------------------------------------AAD
KSCR---------------------------------------------Y--NASSAES-
MAG----------------------------------------YSLHHQ-----------
--------------------------------------NGV--SVSAASASMAAAAQFYH
QAAAASAATD------------PLTSCATQVASASSQ--------PMPDI--PRYPWMSI
T------------------------DWM-SPFDRVVCG----MLPGPNGCPRRRGRQTYT
RFQTLELEKEFHFNHYLTRRRRIEIAHALCLTERQIKIWFQNRRMKLKKELRAVKEINEQ
ARREREEQERLSKEKQGKLDVGGV--------DPHKIMS-LEKNSVA-------------
-----------------------------------------------------DMIKPTV
GKVQT
>F_exs1 XP_029663374.1 homeotic protein ultrabithorax-like [Formica exsecta]
-MNSY-------------------------------------------------------
-----FEQTA--------------------------------------------------
------------------------------------------------------------
GGFYGSHHHQTGAAS---------------------------------------------
---------------------------------------QHHDPA-------TAAYRSFP
--------------LGLGMSHYA---------------SAQHHHHASSSLG---------
--------IHPGGGSNTRPPQ------DSPYDASV-ATAC-KLYSTT-------------
------------------------------------------------------------
---------------------------------PEATGHTTSSY----------------
--------------------------------------------------STTATKDC--
--------------------------------------------------KQQD-QTSTH
QNGYAAVMAAAAVKDVWQSATSGANSQSNSV------------------VRPSACTPEST
RV----------------------------------------------------------
--------------------------------------SSYGGLVGGDPASSPG---NNS
SSRSLTSSWN-TCSLNS-------SASQ-PVATQLHQQ-------PTANH--TFYPWMAI
A--------------------------------------------GANGM-RRRGRQTYT
RYQTLELEKEFHTNHYLTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQ
EKQAQAQKAAAAAAVVHQQQGAGG--------GPEG------------------------
------------------------------------------------------------
---AN
>N_lug1 XP_022206854.1 homeotic protein ultrabithorax-like [Nilaparvata lugens]
MMNSY-------------------------------------------------------
-----FEQS---------------------------------------------------
------------------------------------------------------------
-GFYGGHHHQTAGAA---------------------------------------------
-------------------------------------TGHHHDQT-----PAAAAYR-FP
--------------LGLGMSPYA---------------SSQHHHHHSL------------
--------------HQSRPPQ------DSPYDASV-AAAC-KLYSSS-------------
------------------------------------------------------------
---------------------------------NDTGQQSSINY----------------
--------------------------------------------------STSSKPDC--
--------------------------------------------------NKSE---SAH
QNGYAAAV--AAVKDVWQSATTGGSANSSSLVGP---------------VRPAACTPDS-
RY----------------------------------------------------------
--------------------------------------ASSVGLVGGDPASSPG--ATGG
GRTSSASSWN-TCSLGS-------SASQPTVATQLHQQ--------PSNH--TFYPWMAI
A--------------------------------------------GANGM-RRRGRQTYT
RYQTLELEKEFHTNHYLTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQ
EKQAQAAKAAALAASQAQQQADH-------------------------------------
------------------------------------------------------------
-----
>N_lug2 XP_022183795.1 homeotic protein ultrabithorax-like, partial [Nilaparvata lugens]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------V
A--------------------------------------------GANGM-RRRGRQTYT
RYQTLELEKEFHTNHYLTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQ
EKQAQAAKAAALAASQAQQQADH-------------------------------------
------------------------------------------------------------
-----
>C_lec1 CLEC025236-PA
-MNSY-------------------------------------------------------
-----FEQT---------------------------------------------------
------------------------------------------------------------
-GFYGSHHHQSSTAA---------------------------------------------
---------------------------------------HHHDQT-------AAAYR-FP
--------------LGLGMSPYA---------------SSQHHHHHSL------------
--------------HQSRPPQ------DSPYDASV-AAAC-KLYSAT-------------
------------------------------------------------------------
---------------------------------ND--NQTSVNY----------------
--------------------------------------------------STT-KPDC--
--------------------------------------------------SKTE---GGH
QNGYAAVV-AAAAKDVWQSASAGSTPSANPL------------------VRPSACTPDS-
RY----------------------------------------------------------
--------------------------------------PGLTEAAGGSPGSA-----SRT
SASSLAPSWN-QCSINT-------ASSQAPVGTQIHQQ--------AGNH--TFYPWMAI
A--------------------------------------------GANGL-RRRGRQTYT
RYQTLELEKEFHTNHYLTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQ
EKQAQAQKAAAAAALAAQQQQDH-------------------------------------
------------------------------------------------------------
-----
>C_lec2 CLEC025113-PA
-MSKF-------------------------------------------------------
-----IIDSMLPKYHQ--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------QYHHQLLN---------------
--------------PVITSGSDS---------------SA--VNYSSTAT----------
--------------NNSSSSS------NSPPPSLV-SSAS-RMYPYVAAH----------
-----------------------------------------HHHGQQAAGLAA-------
-------------FAGAAPGGMGAF-----SSPSSAALAAVVD-----------------
------------------------------------------------------------
------------------------------------------------------AATGGD
KSCR---------------------------------------------YTGNVPTADS-
MVN----------------------------------------YSLHHQ-----------
--------------------------------------NSTSSSVSAASASMAAAAQFYH
QAAAASA--D------------PLSSCTTQVASAATGQ-------PMPDI--PRYPWMSI
T------------------------DWM-SPFDRVVCG----MLPGPNGCPRRRGRQTYT
RFQTLELEKEFHFNHYLTRRRRIEIAHALCLTERQIKIWFQNRRMKLKKELRAVKEINEQ
ARREREEQDRMNKEKQAKIGSESGGGQHHQIHDPHKMMGGLDKSSGQ-------------
-----------------------------------------------------DLLKAVV
TKVPT
>C_lec3 CLEC025066-PA
-MSSY-------------------------------------------------------
-----FANSYMPDLRN--------------------------------------------
------------------------------------------------------------
GGVVPAEHPH--------------------------------------------------
-------------------------------------QQHHYGAA-----VVPQG-----
-----------------TEDPTA---------------CDPRQGIPPHHY----------
---------------------------GGPPAAGQ-PPQG-MPYPRFPPY----------
-----------------------------------------DRMDIRAAGYYQNMD----
-------------YRADSPGAMGHM-----GQNGHQTPVVYAS-----------------
------------------------------------------------------------
------------------------------------------------------CKLQAA
VGNG-----IGGPESPPEMDMSHHAHPHQQQHHMGPH------------QHQQAPPPPP-
-------------------------------------------NQAHMM-----------
--------------------------------------YNSQQPTQAPHHPQQQVVQQPP
PNQPNQNNNN-----------------------------------NNTNLPSPLYPWMR-
-----------------------------SQFE------------------RKRGRQTYT
RYQTLELEKEFHFNRYLTRRRRIEIAHALCLTERQIKIWFQNRRMKWKKENKTKGDLVTN
EGSDLSPQTS--------------------------------------------------
------------------------------------------------------------
---PQ
>C_lec4 CLEC025152-PA
-MSSYQ------------------------------------------------------
-----FVNSLASCYQQ--------------------------------------------
-------------------------------QGGQR------------------------
SGASPVDHPQ--------------------------------------------------
---------------------------------------------------SPAG-----
-----------------DYYPNV---------------NYPAGCYSPQQY----------
---------------------------PAQYMQQS-PGGM-MDYTQL--H----------
-----------------------------------------SAQHQRLASHLQPL-----
-------------HGVPSPGAVSPI-----LNNNNPSVTNLSG-----------------
------------------------------------------------------------
---------------------------------------------------STSCKFADS
TTSG-----ANGISSPQDLTTS--SAPGGRTSPPLGK-----------------------
-------------------------------------------TSLHSP-----------
--------------------------------------SNPTSRTPTAPLPTSQSSSSPA
SSTSSSSSTP-GAPG---------AGGGNGTSGSAGGK-------PTPGNPPQIYPWMK-
---------------------------------RVHLGQ---STVNANGE-TKRQRTSYT
RYQTLELEKEFHFNRYLTRRRRIEIAHALCLTERQIKIWFQNRRMKWKKEHKMAS-----
----------------------------MNVIPYHYHMSQPYGNPYQ-------------
-----------------------------------------------------------F
THLTT
>C_lec5 XP_014240207.1 homeotic protein ultrabithorax isoform X1 [Cimex lectularius]
-MNSY-------------------------------------------------------
-----FEQT---------------------------------------------------
------------------------------------------------------------
-GFYGSHHHQSSTAA---------------------------------------------
---------------------------------------HHHDQT-------AAAYR-FP
--------------LGLGMSPYA---------------SSQHHHHHSL------------
--------------HQSRPPQ------DSPYDASV-AAAC-KLYSAT-------------
------------------------------------------------------------
---------------------------------ND--NQTSVNY----------------
--------------------------------------------------STT-KPDC--
--------------------------------------------------SKTE---GGH
QNGYAAVV-AAAAKDVWQSASAGSTPSANPL------------------VRPSACTPDS-
RY----------------------------------------------------------
--------------------------------------PGLTEAAGGSPGSA-----SRT
SASSLAPSWN-QCSINT-------ASSQAPVGTQIHQQ--------AGNH--TFYPWMAI
AVS------------------------------------------GANGL-RRRGRQTYT
RYQTLELEKEFHTNHYLTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQ
EKQAQAQKAAAAAALAAQQQQDH-------------------------------------
------------------------------------------------------------
-----
>D_mel1 FBpp0082793 FBgn0003944 Ubx [Drosophila melanogaster]
-MNSY-------------------------------------------------------
-----FEQA---------------------------------------------------
------------------------------------------------------------
SGFYG-HPHQATGMA---------------------------------------------
-----------------------------------MGSGGHHDQTA---SAAAAAYRGFP
--------------LSLGMSPYA---------------NH--------------------
--------------HLQRTTQ------DSPYDASI-TAACNKIYGDGAGAYKQDCLNIKA
DAVNG-------YKDIWN----------------------TGGSNGGGGG-----G----
-------------GGGGGGGAGGTG-----GA----------------------------
------------------------------------------------------------
--------------------------------------------------GNANGGNAAN
ANGQ-------------------NNPAGGMP------------------VRPSACTPDS-
RVGGYLDT--------------------------------SGGSPVSHRGG---------
-------------------------------------SAGGNVSVSGGNGNAGGVQSGVG
VAGAGTA-WNANCTISG-------AAAQTAAASSLHQ---------ASNH--TFYPWMAI
AGECPEDPTKSKIRSDLTQYGGISTD-MGKRYSESLAGSLLPDWLGTNGL-RRRGRQTYT
RYQTLELEKEFHTNHYLTRRRRIEMAHALCLTERQIKIWFQNRRMKLKKEIQAIKELNEQ
EKQAQAQKAAAAAAAAAAVQGGHL------------------------------------
------------------------------------------------------------
---DQ
>D_sim1 FBpp0314200 FBgn0191744 Ubx [Drosophila simulans]
-MSKF-------------------------------------------------------
-----VFDSMLPKYPQFQPF---ISSHHLTTTPPNSSSAAVA-AALAAAAASASASVS--
-------------------ASSSNNNSSNTIAGSNTSNTNNSSSSPSSSSNNNSNLNLSG
GSLSPSHLSQHLGQSPHSPVSSSSPFQQHHPQV--------------QQQHLNHQQQQHL
----------------------------------HHQQQHHHQYS-----SLSAALQ-LQ
QQQ--------HHISKLAAAAVA---------------SHGHAHQQLL------------
--------LTPPSAGNSQAGD------SSCSPSPSASGSS-SLHRSL-------------
------------------------------------------------------------
--------------NDNSPGSASAS-----ASASAASSVAAAA-----------------
------------------------------------------------------------
------------------------------------------------------AAAAAA
ASSS-----FAIPTSKMYPYVSNHPSSHGGLSGMAGFT----------GLEDKSCSRYT-
DTV---------------------------------------------------------
--------------------------------------MNSYQSMSVPASASAQFAQFYQ
HATAAASAVS-AASA-GAIGVDSLGNACTQPASGVMPGAGGAGGAGIADL--PRYPWMTL
T------------------------DWMGSPFERVVCG----DFNGPNGCPRRRGRQTYT
RFQTLELEKEFHFNHYLTRRRRIEIAHALCLTERQIKIWFQNRRMKLKKELRAVKEINEQ
ARRDREEQEKMKAQETMKSAQQNKQVQQQQQQQQQQQQQQQQQHQQQQQQPQDHHSIIAH
NPGHLHHSVVGQNDLKLGLGMGVGVGVGGIGPGIGGGLGGNLGMMSALDKSNHDLLK-AV
SKVNS
>M_ext1 PNEQ01018149.1 M_extradentata Ubx
SPTKVSANKIFFRDDGAMGEVQIDVEGQNGLPTKVIWRCNETSAGGEGGPGGDRSANSFLSLGRHVSLARTRLQGKASPPRSSDTNTSPSPPRGTTINFPGKRLVTAGDGRAGGTHRHASAERNGFESGVVVYVSVDLAPEAWYSCSRGDTAPDEPVNIALVLISCHLWYRWLGIQVAAEDRHKGRVRQLVIHVVGSSKLLSADFCFRFQGPRLAQWLMQEKHKRTRQSYSRFQTLELEKEFHYNRYLTRKRRIEIAHALGLTERQIKIWFQNRRMKWKKKHYQVGHDVQEAARGAVSNVPGADEDDA
>C_hook1 NQII01001419.1 C_hookeri Ubx
SPDSRGGRRAPGPQRHRCPLKRSQKHFSYEAYLSVPVFIGRVAQCRPAYAYTSKIVSCNRIHTNSGNFFKESRSITAGAAPGLSHWSGGHRGVGGICGGRKEGLVGVGNGDVNMTGANKDDDGADPPGPPEDLQPALRRLPGRRRGRGRSREASRRHTSSSSTVRRLLRGGRGGSPPGLQPERARGEGVARPGSGRRGPGGVHEVGGRWSHPTGPFFYPWMKTVVCPVRSRSFSCRSDVEDLMFWRIPLFSRYTRELVVCENPNFIAPEKHKRTRQSYTRFQTLELEKEFHFNRYLTRRRRVEIAHALGLTERQIKIWFQNRRMKWKKKHYQLGRPVDAEAVEAAAASASVSGGVGG
>C_hook2 NQII01000427.1 C_hookeri Ubx
FNGRGGSGGVVARALASHHSDSGSIPGGFTPGFSHRVQRGTYRNPSLDIPADDATYPAAATVKCTHIYALEGNYQRQYVLQSRVVQSEKQLWRTGGDEESGGGGVTCSDGAVGDVGAGVKEAGNASTNRVQSPTESLPGMWESCRMMPLVGGFSRGSPASPPPHSIHAGGQEEVTQSNSHRSLLTSAPALFPSGAARVGCTAGGNQTHSIKHSLFKNCAQVLYSWKKMFETRYTPVTFSITNTLQAYSRYKSPLPKLREGLGTGLVSDWLKHCRRRKARTVFSDHQLTGLEKRFEAQRYLSTPERVELANALHLSETQVKTWFQNRRMKHKKQLRKMNECSDDAMDSRPDTGGVAETGGAAVRDEH