>A_pis1 XP_008182670.1 homeobox protein extradenticle isoform X1 [Acyrthosiphon pisum]
MNSMDEHNRMMHPTS---AML-------PQ---PYG-MSSVDPNHGAPTPPDQ--DTRKQ
-DIGEILQQIMNITDQSLDEAQARKHTLNCHRMKPSLFSVLCEIKEKT------VLSLRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGAGAAASASAAASGGP---GQP
DNAIEHSDYRAKLAQIRQIYHQELEKYEQACNEFTTHV----MNLLREQSRTRPITPKEI
ERMVQIIHKKFSSIQMQLKQSTCEAVMILRSRFLDAR-----------RKRRNFSKQASE
ILNEYFYSHLSNPYPSEEAKEELARKCSITVSQVSNWFGNKRIRYKKNI----GKAQEEA
NLYAAKKA------------------------------------------AGASPYSMGP
-------------------------ASQGTPTPLLSPAPGGG------------------
-PQDSMGYSL-SLNG----AEYSSPMSGSQVCAQYSDGSLG------------YDPMGHQ
AMP---KNSGSP------STGWN-SSHEY--QTHGMHDDSED------------------
--SSDDVDIKRPKLS
>N_lug2 XP_022186095.1 homeobox protein extradenticle-like [Nilaparvata lugens]
---MDEQNRMMHPSG-QVGMM-------PQ--PPYG-MQPVDPNHGAPATPDQ--ETRKQ
-DIGEILQQIMNITDQSLDEAQARKHTLNCHRMKPSLFSVLCEIKEKTGE----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>M_ext1 Medex_00068030-RA
---MDEQSRMMHPVSSQVGMM-------PQ---PYG-MQPVDPNHGAPTTPDQ--ETRKQ
-DIGEILQQIMNITDQSLDEAQARKHTLNCHRMKPALFSVLCEIKEKTDKQGLNVCEFQN
VYILSCADPQILTIRRSADINVFNRPIPEFLVGEVFTFGPTTRLSSSVG-----------
------------------------------------------------------------
--------------------------------FLRA------------------------
---------------------------------VDNFCDN--------------------
--------------------------------------------------LGGSYFELGE
HF----------------------VAAWGT------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>F_exs1 XP_029677537.1 homeobox protein extradenticle isoform X1 [Formica exsecta]
---MDETGNMLQHGGSGVGLMGGNQGQAAQNTAGYGSMGPVDGT--ATQGPDQTVEARKQ
-DIGEILQQIMNITDQSLDEAQARKHTLNCHRMKPALFSVLCEIKEKT------VLSLRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGAGAAASASAAAAAGPP--GQP
DNAIEHSDYRAKLAQIRQIYHQELEKYEQACNEFTTHV----MNLLREQSRTRPITPKEI
ERMVQIIHKKFSSIQMQLKQSTCEAVMILRSRFLDAR-----------RKRRNFSKQASE
ILNEYFYSHLSNPYPSEEAKEELARKCGITVSQVSNWFGNKRIRYKKNI----GKAQEEA
NLYAAKKAAD--------------------LEPRW--RKSHHCKSL-AAFAGASPYSMGG
-------------------------ASQGTPTPMMSPAPPGG------------------
-PQDMAGYSM-GING----SDYGS--------QPYNDGSMG------------YDP-MHQ
GKA---LTGGPG------AAGWM-QQREAVPEFPPLHDSADS------------------
--DSDRENEKRPRV-
>D_mel1 FBpp0073940 FBgn0000611 exd [Drosophila melanogaster]
---MEDPNRMLAHTG---GMM------APQ---GYG-LSGQDDGQNAGS--EN--EVRKQ
KDIGEILQQIMSISEQSLDEAQARKHTLNCHRMKPALFSVLCEIKEKT------VLSIRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGGAAAASAAAASQGGSLSIDGA
DNAIEHSDYRAKLAQIRQIYHQELEKYEQACNEFTTHV----MNLLREQSRTRPITPKEI
ERMVQIIHKKFSSIQMQLKQSTCEAVMILRSRFLDAR-----------RKRRNFSKQASE
ILNEYFYSHLSNPYPSEEAKEELARKCGITVSQVSNWFGNKRIRYKKNI----GKAQEEA
NLYAAKKA------------------------------------------AGASPYSMAG
-------------------------PPSGTTTPMMSPAP---------------------
-PQDSMGYPM-GSGG----YDQ-------Q--QPYDNSMGG------------YDPNLHQ
DLS--------P------------------------------------------------
---------------
>D_sim1 FBpp0215663 FBgn0188823 exd [Drosophila simulans]
---MEDPNRMLAHTG---GMM------APQ---GYG-LSGQDDGQNAGS--EN--EVRKQ
KDIGEILQQIMSISEQSLDEAQARKHTLNCHRMKPALFSVLCEIKEKT------VLSIRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGGAAAASAAAASQGGSLSIDGA
DNAIEHSDYRAKLAQIRQIYHQELEKYEQACNEFTTHV----MNLLREQSRTRPITPKEI
ERMVQIIHKKFSSIQMQLKQSTCEAVMILRSRFLDAR-----------RKRRNFSKQASE
ILNEYFYSHLSNPYPSEEAKEELARKCGITVSQVSNWFGNKRIRYKKNI----GKAQEEA
NLYAAKKA------------------------------------------AGASPYSMAG
-------------------------PPSGTTTPMMSPAP---------------------
-PQDSMGYPM-GSGG----YDQ-------Q--QPYDNSMGG------------YDPNLHQ
DLS--------P------------------------------------------------
---------------
>N_lug1 XP_022201680.1 homeobox protein extradenticle-like [Nilaparvata lugens]
------------------------------------------------------------
--------------------------------MK-------VESVAMA------LLSLRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGAGAAATASAAAAGGP---GQP
DNAIEHSDYRAKLAQIRQIYHQELEKYEQACNEFTTHV----MNLLREQSRTRPITPKEI
ERMVQIIHKKFSSIQMQLKQSTCEAVMILRSRFLDAR-----------RKRRNFSKQASE
ILNEYFYSHLSNPYPSEEAKEELARKCSITVSQVSNWFGNKRIRYKKNI----GKAQEEA
NLYAAKKA------------------------------------------AGASPYSMGP
-------------------------ASQGTATPMMSPAPPGSG-----------------
GPNDSMGYAINAMNGGGGPGDYSSPMSGSQ--APYSDGSLG------------YDA-MHQ
GGGVTPKASGSPPLRGGDGGGWNAPPREQIPDFQPLHPDDSG------------------
--DSSDLDIKRPKL-
>C_lec3 XP_024086232.1 homeobox protein extradenticle isoform X1 [Cimex lectularius]
------------------------------------------------------------
------------------------------------MVYFLPPLKSIS------LLSLRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGVSAAAAASAAAASGQ---VQ-
DNAIEHSDYRAKLAQIRQIYHQELEKYEQACNEFTTHV----MNLLREQSRTRPITPKEI
ERMVQIIHKKFSSIQMQLKQSTCEAVMILRSRFLDAR-----------RKRRNFSKQASE
ILNEYFYSHLSNPYPSEEAKEELARKCTITVSQVSNWFGNKRIRYKKNI----GKAQEEA
NLYAAKKAAGS------------------VTKSDWLSRSSESLQAS-QTRSGASPYSMGP
-------------------------GSQGTATPMMSPAPPGA------------------
-PQDSMGYSI-GING----GDYSSPMSSAQ--TPYSDGSLG------------YEG-MHQ
GSG---KTSGSPPIR---GEGWN-PPREQIPDFQPLHPEDSG------------------
--DSSDIDIKRPKL-
>M_ext2 Medex_00071840-RA
------------------------------------------------------------
------------------------------------------------------------
-----------MRLD--------NMLIAEGVAGPEKGGGAGAAASASAAASGGP---GQP
DNAIEHSDYRAKLAQIRQIYHQELEKYEQVSTLLLAHVPFNITGVVRASEYTSPRT----
----------------------CS------------------------------------
-LQHYWRS-------------------------TSKW-----------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VHFS------------------------
------------------------------------------------------------
---------------
>G_bue1 GBUE010039-PA
------------------------------------------------------------
------------------------------------------------------------
----------MLRIKFY-------------------------------------------
---------------LRLVHHGLCFDIFQACNEFTTHV----MNLLREQSRTRPITPKEI
ERMVQIIHKKFSSIQMQLKQSTCEAVMILRSRFLDASYYKCSHNSFDMRKRRNFSKQASE
ILNEYFYSHLSNPYPSEEAKEELARKCSITVSQVSNWFGNKRIRYKKNI----GKAQEEA
NLYAAKKAAVYGRFGKYIFFFKVMLIIILFVQDNTVRR----------YRVGFTKLKLKT
TI----------------------------------------------------------
-PNNHILVLL----------DVSSL---------FT------------------------
-------------------------------NIPP-------------------------
-------DIK-----
>C_hook1 maker-scaffold845-size653622-augustus-gene-5.4-mRNA-1
MN-IERRERLAS-------------------------LSSTD---------DQ-------
-DSGSDAEQ---------------------------------------------------
-------DPR--------------------------------TCTRRAASRPGG---GQP
A-----------------------------------------------------------
-----------------------------------TR-----------KRRGNLPKQSVK
ILKHWLYVHRYRAYPSDAEKVALSQETNLTSLQVSNWFINARRRILPQMIRREGHDPQQF
TISRRGKKTTGGSGGQ------------------------HSPRGLSGARLGAAAGRRSG
SVQDHDYDDNSYRSGEDDSGGYDSSLSEGSDTAQRQPAAPWSSVIVCRYGCLQGCSVHGR
DPTSSRGEGL-FPSG----GVLTHP----E--TNYWNGPLTACVEEVTTANHKYSR-MH-
-------------------------PQETPPPTPPQEEDKEKFECLYLLVEAAVARQQEK
EREQQGLSISV----
