>A_pis1 XP_008182670.1 homeobox protein extradenticle isoform X1 [Acyrthosiphon pisum]
MNSMDEHNRMMHPTS---AML-------PQ---PYG-MSSVDPNHGAPTPPDQ--DTRKQ
-DIGEILQQIMNITDQSLDEAQARKHTLNCHRMKPSLFSVLCEIKEKT------VLSLRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGAGAAASASAAASGGP----GQ
PDNAIEHSDYRAKLAQIRQIYH--------QELEKYEQACNEFTTHV----MNLLREQS-
-RTRPI------------TPKEIERMVQIIHKKFSSIQMQLKQSTCEAVMILRSR-----
--------------FLDAR-----------RKRRNFSKQASEILNEYFYSHLSNPYPSEE
AKEELARKCSITVSQVSNWFGNKRIRYKKNI----GKAQEEANLYAAKKA----------
--------------------------------AGASPYSMGP------------------
-------ASQGTPTPLLSPAPGGG-------------------PQDSMGYSL-SLNG---
-AEYSSPMSGSQVCAQYSDGSLG------------YDPMGHQAMP---KNSGSP------
STGWN-SSHEY--QTHGMHDDSEDSSDDVDIKRPKL------S
>G_bue1 GBUE010039-PA
------------------------------------------------------------
------------------------------------------------------------
----------MLRIKFY-------------------------------------------
----------------LRLVHH--------GLCFDIFQACNEFTTHV----MNLLREQS-
-RTRPI------------TPKEIERMVQIIHKKFSSIQMQLKQSTCEAVMILRSR-----
--------------FLDASYYKCSHNSFDMRKRRNFSKQASEILNEYFYSHLSNPYPSEE
AKEELARKCSITVSQVSNWFGNKRIRYKKNI----GKAQEEANLYAAKKAAVYGRFGKYI
FFFKVMLIIILFVQDNTVRR----------YRVGFTKLKLKTTI----------------
-------------------------------------------PNNHILVLL--------
--DVSSL---------FT------------------------------------------
-------------NIPP------------DIK-----------
>F_exs1 XP_029677537.1 homeobox protein extradenticle isoform X1 [Formica exsecta]
---MDETGNMLQHGGSGVGLMGGNQGQAAQNTAGYGSMGPVDGT--ATQGPDQTVEARKQ
-DIGEILQQIMNITDQSLDEAQARKHTLNCHRMKPALFSVLCEIKEKT------VLSLRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGAGAAASASAAAAAGPP---GQ
PDNAIEHSDYRAKLAQIRQIYH--------QELEKYEQACNEFTTHV----MNLLREQS-
-RTRPI------------TPKEIERMVQIIHKKFSSIQMQLKQSTCEAVMILRSR-----
--------------FLDAR-----------RKRRNFSKQASEILNEYFYSHLSNPYPSEE
AKEELARKCGITVSQVSNWFGNKRIRYKKNI----GKAQEEANLYAAKKAAD--------
------------LEPRW--RKSHHCKSL-AAFAGASPYSMGG------------------
-------ASQGTPTPMMSPAPPGG-------------------PQDMAGYSM-GING---
-SDYGS--------QPYNDGSMG------------YDP-MHQGKA---LTGGPG------
AAGWM-QQREAVPEFPPLHDSADSDSDRENEKRPRV-------
>N_lug1 XP_022201680.1 homeobox protein extradenticle-like [Nilaparvata lugens]
------------------------------------------------------------
--------------------------------MK-------VESVAMA------LLSLRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGAGAAATASAAAAGGP----GQ
PDNAIEHSDYRAKLAQIRQIYH--------QELEKYEQACNEFTTHV----MNLLREQS-
-RTRPI------------TPKEIERMVQIIHKKFSSIQMQLKQSTCEAVMILRSR-----
--------------FLDAR-----------RKRRNFSKQASEILNEYFYSHLSNPYPSEE
AKEELARKCSITVSQVSNWFGNKRIRYKKNI----GKAQEEANLYAAKKA----------
--------------------------------AGASPYSMGP------------------
-------ASQGTATPMMSPAPPGSG-----------------GPNDSMGYAINAMNGGGG
PGDYSSPMSGSQ--APYSDGSLG------------YDA-MHQGGGVTPKASGSPPLRGGD
GGGWNAPPREQIPDFQPLHPDDSGDSSDLDIKRPKL-------
>N_lug2 XP_022186095.1 homeobox protein extradenticle-like [Nilaparvata lugens]
---MDEQNRMMHPSG-QVGMM-------PQ--PPYG-MQPVDPNHGAPATPDQ--ETRKQ
-DIGEILQQIMNITDQSLDEAQARKHTLNCHRMKPSLFSVLCEIKEKTGE----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>C_hook1 maker-scaffold845-size653622-augustus-gene-5.4-mRNA-1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------MNIERRE--
-RLASLSS----------T-----------DDQDSGSDAEQDPRTCTR--RAASRPGGGQ
PATR--------------------------KRRGNLPKQSVKILKHWLYVHRYRAYPSDA
EKVALSQETNLTSLQVSNWFINARRRILPQMIRREGHDPQQFTISRRGKKTTGGSGGQ--
----------------------HSPRGLSGARLGAAAGRRSGSVQDHDYDDNSYRSGEDD
SGGYDSSLSEGSDTAQRQPAAPWSSVIVCRYGCLQGCSVHGRDPTSSRGEGL-FPSG---
-GVLTHP----E--TNYWNGPLTACVEEVTTANHKYSR-MHPQET-------PPPTP---
------PQEEDKEKFECLYLLVEAAVARQQEKEREQQGLSISV
>C_lec3 XP_024086232.1 homeobox protein extradenticle isoform X1 [Cimex lectularius]
------------------------------------------------------------
------------------------------------MVYFLPPLKSIS------LLSLRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGVSAAAAASAAAASGQ----VQ
-DNAIEHSDYRAKLAQIRQIYH--------QELEKYEQACNEFTTHV----MNLLREQS-
-RTRPI------------TPKEIERMVQIIHKKFSSIQMQLKQSTCEAVMILRSR-----
--------------FLDAR-----------RKRRNFSKQASEILNEYFYSHLSNPYPSEE
AKEELARKCTITVSQVSNWFGNKRIRYKKNI----GKAQEEANLYAAKKAAGS-------
-----------VTKSDWLSRSSESLQAS-QTRSGASPYSMGP------------------
-------GSQGTATPMMSPAPPGA-------------------PQDSMGYSI-GING---
-GDYSSPMSSAQ--TPYSDGSLG------------YEG-MHQGSG---KTSGSPPIR---
GEGWN-PPREQIPDFQPLHPEDSGDSSDIDIKRPKL-------
>M_ext1 Medex_00068030-RA
---MDEQSRMMHPVSSQVGMM-------PQ---PYG-MQPVDPNHGAPTTPDQ--ETRKQ
-DIGEILQQIMNITDQSLDEAQARKHTLNCHRMKPALFSVLCEIKEKTDKQGLNVCEFQN
VYILSCADPQILTIRRSADINVFNRPIPEFLVGEVFTFGPTTRLSSSVG-----------
------------------------------------------------------------
------------------------------------------------------------
--------------FLRA------------------------------------------
---------------VDNFCDN--------------------------------------
--------------------------------LGGSYFELGEHF----------------
------VAAWGT------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>M_ext2 Medex_00071840-RA
------------------------------------------------------------
------------------------------------------------------------
-----------MRLD--------NMLIAEGVAGPEKGGGAGAAASASAAASGGP----GQ
PDNAIEHSDYRAKLAQIRQIYH--------QELEKYEQVSTLLLAHVPFNITGVVRASE-
-YTSPR------------T--------------------------CS-------------
-------------------------------------------LQHYWRS----------
---------------TSKW-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------VHFS------------------------------------------
-------------------------------------------
>D_mel1 FBpp0073940 FBgn0000611 exd [Drosophila melanogaster]
---MEDPNRMLAHTG---GMM------APQ---GYG-LSGQD--DGQNAGSEN--EVRKQ
KDIGEILQQIMSISEQSLDEAQARKHTLNCHRMKPALFSVLCEIKEKT------VLSIRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGGAAAASAAAASQGGSL-SIDG
ADNAIEHSDYRAKLAQIRQIYH--------QELEKYEQACNEFTTHV----MNLLREQS-
-RTRPI------------TPKEIERMVQIIHKKFSSIQMQLKQSTCEAVMILRSR-----
--------------FLDAR-----------RKRRNFSKQASEILNEYFYSHLSNPYPSEE
AKEELARKCGITVSQVSNWFGNKRIRYKKNI----GKAQEEANLYAAKKA----------
--------------------------------AGASPYSMAG------------------
-------PPSGTTTPMMSPAP----------------------PQDSMGYPM-GSGG---
-YDQ-------Q--QPYDNSMGG------------YDPNLHQDLS--------P------
-------------------------------------------
>D_sim1 FBpp0215663 FBgn0188823 exd [Drosophila simulans]
---MEDPNRMLAHTG---GMM------APQ---GYG-LSGQD--DGQNAGSEN--EVRKQ
KDIGEILQQIMSISEQSLDEAQARKHTLNCHRMKPALFSVLCEIKEKT------VLSIRN
TQEEEPPDPQLMRLD--------NMLIAEGVAGPEKGGGGAAAASAAAASQGGSL-SIDG
ADNAIEHSDYRAKLAQIRQIYH--------QELEKYEQACNEFTTHV----MNLLREQS-
-RTRPI------------TPKEIERMVQIIHKKFSSIQMQLKQSTCEAVMILRSR-----
--------------FLDAR-----------RKRRNFSKQASEILNEYFYSHLSNPYPSEE
AKEELARKCGITVSQVSNWFGNKRIRYKKNI----GKAQEEANLYAAKKA----------
--------------------------------AGASPYSMAG------------------
-------PPSGTTTPMMSPAP----------------------PQDSMGYPM-GSGG---
-YDQ-------Q--QPYDNSMGG------------YDPNLHQDLS--------P------
-------------------------------------------
